### ISSUE TITLE
No Close method for AsyncConnection?

### ISSUE THREAD

**Issue by pcolmer** [praeclarum/sqlite-net#101]
If I create a non-async Connection, there is a Close method I can access. However, there isn't a Close method for async connections. Should there be?

**Comment by scastria** [comment]
SQLiteConnectionPool is not public so it cannot be called!

**Comment by JanZeman** [comment]
You can use reflection to call it. In my attempts it worked perfectly for Android and Windows, it fires back after 3x or 4x such closed connections on iOS. Damn... I was almost tempted to go for this solution but on iOS (simulator) it does not seem to be a viable solution.

There must be a reason the creators did the Reset method internal so all in all this approach is probably not recommended but I need to close the connection time to time... :-(

        private static void CloseDatabaseConnectionViaReflection()
        {
            var assembly = typeof(SQLiteAsyncConnection).GetTypeInfo().Assembly;
            var sqLiteConnectionPoolType = assembly.GetTypes().First(t => t.Name == "SQLiteConnectionPool");
            var resetMethod = sqLiteConnectionPoolType.GetMethod("Reset");

            var sqLiteConnectionPoolSharedInstance =
                sqLiteConnectionPoolType
                    .GetFields(BindingFlags.Static)
                    .First(field => field.IsInitOnly && field.Name == "_shared")
                    .GetValue(null);

            resetMethod.Invoke(sqLiteConnectionPoolSharedInstance, null);
        }

**Comment by luminelx64** [comment]
Pls has this issue been resolved? I also need the close() method on the async connection.

**Comment by snalesso** [comment]
Up for the `CloseAsync()` method. Why is it missing?

**Comment by praeclarum** [comment]
Yeah, this is all my fault. I still use the synchronous version so the Async version gets neglected.

I've created Issue #480 to remind me to get these back in parity.

This issue will track the change to expose `SQLiteConnectionPool.Shared.Reset`

**Comment by scionwest** [comment]
> The solution is to call SQLiteConnectionPool.Shared.Reset(); This closes all of the open connections.
> This issue will track the change to expose SQLiteConnectionPool.Shared.Reset
Isn't that dangerous? If you want to just close your current connection, exposing a `CloseAsync` method on the `SQLiteAsyncConnection` would be sufficient. You don't always know what other async or parallel process might have connections still being used before you just force shut them all down. I'm not sure that the pool reset needs to be exposed if `CloseAsync` is provided.

**Comment by praeclarum** [comment]
Working on a `CloseAsync` method now.

**Comment by aphex3k** [comment]
Thank you so much!

**Comment by uwe-neuronation** [comment]
To cleare that pool call:
`SQLiteAsyncConnection.ResetPool();`
im using  **sqlite-net-pcl 1.4.118**

`_connection.GetConnection().Close();
                _connection.GetConnection().Dispose();
                SQLiteAsyncConnection.ResetPool();`
