### ISSUE TITLE
silverlight only?

### ISSUE THREAD

**Issue by ting195a** [praeclarum/sqlite-net#103]
I believe XNA also runs the same piece of code that silverlight does.

I had to change to this in order to get XNA working :
# if WINDOWS_PHONE
# define USE_CSHARP_SQLITE
# define SILVERLIGHT
# endif

sqlite-net is also ideal for embedded database for XNA games.

**Comment by praeclarum** [comment]
Thanks to the nuget package `sqlite-net-pcl` this is all taken care of for you!
