### ISSUE TITLE
WPF tips Unable to load DLL 'SQLite3': the specified module was not found

### ISSUE THREAD

**Issue by bbhxwl** [praeclarum/sqlite-net#1037]
WPF tips Unable to load DLL 'SQLite3': the specified module was not found

**Comment by VinaCaptcha** [comment]
![2021-09-30_231121](https://user-images.githubusercontent.com/33093866/135492292-19279a6c-6862-42a8-8a8c-b68e02d92001.png)
Worked 100% for me!
You can re-install SQLite packages version as my picture, don't forget Re-Build your Project before you press F5.
