### ISSUE TITLE
use in background task for windows 8 apps

### ISSUE THREAD

**Issue by TechnicHail** [praeclarum/sqlite-net#104]
I am currently trying to get a background task to update a database.
I first got everything working in a single project by following a few guides (like this one: http://timheuer.com/blog/archive/2012/08/07/updated-how-to-using-sqlite-from-windows-store-apps.aspx) however when I move everything database related over to a separate windows runtime component project I get > 200 errors.
 such as;

A public type has a namespace (‘Tasks’) that shares no common prefix with other namespaces (‘SQLite’). All types within a Windows Metadata file must exist in a sub namespace of the namespace that is implied by the file name.

and

‘SQLite.SQLiteAsyncConnection.CreateTableAsync()’ is a generic method. Windows Runtime methods cannot be generic.

Is it possible to get SQLite-net running in the background?

**Comment by cansado2930** [comment]
Hi, 
I have the same problem, but it has less errors, 24 aproximately. I have changed the platform of destination from ANY_CPU to x86,x64,ARM. I have tryed to do it, but I don't get work it. So, Could you explain me more easy what are "public (exportable) types"?
Thank you

**Comment by TechnicHail** [comment]
Change all the public classes to internal.
A background task project is a Windows Runtime component, which are class libraries that can be used in C#, C++ and javascript. To do this there need to be a bunch of restrictions on what they expose to anything using them. In this case you are hitting at least two. 1. All public classes must be sealed. 2. All public types must only expose other windows runtime types (parameters, properties, return types etc.).

Using the internal instead of public on classes (or anything else) will mean that they will not get exposed anything outside the library (they won’t be exported) and as such none of the windows runtime restrictions will apply. 
More info: https://msdn.microsoft.com/en-us/library/br230301.aspx
