### ISSUE TITLE
Retrieve multiple columns - 'raw' query

### ISSUE THREAD

**Issue by Flying--Dutchman** [praeclarum/sqlite-net#1042]
Is it possible to retrieve only 'raw' values with SQLitePCL and command parameters?
With that I mean; Execute following query:

`SELECT column1, column2, column3 FROM table1
WHERE column1 > ?
`

and only getting those values and not the corresponding C# entity?
Maybe as a `List<object[]>`

**Comment by ivosnoza** [comment]
I don't know about any method in this library and you probably need to execute raw query and then iterate results and map its values to a proper data type
```
SQLitePCL.sqlite3_stmt stQuery = SQLite3.Prepare2(connection.Handle, query);
var colLength = SQLite3.ColumnCount(stQuery);
List<object[]> result = new List<object[]>();
while (true)
{
    var step = SQLite3.Step(stQuery);
    if (step != SQLite3.Result.Row)
        break;

    object[] obj = new object[colLength];
    result.Add(obj);
    for (int i = 0; i < colLength; i++)
    {
        var colType = SQLite3.ColumnType(stQuery, i);
        switch (colType)
        {
            case SQLite3.ColType.Integer:
                obj[i] = SQLite3.ColumnInt(stQuery, i);
                break;

            // Handle other types you need
        }
    }
}
```

**Comment by Flying--Dutchman** [comment]
Thank you very much, this is exactly what I needed :+1:
