### ISSUE TITLE
How can I use foreign key constrain in SQLite for WinRT ?

### ISSUE THREAD

**Issue by Xyroid** [praeclarum/sqlite-net#107]
Hi, I am excited to use SQLite for WInRT. I am using Windows 8 Release Preview. I have downloaded the repo (https://github.com/praeclarum/sqlite-net/zipball/master) it's not opening, basically I want to see the examples within it. Moreover does SQLite for WinRT support foreign key constrain ? Can you please guide me about that thing ? Thanks.

**Comment by praeclarum** [comment]
That constraint is not support. Please monitor #100 for details.
