### ISSUE TITLE
Add secure string support to sqlite-net-sqlcipher

### ISSUE THREAD

**Issue by honguyenminh** [praeclarum/sqlite-net#1076]
Currently connection string only support key as pure string or byte array. But normally passwords are (and should) be saved in a `SecureString`. Can you add support for it?

**Comment by Sergio0694** [comment]
> "But normally passwords are (**and should**) be saved in a `SecureString`."

This is not correct. `SecureString` is not actually secure, has some well known fundamental issues, and in fact it's even not recommended and actually planned to be marked as obsolete and eventually removed entirely from the BCL. See the runtime design doc here: https://github.com/dotnet/designs/pull/147. I don't think it makes sense to add support for this as it would just be more work to then incentivize users to use a type that should just never be used in the first place.

**Comment by honguyenminh** [comment]
I have not read the docs for latest info on this type, so my bad. Closing.
