### ISSUE TITLE
No support to pass a Type to Async Insert methods

### ISSUE THREAD

**Issue by carlospuk** [praeclarum/sqlite-net#110]
It would be great if the Type parameter could also be passed to the asynchronous Insert... methods.

I've done this myself, but I don't know how to push it to source.

In SQLIte.cs, add:

   /// <summary>

        /// Inserts all specified objects.
        /// </summary>

        /// <param name="objects">
        /// An <see cref="IEnumerable"/> of the objects to insert.
        /// </param>
        /// <returns>
        /// The number of rows added to the table.
        /// </returns>
        public int InsertAll(System.Collections.IEnumerable objects, Type type, bool beginTransaction = true)
        {
            if (beginTransaction)
            {
                BeginTransaction();
            }
            var c = 0;
            foreach (var r in objects)
            {
                c += Insert(r, type);
            }
            if (beginTransaction)
            {
                Commit();
            }
            return c;
        }

In SQLIteAsync.cs, add:

```
    public Task<int> InsertAllAsync(IEnumerable items, Type type)
    {
        return Task.Factory.StartNew(() =>
        {
            var conn = GetConnection();
            using (conn.Lock())
            {
                return conn.InsertAll(items, type);
            }
        });
    }
```

**Comment by praeclarum** [comment]
This has been added!
