### ISSUE TITLE
Not creating a new Encrypted DB? (LibVer 1.8.116)

### ISSUE THREAD

**Issue by Devilcow** [praeclarum/sqlite-net#1134]
Hello, I have been chasing my tail because I thought my problems were elsewhere, but it looks like my code is not even generating an encrypted database.
This is the function to create the DB, it executes in the path I expect, creating the DB with the Password, but the DB is never encrypted. 

The code to create the database is this

        /// <summary>
        /// Create async db connection.
        /// </summary>
        /// <returns>
        /// A <see cref="Task{TResult}" /> representing the result of the asynchronous operation.
        /// </returns>
        public static SQLiteAsyncConnection CreateDBConnectionAsync(string dbName = "", string Password = null)
        {
            try
            {
                string databasePath = GetDBPath(dbName);

                if (AppSettingsFunctions.GetBoolSetting("settings_DBIsEncrypted")) //&& CoreGlobals.IsAuthenticated)
                    Password = CoreGlobals.appPassword;

                SQLiteConnectionString connectionString;

                if (!CoreGlobals.bDBEncrypted)
                    connectionString = new SQLiteConnectionString(databasePath,
                                                                    true);
                else
                    connectionString = new SQLiteConnectionString(databasePath,
                                                                    true,
                                                                    key: Password,
                                                                    postKeyAction: c =>
                                                                    {
                                                                        c.Execute("PRAGMA cipher_compatibility = 3");
                                                                    });

                var connection = new SQLiteAsyncConnection(connectionString);

                return connection;
            }
            catch (SQLite.SQLiteException ex)
            {
                DebugTools.LogException(ex);
            }
            return null;
        }

public static bool CheckDBType(string dbPath)
        {
            bool dbEncrypted = false;
            try
            {
                if (File.Exists(dbPath))
                {
                    String s = "SQLite format 3";
                    byte[] b = new byte[s.Length];
                    int bytesRead = new FileStream(dbPath, FileMode.Open).Read(b, 0, s.Length);
                    if (bytesRead > 0)
                    {
                        if (bytesRead == s.Length && s.Equals(Encoding.UTF8.GetString(b)))
                        {
                            // Unencrypted
                            dbEncrypted = false;
                        }
                        else
                        {
                            // Encrypted
                            dbEncrypted = true;
                        }
                    }
                }
            }
            catch (IOException e)
            {
                DebugTools.LogException(e);
            }
            return dbEncrypted;
        }

Any ideas on why I am not getting an encrypted DB?

Cheers!

**Comment by developernotes** [comment]
Hi @Devilcow 

It would be best to confirm your application is properly loading SQLCipher at runtime. The best way to do that is to execute the following PRAGMA statement from your connection once opened:

```
PRAGMA cipher_version;
```

This should return a string value if your application is linking SQLCipher, otherwise a plaintext SQLite library will not return a value.

**Comment by Devilcow** [comment]
Thanks! That was it, The PCL project was using the sqlCipher lib, but the Android was building with the non cipher version.

One problem I am having now is that when the program is running, I can encrypt the database, and it gets flagged as encrypted (Checking the header of the file), but once I close then re-open the app, even though I enter the proper password, it still gives me the "File Not a Database".  

I will browse the other posts, however, if you know of any starting points to check?
