### ISSUE TITLE
SQLite-net-cipher not respecting password, always allows access with any password, MAUI, .net6, .net7

### ISSUE THREAD

**Issue by needledrag** [praeclarum/sqlite-net#1149]
Hi,

I was looking to port my project from xamarin to maui and it seems that using sql-cipher-net works fine but when I change the password string passed in to the SQLiteAsyncConnection it still allows access to the db, whatever password is input.  Previously it threw with a message 'file is not a database'.

I thought this might be an issue with my code or libraries so I cloned Gerald Versluis's example (I'm using the same libraries)  and did the same thing, opened with a password, added records. Closed and reopened with a different password and it carried on as normal allowing access instead of throwing a 'file is not a database' message. 

 Geralds repo link.

https://github.com/jfversluis/MauiEncryptedSqliteSample/tree/main/MauiEncryptedSqliteSample

Has something changed for Maui or .net6/.net7?  Or is it somehow picking up SQLite-net-pcl instead even though the cipher library is installed in the project?

Regards

**Comment by nicjay** [comment]
I had the same/similar issue, what fixed it was adding this package: SQLitePCLRaw.bundle_e_sqlcipher (2.1.2 or newer).

**Comment by needledrag** [comment]
Thank you, I'll try that out.

**Comment by needledrag** [comment]
Thanks @nicjay , had to update all the SQLite packages to 2.1.3 for it to work but works as expected now.  Much appreciated.

<PackageReference Include="SQLitePCLRaw.core" Version="2.1.3" />
<PackageReference Include="SQLitePCLRaw.provider.sqlite3" Version="2.1.3" />
<PackageReference Include="SQLitePCLRaw.bundle_green" Version="2.1.3" />
<PackageReference Include="SQLitePCLRaw.provider.dynamic_cdecl" Version="2.1.3" />
<PackageReference Include="SQLitePCLRaw.bundle_e_sqlcipher" Version="2.1.3" />

**Comment by needledrag** [comment]
`<PackageReference Include="SQLitePCLRaw.core" Version="2.1.3" />
<PackageReference Include="SQLitePCLRaw.provider.sqlite3" Version="2.1.3" />
<PackageReference Include="SQLitePCLRaw.bundle_green" Version="2.1.3" />
<PackageReference Include="SQLitePCLRaw.provider.dynamic_cdecl" Version="2.1.3" />
<PackageReference Include="SQLitePCLRaw.bundle_e_sqlcipher" Version="2.1.3" />`

Updating to all these packages worked for me.
