### ISSUE TITLE
Can't assign primary key

### ISSUE THREAD

**Issue by tsf1** [praeclarum/sqlite-net#115]
My class is as follows:

public class MyObject
{
            [PrimaryKey]
            public string UniqueId { get; set; }
            public byte OtherValue { get; set; }
}

However, when I try to do the following update, I get an error saying there is no primary key:

var query = conn.Table<MyObject>();
foreach (var itm in query)
{
     itm.OtherValue++;
     conn.Update(itm, typeof(MyObject));
}

So when I look at what is happening and inspect the mapping (via var map = GetMapping (objType)), I see that it indeed does not have a PK assigned.  What am I doing wrong?  Thanks.

**Comment by johnmurphy01** [comment]
I have the same problem when updating an object. I have a primary key set and when the code gets to the GetMappings method in SQLite.cs, it returns PK = null
