### ISSUE TITLE
Failed to create backup

### ISSUE THREAD

**Issue by Nochoon** [praeclarum/sqlite-net#1155]
Hellow everyone

I want to backup encrypted database.

However, I got an error message.

error message : Exception: Failed to create backup

Is there a way to solve it?

I will attach the code I used.

-------------------------------------------------------------------------

    void Start()
    {
        Backup("TestDB");
    }

    async void Backup(string filename)
    {
        string path = Path.Combine(Application.persistentDataPath, filename + ".db");
        string destPath = Path.Combine(Application.persistentDataPath, $"{Guid.NewGuid()}.db");

        var options = new SQLiteConnectionString(databasePath: path, storeDateTimeAsTicks:true, key:"password");     
        _connection = new SQLiteAsyncConnection(options);

        await _connection.BackupAsync(destPath);
    }

**Comment by sjlombardo** [comment]
@Nochoon - This will not work for encrypted databases. SQLCipher blocks the Backup API from performing an unmatched operation, like trying to backup an encrypted databases to a non-encrypted one, or a non-encrypted database to an encrypted one. The Backup method in this project only uses a non-encrypted database as a target. As a result. you would only be able to use it to backup non-encrypted databases. Attempting to use it with a SQLCipher encrypted database will result in an error.

Making Backup work for encrypted databases would require the [Backup](https://github.com/praeclarum/sqlite-net/blob/d40846fb4399a019b9685808fb703018ba6f1cd8/src/SQLite.cs#L2152) to be changed to support opening an encrypted target database.

If you need an alternative, you could take a look at [SQLCipher Export](https://www.zetetic.net/sqlcipher/sqlcipher-api/#sqlcipher_export) function. It doesn't do exactly the same thing as the backup API, but it does support exporting a copy of a database (i.e. schema and data) to a separate attached database file.

**Comment by Nochoon** [comment]
> ne, or a non-

Thank you bro!!!!!
