### ISSUE TITLE
Multiple thread inserts?

### ISSUE THREAD

**Issue by efontana** [praeclarum/sqlite-net#117]
Hi, Thanks for adding this wrapper.  I'm new to Sqlite and are wondering about this:

I've got a single SQLIteConnection that is shared amongst threads (i've read this is ok and are also using: SQLiteOpenFlags.FullMutex|SQLIteOpenFlags.SharedCache

I've got a simple unit test that fails, i've got  test which creates 100 concurrent threads each of which allocates a new object, then retrieves the autoincrementd primary key and i'm getting duplicates?

Do I need to do my own lock to prevent this from happening?   Or am I misunderstanding what thread-safety means for sqlite?

**Comment by praeclarum** [comment]
The `Insert` method now maintains its own lock to serialize access.

Please also consider using the `Async` versions that work on a background thread.
