### ISSUE TITLE
System.DllNotFoundException: 'sqlite3' on .Net Maui Android

### ISSUE THREAD

**Issue by ataparia** [praeclarum/sqlite-net#1210]
Hi Team,
I am getting the following error - System.DllNotFoundException: 'sqlite3' when I try to run the .Net MAUI app on the android device.

This error is specially thrown from the following line in the SQLite.cs file
LibVersionNumber = SQLite3.LibVersionNumber ();

I cannot reference "sqlite-net-pcl" package directly as I am using the source code for the following files
1. SQLite.cs
2. SQLiteAsync.cs
as I have some custom behavior that I had to code in those files.

For the android project, I am referencing this nuget package(SQLitePCLRaw.bundle_e_sqlite3) and have also defined a Conditional Compilation Symbol(USE_SQLITEPCL_RAW) for my android target which should trigger the following code in SQLite.cs
SQLitePCL.Batteries_V2.Init ();

I still continue getting the same error.

Any help regarding this issue would be greatly appreciated.

Thank you in advance.

**Comment by ataparia** [comment]
Got it working following the instructions against - https://github.com/praeclarum/sqlite-net/issues/542

**Comment by ericsink** [comment]
The error message indicates that something is trying to load the native SQLite library using the base name `sqlite3`.  But builds provided by SQLitePCLRaw.bundle_e_sqlite3 have `e_sqlite3` as their base name.  And if you are defining USE_SQLITEPCL_RAW, if I recall correctly, SQLite.cs doesn't use is own DllImport declarations, preferring to use the ones provided by SQLitePCLRaw instead.  So this shouldn't be happening.

I would look to see if somehow a DllImport with `sqlite3` is still getting used.
