### ISSUE TITLE
What visualization software should I use to open encrypted db

### ISSUE THREAD

**Issue by a3cc007** [praeclarum/sqlite-net#1215]
```
            var options = new SQLiteConnectionString("1.db", true,"123");
            using (SQLiteConnection _db = new SQLiteConnection(options))
            {
                _db.CreateTable<Stock>();
                _db.CreateTable<Valuation>();
            }
```

I used the above code to generate an encrypted db file, which I can read through the program. I want to open it through visual database management software. I tried dbeaver and sqlitestudio, and both prompted "file is not a database". What should I do?

**Comment by sjlombardo** [comment]
Try [DB Browser for SQLite](https://sqlitebrowser.org/)
