### ISSUE TITLE
sqlite-net-sqlcipher  license

### ISSUE THREAD

**Issue by a3cc007** [praeclarum/sqlite-net#1216]
I referenced sqlite-net-sqlcipher via nuget, and automatically added x64/sqlcipher.dll under bin, is it a free version or a commercial version added this way?

**Comment by a3cc007** [comment]
![image](https://github.com/praeclarum/sqlite-net/assets/19948650/c3cac9c0-4f17-4d39-bf0e-13654d170f0d)

I quoted the above 2 packages, will there be a copyright issue？

**Comment by ericsink** [comment]
Are you sure the file was named `sqlcipher.dll` ?

If it was named `e_sqlcipher.dll`, then it's one of the unofficial SQLCipher builds from the SQLitePCLRaw project.  More info on those here:

https://github.com/ericsink/SQLitePCL.raw/wiki/Expectation-setting-for-e_sqlcipher

**Comment by sjlombardo** [comment]
Hello @a3cc007  - in addition to the licenses for the sqlite-net and SQLitePCLRaw packages, if you are using a version of SQLCipher under community edition (open source) terms you should provide attribution as described here:

https://www.zetetic.net/sqlcipher/license/

**Comment by a3cc007** [comment]
> Are you sure the file was named `sqlcipher.dll` ?
> 
> If it was named `e_sqlcipher.dll`, then it's one of the unofficial SQLCipher builds from the SQLitePCLRaw project. More info on those here:
> 
> https://github.com/ericsink/SQLitePCL.raw/wiki/Expectation-setting-for-e_sqlcipher

The program was compiled, and there were e_sqlite3.dll and sqlcipher.dll in the bin/x86 folder

**Comment by ericsink** [comment]
I'm not entirely sure where that build came from, but I vaguely recall maybe doing sqlcipher builds a long time ago without the e_ prefix, so that's the most likely explanation.

**Comment by a3cc007** [comment]
> I'm not entirely sure where that build came from, but I vaguely recall maybe doing sqlcipher builds a long time ago without the e_ prefix, so that's the most likely explanation.

Will there be a fee for this?

**Comment by ericsink** [comment]
If it's a build I made as part of SQLitePCLRaw, then it is based on code obtained under an open source license (mentioned by @sjlombardo above) and is distributed on nuget at no cost, with the caveats I describe in the wiki article I mentioned above.

**Comment by a3cc007** [comment]
Thanks for all the help @ericsink   @sjlombardo
