### ISSUE TITLE
Constrain error?

### ISSUE THREAD

**Issue by cognitopia** [praeclarum/sqlite-net#126]
I'm getting an error on each Insert - Constrain
Not sure what this is, the insert seems to work but the errors clog up my log.

Error:
Constraint
SOURCE: PicturePlannerHD
TARGETSITE: Int32 ExecuteNonQuery(System.Object[])
STACKTRACE:   at SQLite.PreparedSqlLiteInsertCommand.ExecuteNonQuery (System.Object[] source) [0x00000] in <filename unknown>:0 
  at SQLite.SQLiteConnection.Insert (System.Object obj, System.String extra, System.Type objType) [0x00000] in <filename unknown>:0 
  at SQLite.SQLiteConnection.Insert (System.Object obj) [0x00000] in <filename unknown>:0 
  at PicturePlannerHD.Database.UserSave (PicturePlannerHD.User record) [0x00000] in <filename unknown>:0 

Method:

public void UserSave(User record)
        {
            try
            {
                record.modStamp = DateTime.UtcNow;
                if(UserReadSafe(record.userID) != null)
                {
                    //Update existing record
                    Update(record);
                }
                else
                {
                    //Insert new record
                    Insert(record);
                }
            }
            catch(Exception ex)
            {
                Log.LogError("UserSave",ex);
            }
        }

**Comment by jlcool** [comment]
Seven years ago?
