### ISSUE TITLE
SQLIteAsyncConnection fails with unicode characters

### ISSUE THREAD

**Issue by WieserSoftware** [praeclarum/sqlite-net#131]
If you create a filename with unicode characters, it will fail when you try to open it or create tables.

My cure was to modify SqlLiteConnection in SQLite.cs as follows:

// var r = SQLite3.Open (DatabasePath, out handle); 
var utf8 = new UTF8Encoding(); 
var r = SQLite3.Open(utf8.GetBytes(DatabasePath), out handle, (int)(SQLiteOpenFlags.ReadWrite | SQLiteOpenFlags.Create), Sqlite3Statement.Zero);

This forces the database open with a UTF8 filename, and processes the database as UTF-8.

You can also use Open16, but that I believe opens the file in UTF16.

**Comment by FUR10N** [comment]
I know this is a really old ticket and that the code has changed a lot since this was made, but I still run into this issue when using SQLitePCL.raw

@praeclarum 
Is there a reason we don't call `GetNullTerminatedUtf8` when `USE_SQLITEPCL_RAW`?
(line 212 of SQLite.cs)
