### ISSUE TITLE
Multi Column Primary-Key

### ISSUE THREAD

**Issue by Otto404** [praeclarum/sqlite-net#149]
public class AB
{
    [SQLite.PrimaryKey]
    public int A_ID { get; set; }
    [SQLite.PrimaryKey]
    public int B_ID { get; set; }
}
...
new SQLiteAsyncConnection(dbPath).CreateTableAsync();
...

leads to

create table if not exists "AB"(
"A_ID" integer primary key not null ,
"B_ID" integer primary key not null )

Should be: 
CREATE TABLE AB (A_ID, B_ID, PRIMARY KEY (A_ID, B_ID))

**Comment by praeclarum** [comment]
Working on it in #280
