### ISSUE TITLE
Thread Safe and SQLiteConfig.Serialized

### ISSUE THREAD

**Issue by ianvink** [praeclarum/sqlite-net#177]
I am trying to change sqlite default to be "more" thread-safe by calling, very early
in my application (i.e. before any other use of sqlite) this code:

```
SqliteConnection.SetConfig (SQLiteConfig.Serialized);
```

I couldn't find a way to set this in SQLIte-Net

Thanks for the Awesome tool!

**Comment by markgibaud** [comment]
Hi @ianvink - can you provide a fuller code sample? Am trying to get this working but not where which class to put it in or which assemblies to reference to resolve several classes. Tried using this code:

https://code.google.com/p/sqlite-net/source/diff?spec=svn24&r=24&format=side&path=/trunk/src/SQLite.cs

But also not sure why we have to do this, as the version of SQLite-net that I'm using already has this code in?

**Comment by generik0** [comment]
@ianvink I would also be interested in this.

**Comment by JFMG** [comment]
Update your SQLite class with this property:

```csharp
[DllImport("sqlite3", EntryPoint = "sqlite3_config", CallingConvention = CallingConvention.Cdecl)]
internal static extern Result Config(ConfigOption option);
```

In the constructor of your SQLite class call
```csharp
Config(ConfigOption.Serialized);
```
