### ISSUE TITLE
VS2008/.NET 3.5 Default parameter are not permitted

### ISSUE THREAD

**Issue by okertanov** [praeclarum/sqlite-net#189]
error CS0241: Default parameter specifiers are not permitted with 
    Microsoft Visual Studio 2008 Version 9.0.30729.1 SP
    Microsoft .NET Framework Version 3.5 SP1
    Microsoft Visual C# 2008   91605-270-1843014-60709

**Comment by praeclarum** [comment]
I'm sorry but I'm not going to maintain older C# compatibility. Hope the old version still works for you.
