### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by tambovchanin** [praeclarum/sqlite-net#228]
Get library here https://components.xamarin.com/view/sqlite-net/

Compiling example for android (xamarin) get error:

Error   1   resource directory 'F:\Work\Android\SQLite.Android.Sample\obj\Debug__library_projects__\SQLite\library_project_imports\res' does not exist F:\Работа\Android\SQLite.Android.Sample\AAPT  SQLite.Android.Sample

**Comment by praeclarum** [comment]
Sorry this seems to have been a Xamarin bug. I hope it works for you now! Might I also suggest switching to the nuget `sqlite-net-pcl`.
