### ISSUE TITLE
Problems with Prepare2 when device is in SWEDEN regional settings (iOS)

### ISSUE THREAD

**Issue by neal007** [praeclarum/sqlite-net#233]
Hello,

In this method:  public static IntPtr Prepare2 (IntPtr db, string query)

I'm getting an error when a user uses SWEDEN for device region.  The query is:

"SELECT \* FROM TimeCalcTable WHERE LogID=−2 ORDER BY ID;"

The error message is:

$exception  {SQLite.SQLiteException: no such column: −2   at SQLite.SQLite3.Prepare2 (IntPtr db, System.String query) [0x00024]

Anyone know how to resolve this?  My app update just went live :(

Thanks.

**Comment by praeclarum** [comment]
You should use parameterized queries to prevent these kinds of problems:

```csharp
var rows = connection.Query<TimeCalcTable>("SELECT * FROM TimeCalcTable WHERE LogID=? ORDER BY ID", logID);
```
