### ISSUE TITLE
sqlite-net is throwing error while developoing to windows phone 8 app 

### ISSUE THREAD

**Issue by kkbandaru** [praeclarum/sqlite-net#251]
I have created windows 8 phone app, and installed SQLite for windows phone from Visual Studios Gallery.  installed Sqlite-net package nugget package.
and added the conditional symbol compilation "USE_WP8_NATIVE_SQLITE". 

even then I am getting below error.

"The type or namespace name 'Sqlite' could not be found".

Can you please help me to solve this error.

**Comment by praeclarum** [comment]
This is now supported by using the nuget package `sqlite-net-pcl`
