### ISSUE TITLE
Windows 8.1 - Document Capability

### ISSUE THREAD

**Issue by Vinnie1991** [praeclarum/sqlite-net#252]
I just found an issue which may have been a problem for this project.

Since Windows 8.1 is the Document Capability not for the Individual account, but only for the Company Accounts.
As an Individual account developer you must ask to the user where you want to save the/a file with the FilePicker.

I hate it, I want to save the database without asking in the same folder as the app is. So when the project is build in Win8.0 then it's not a problem, but when it's Win8.1 then it does.

http://blogs.msdn.com/b/wsdevsol/archive/2013/05/09/dealing-with-documents-how-not-to-use-the-documentslibrary-capability-in-windows-store-apps.aspx

**Comment by praeclarum** [comment]
I'm sorry, we're focusing our attention on UWP now.
