### ISSUE TITLE
Problem with prepared statements / escaping

### ISSUE THREAD

**Issue by jonathanlundstrom** [praeclarum/sqlite-net#262]
Hello!

We're building an iPhone and Android app using this awesome library, but have run in to some problems when it comes to escaping SQL queries and I'm not certain how to resolve them. This is an app for a marathon, and in our Runner handler we've got the following query inside a method called "GetRunnersWomen(string searchQuery)":

```
return GetRunnerList ("SELECT * FROM Runner WHERE gender = 'Kvinna' AND Id NOT IN (" + favorites + ") AND firstname LIKE '%" + query + "%' OR gender = 'Kvinna' AND Id NOT IN (" + this.GetFavoriteIDs() + ") AND lastname LIKE '%" + query + "%' ORDER BY firstname COLLATE NOCASE ASC, lastname COLLATE NOCASE ASC");
```

As you can see from above, it's not escaped which is horrible and causes nasty problems in the application. So look below for the escaped query:

```
return GetRunnerList ("SELECT * FROM Runner WHERE gender = 'Kvinna' AND Id NOT IN (?) AND firstname LIKE '%?%' OR gender = 'Kvinna' AND Id NOT IN (?) AND lastname LIKE '%?%' ORDER BY firstname COLLATE NOCASE ASC, lastname COLLATE NOCASE ASC", favorites, searchQuery, favorites, searchQuery);
```

Do note that the favorites variable above is a string in the IN format: `"32,45, 78, 97"`.

As you also see from both of the above method calls is that they point to GetRunnerList, which is a generic method we have in order to parse the SQL results and get them as Runner objects. The method looks like this:

```
private List<Runner> GetRunnerList(String pSql, params object[] args){
    mDatabaseAdapter.Connect ();
    List<Runner> runners = null;
    lock (mDatabaseAdapter.locker){
        try {
            Console.Out.WriteLine(args);
            runners = mDatabaseAdapter.DBConnection.Query<Runner>(pSql, args);
        } catch (System.NullReferenceException e) {
            Console.Out.WriteLine ("Error: {0}" + e.Message);
        }
    }
    mDatabaseAdapter.Close ();
    return runners;
}
```

The above function handles parameters in the same way as the query method in this library does, but whenever I log the params I get this `System.Object[]` and my results are obviously completely blank since the parameters and never bound.

I even tried binding the parameters straight to the Query argument, but I'm not getting any results either. I also tried simplifying the queries to only include first name but same problem.

Any help is welcome as I'm completely stuck and we need to get this escaping in place quickly.

Thanks in advance,
Jonathan

**Comment by praeclarum** [comment]
I'm closing this issue since it seems you just need to work on your query. I do believe the library should help you out a bit more here but I'll have to consider how...
