### ISSUE TITLE
spatialite support

### ISSUE THREAD

**Issue by rgl** [praeclarum/sqlite-net#267]
It would be wonderful if we could use spatial types from the spatialite library (http://www.gaia-gis.it/gaia-sins/).

I was able to use http://www.gaia-gis.it/gaia-sins/windows-bin-amd64/spatialite-4.1.1-DLL-win-amd64.zip as-is (I just had to modify the dll name on SQLite.cs to DllImport("libsqlite3-0"...). And do the initialization with:

``` csharp
var db = new SQLiteConnection(path, true);

#if DEBUG
// NB traces are written into the debugger Debug window.
db.Trace = true;
db.TimeExecution = true;
#endif

db.EnableLoadExtension(1);
db.ExecuteScalar<object>("select load_extension('libspatialite-4')");
db.EnableLoadExtension(0);

// See http://www.gaia-gis.it/gaia-sins/spatialite-cookbook/html/metadata.html
// NB this can take a while if you don't use a transaction.
db.BeginTransaction();
db.ExecuteScalar<int>("select InitSpatialMetaData()");
db.Commit();

db.CreateTable<GasStation>();

// add a column named "geometry" (POINT type) into the GasStation table.
// NB 4326 is the WGS84 [Geographic System] SRS SRID.
// TODO see if the column already exists before trying to create it.
db.ExecuteScalar<int>("select AddGeometryColumn('GasStation', 'geometry', 4326, 'POINT', 'XY')");
```

But now I want to be able to declare a geometry type on my models, e.g.:

``` csharp
public class GasStation
{
    [PrimaryKey]
    public long Id { get; set; }

       ...

    // TODO somehow make the driver create this column after the table is created
    // NB Point here is just an example of how I would like to use it.
    [Point]
    public Point Coordinates { get; set; }
}
```

And use them as normal primitive types.

There's the http://spatial.litesolutions.net/ (available on nuget too) library that already has the geometry types (which could be used to work with geometry types defined in well known text or binary). 

Or we could create/use a wrapper for the native geometry types of libgeos (that's used by spatialite).

**Comment by praeclarum** [comment]
Given that e_sqlite has support for the operations you need, I think that is the way to go. For reference, see: https://github.com/praeclarum/sqlite-net/issues/565

You would need to add a reference to `sqlite-net-base` and then a reference to the raw e_sqlite bundle. You will also need to call the raw init function for that bundle.
