### ISSUE TITLE
Connection Lifetime and Unit of Work

### ISSUE THREAD

**Issue by JoshClose** [praeclarum/sqlite-net#270]
I'm doing a WinRT (Windows Store) app.

How long should a connection live? Should I create it, do my immediate work and release it? Or can create it in the app start up, and use the same connection everywhere in my app, for the lifetime of the app running?

**Comment by praeclarum** [comment]
Please use `SQLiteAsyncConnection` for easy background execution. `SQLiteConnection` is improving on its thread safeness, but it's not complete yet.
