### ISSUE TITLE
_preserveDuringLinkMagic is never assigned to

### ISSUE THREAD

**Issue by krunk4ever** [praeclarum/sqlite-net#273]
In SQLite.cs, _preserveDuringLinkMagic is referenced in only 2 places:

```
        /// <summary>
        /// Used to list some code that we want the MonoTouch linker
        /// to see, but that we never want to actually execute.
        /// </summary>
        static bool _preserveDuringLinkMagic;
```

and

```
        static SQLiteConnection ()
        {
            if (_preserveDuringLinkMagic) {
                var ti = new ColumnInfo ();
                ti.Name = "magic";
            }
        }
```

But it never gets assigned.

**Comment by isalgueiro** [comment]
That seems to be to force MonoTouch linker to ignore that code from the class, but I don't know why anyone would want to do something like that and didn't find anything on the Interwebs....

**Comment by nurchi** [comment]
I also get a warning that since the variable is not assigned, it will always have the default value of `false`.

To get rid of the warning, I just initialise it to `false`, but I also don't understand why we would "want" to have something that never gets called...

**Comment by praeclarum** [comment]
This code has been updated to use the preserve attribute instead.
