### ISSUE TITLE
How WPF project user your  sqlite-net

### ISSUE THREAD

**Issue by fenghuanwuhen** [praeclarum/sqlite-net#278]
hello：
   Recently，I use your sqlite-net to my WPF project,But I found than It need a sqlite3.dll
in "C:\Windows\System32",Isn't?Author, I am very Worry about than,when you see the my answer,please connect me quickly ,thank you.And my email is "yefeng.chen@maxitai.com".
yefeng.chen
                                                                                   Best wish!

**Comment by praeclarum** [comment]
Please use the nuget package `sqlite-net-pcl` to do this.
