### ISSUE TITLE
Windows Universal App

### ISSUE THREAD

**Issue by nickpateman** [praeclarum/sqlite-net#279]
Hi there,

I'm making a universal app for windows 8.1 and windows phone 8.1 To get the desktop code to work I had to add a nuget reference to "SQL for Windows Runtime", this works great, but I have no idea where the Windows Phone 8 version is.

Any ideas?

Nick

**Comment by Gillardo** [comment]
Oh this would make my life sweeter... Do you have timescales?

**Comment by praeclarum** [comment]
Please update to the nuget package `sqlite-net-pcl` for a lot of improvements here.
