### ISSUE TITLE
Insert does not return primary key.

### ISSUE THREAD

**Issue by klemenf** [praeclarum/sqlite-net#283]
The comment above the method "public int Insert (object obj)" in SQLite.cs says the method returns the primary key of the inserted row. The method however returns the count of inserted rows. What's the correct behaviour?

**Comment by praeclarum** [comment]
I improved the doc comment: https://github.com/praeclarum/sqlite-net/commit/4cb1296073b9e8b721a6ddb2c26ae03edd2a6130
