### ISSUE TITLE
Different ENum storage definition

### ISSUE THREAD

**Issue by DuskoV** [praeclarum/sqlite-net#31]
This is more of the feature request, but not sure where to post it:

Add support for different types on Enum storage. For example, they can be stored as int, char or string

SQLiteNet attributes for ENum types 

<pre>
public class EnumCharAffinityAttribute : Attribute  //Stored as char(1)
{
}
public class EnumStringAffinityAttribute : Attribute  //Stored as varchar(50) -> string name of ENum value
{
}
public class EnumInt32AffinityAttribute : Attribute  // stored as integer
{
}</pre>
Code Declaration:
<pre>
public enum PersonType {Child = 'C', Adult = 'A', Senior = 'S'}
public enum PersonAge {ChildAge = 0, AdultAge = 21, SeniorAge = 40}
</pre>

Sample class declaration:
<code>
public class Person
{
    public Person () { }
    [PrimaryKey, AutoIncrement]
    public int ID { get; set; }
    public string FirstName { get; set; }
    public string LastName { get; set; }

```
[EnumCharAffinity]
public PersonType Type {get; set;}
[EnumInt32Affinity]
public PersonAge Age {get; set;}
```

}</code>

**Comment by appSoluteDE** [comment]
I added an attribute to store enum values as text.
See pull request #439
