### ISSUE TITLE
System.FormatException with Italian region on WP8

### ISSUE THREAD

**Issue by vunder** [praeclarum/sqlite-net#311]
Current implementation has some problem with processing DateTime with Italian regional settings.
On WP8 Italian regional settings has point '.' as time separator (e.g. 8.14, instead of 8:14). When storeDateTimeAsTicks is False, sqlite-net is using "yyyy-MM-dd HH:mm:ss" as convertion template. But with Italian regional settings colon ':' time separator is replasing with point '.', because on WP8 (not WP8.1) point is the time separator. After moving database to WP8.1 application cannot process DateTime columns because WP8.1 has another separator (':').
My suggestion is to make small change in SQLite.cs, line 2182 when DateTime is saving in the database:

``` C#
SQLite3.BindText (stmt, index, ((DateTime)value).ToString ("yyyy-MM-dd HH:mm:ss"), -1, NegativePointer);
```

change to

``` C#
SQLite3.BindText (stmt, index, ((DateTime)value).ToString ("yyyy\\-MM\\-dd HH\\:mm\\:ss"), -1, NegativePointer);
```

Backslash makes system convert DateTime type to the string with separators that are in the format, without consideration of current regional settings.

**Comment by ps-mzametter** [comment]
Same problem also occurs for some German users. Maybe it would be better to use
```csharp
return DateTime.ParseExact(text, "yyyy-MM-dd HH:mm:ss", CultureInfo.InvariantCulture);
```

instead of 
```csharp
return DateTime.Parse (text);
```

in SQLite.Net.SQLiteCommand.ReadCol(IDbStatement stmt, Int32 index, ColType type, Type clrType). This solution would also have a positive impact on performance, when parsing the string.

**Comment by praeclarum** [comment]
This has been fixed!
