### ISSUE TITLE
Insert() always returns 1

### ISSUE THREAD

**Issue by Freddixx** [praeclarum/sqlite-net#312]
Hi,

I really think this is a bug: Whenever I am adding a new object to my DB the insert method returns 1 while the ID member of the object is properly updated. For example:

`int iDBId = App.DB.Insert(i);`

returns 1 while - in this case -

`i.DBId; // my PK member`

returns 76 (which is the correct value).

Any ideas? Am I doing something wrong here? Thanks in advance, cheers, Fred.

**Comment by praeclarum** [comment]
I updated the docs so hopefully this won't trick anyone else.
