### ISSUE TITLE
Annotations do not work when classes are in a different project

### ISSUE THREAD

**Issue by Freddixx** [praeclarum/sqlite-net#323]
All my model classes are in a shared project as I share them with a background task on Windows Phone. When I launch my Windows Phone 8.1 app SQLite-net does not seem to parse the annotations as I kepp getting  `dont know about..` exceptions for properties I excluded explicitely using the `[Ignore]` annotations.

Does somebody have a workaround for this? I'd be more than happy if I could fix that.

**Comment by jortiz56** [comment]
Hi Freddixx did you solved this problem? I'm having the same problem.

**Comment by Freddixx** [comment]
The solution was quite simple: I moved to the origin of this project and used the portable version: https://www.nuget.org/packages/SQLite.Net-PCL/

**Comment by jortiz56** [comment]
Waoo !! I went to the code of the library and fixed the methods but I still
don't trust it will fix all. Thanks man I will try your method.

On Wed, Jul 15, 2015 at 12:47 PM, Freddixx <notifications@github.com> wrote:

> The solution was quite simple: I moved to the origin of this project and
> used the portable version: https://www.nuget.org/packages/SQLite.Net-PCL/
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/praeclarum/sqlite-net/issues/323#issuecomment-121675988>
> .
>



-- 
Juan Ortiz

**Comment by praeclarum** [comment]
This has been fixed in version 1.5.
