### ISSUE TITLE
Implementing sqlite3_key sqlite3_rekey

### ISSUE THREAD

**Issue by geocine** [praeclarum/sqlite-net#324]
I am looking for an implementation of the following encryption layers for the SQLite3 DB using wxSQLite3 

``` C
int sqlite3_key(
  sqlite3 *db,                   /* Database to be rekeyed */
  const void *pKey, int nKey     /* The key, and the length of the key in bytes */
);

int sqlite3_rekey(
  sqlite3 *db,                   /* Database to be rekeyed */
  const void *pKey, int nKey     /* The new key, and the length of the key in bytes */
);

```

Get DLL here: https://github.com/rindeal/wxSQLite3-VS

Add the following to **SQLiteConnection**

``` csharp
/// Provide a way to set or change database encryption key
/// </summary>
/// <param name="key"></param>
public void SetDbKey(string key)
{
    var r = SQLite3.Rekey(Handle, key, key.Length);
    if (r != SQLite3.Result.OK)
    {
        string msg = SQLite3.GetErrmsg(Handle);
        throw SQLiteException.New(r, msg);
    }
}

/// <summary>
/// Provide a way to decrypt your database
/// </summary>
/// <param name="key"></param>
public void Key(string key)
{
    var r = SQLite3.Key(Handle, key, key.Length);
    if (r != SQLite3.Result.OK)
    {
        string msg = SQLite3.GetErrmsg(Handle);
        throw SQLiteException.New(r, msg);
    }
}
```

Add the following to **SQLite3**

``` csharp
[DllImport("sqlite3", EntryPoint = "sqlite3_key", CallingConvention = CallingConvention.Cdecl)]
public static extern Result Key(IntPtr db, [MarshalAs(UnmanagedType.LPStr)] string pKey, int nkey);

[DllImport("sqlite3", EntryPoint = "sqlite3_rekey", CallingConvention = CallingConvention.Cdecl)]
public static extern Result Rekey(IntPtr db, [MarshalAs(UnmanagedType.LPStr)] string pKey, int nkey);
```

Usage:

``` csharp
var db = new SQLiteConnection("sample.db");
db.SetDbKey("yourpassword"); // you only have to do this once
db.Key("yourpassword"); // to decrypt database
```

**Comment by mittt** [comment]
Sorry for the questions, I'm knowage in .NET is not so deep. Could you help.

How can I reference those DLLs? 

Also is it possible to build wxSQLite3-VS for ARM.

The app i'm working on is a Windows 8.0 Store app and I need encrypted SQLite Db there, is this method applicable there?

**Comment by mittt** [comment]
I was able to use this method, but my application failed the Windows Store validation:
* sqlite3.dll has failed the AppContainerCheck check.
* API ****  in kernel32.dll is not supported for this application type. sqlite3.dll calls this API. (a long list of those)

I there really a way to pass those? Maybe if i build wxSQLite3-VS with the appropreate flags?

**Comment by praeclarum** [comment]
I recently added support for SQLCipher by adding a `SetKey` method that executes `pragma key = 'secret'`

I'm not sure if we want to also support wxSQLite3 at this time. Sorry!
