### ISSUE TITLE
enum defined as byte can not be deserialized

### ISSUE THREAD

**Issue by DuskoV** [praeclarum/sqlite-net#33]
This is working:
public enum ColorType {Blue = 1, Red = 2, Green = 4, White = 8 }

This is NOT working:
public enum ColorType : byte {Blue = 1, Red = 2, Green = 4, White = 8 }

**Comment by ctyar** [comment]
This bug still exists in 1.0.11

**Comment by ivanstus** [comment]
Still exists in 1.3.3

**Comment by praeclarum** [comment]
Writing a test now...

**Comment by praeclarum** [comment]
I added a test and it seems to be fixed now.
