### ISSUE TITLE
SQLite.cs is not functional at all while SQLiteAsync.cs is working well

### ISSUE THREAD

**Issue by alshakir** [praeclarum/sqlite-net#338]
Im not sure if this is an issue, but I am working on a windows 8.1 Universal APP

I noticed that using the Synchronous library will not persist tables and will not create the db file
e.g.

SQLiteConnection con = new SQLiteConnection("myData.db");

trying to check if the file was created result in an exception FileNotFoundException

while doing the same with
SQLiteAsyncConnection con = new SQLiteAsyncConnection("myData.db");

then I can find the file and I can persist my tables and data..

Is the synchronous library deprecated?

**Comment by Freddixx** [comment]
Just to be sure: Have you tried setting your path as follows:

    var path = Path.Combine(Windows.Storage.ApplicationData.Current.LocalFolder.Path, "myData.db");
    new SQLiteAsyncConnection(path);

**Comment by alshakir** [comment]
The introduction didnt setup the path the way you did. Moreover, on special note section of the introduction page, it says :" Database file will always be created in the path returned by ..."
That implies it is done for you automatically. Also, it works fine for the async object; why not for the sync??

So answering your question:
No, I did the same code on the introductory page!

Thanx for response

**Comment by ACzero** [comment]
I have the same problem while developing WP8.1 APP(not silverlight)

**Comment by ACzero** [comment]
I set the path like this,and it work,maybe you can try
```
var path = Windows.Storage.ApplicationData.Current.LocalFolder.Path + "\\myData.db";
conn = new SQLiteConnection(path);
```
