### ISSUE TITLE
SqlType mapping for UInt32 and Int64

### ISSUE THREAD

**Issue by pcolmer** [praeclarum/sqlite-net#342]
The code in SqlType says:

```
        } else if (clrType == typeof(UInt32) || clrType == typeof(Int64)) {
            return "bigint";
```

Since SQLite actually treats any integer as 1-8 bytes depending on the size of the value (https://www.sqlite.org/datatype3.html), it might make more sense to return "integer" instead, just as with the logic test in the preceding lines.

The use of "bigint" actually becomes a problem if the primary key is defined as UInt32 or Int64 as "bigint" isn't a valid PK type and any attempt to update a record results in a SQLite error. Changing the code to return "integer" instead resolves the problem.

**Comment by maxcabral** [comment]
+1 I just did this for my own project. Here's a pull request:

https://github.com/praeclarum/sqlite-net/pull/345

**Comment by bamanow** [comment]
Also there is a problem with this line if entity Id is long (Int64). Sqlite just doesn't allow autoincrement bigint primary keys.

**Comment by burgua** [comment]
@praeclarum, should this issue be closed? 
It looks like @maxcabral  solved https://github.com/praeclarum/sqlite-net/pull/345 this problem

**Comment by praeclarum** [comment]
Closing!
