### ISSUE TITLE
Can i force the path of the required SQLite.dll ?  

### ISSUE THREAD

**Issue by bomanden** [praeclarum/sqlite-net#343]
Hi 
I'm using prettyBin (http://www.nuget.org/packages/PrettyBin/1.0.3)
Moves all DLLs to a lib folder. 
But it also makes SQlite-net not working. 
Can I set or force the path of the SQlite.dll to SQlite-net ? 
Tried moving it to system32 ( suggested in another forum , but that does not work )

Hope someone can help me out. 

-Bo

**Comment by nurchi** [comment]
Before making any calls to `sqlite-net` try adding the following line (preferable in the `Program.cs`):

			Environment.SetEnvironmentVariable("PATH", "path-to-your-lib-folder;"+Environment.GetEnvironmentVariable("PATH"), EnvironmentVariableTarget.Process);

This sets the `PATH` environment variable at runtime only to your process, without affecting the system or user level environment.

**Comment by praeclarum** [comment]
This is a bit out of scope for this project. I hope you find a solution!
