### ISSUE TITLE
Syntax errors on object insertion

### ISSUE THREAD

**Issue by smattox** [praeclarum/sqlite-net#348]
Using the most recent Android .dll, I encounter an exception upon attempting to create a table:

02-11 10:36:22.736 E/mono    (18479): Unhandled Exception:
02-11 10:36:22.736 E/mono    (18479): SQLite.SQLiteException: near ")": syntax error
02-11 10:36:22.736 E/mono    (18479):   at SQLite.SQLite3.Prepare2 (IntPtr db, System.String query) [0x00000] in <filename unknown>:0 
02-11 10:36:22.736 E/mono    (18479):   at SQLite.SQLiteCommand.Prepare () [0x00000] in <filename unknown>:0 
02-11 10:36:22.736 E/mono    (18479):   at SQLite.SQLiteCommand.ExecuteNonQuery () [0x00000] in <filename unknown>:0 
02-11 10:36:22.736 E/mono    (18479):   at SQLite.SQLiteConnection.Execute (System.String query, System.Object[] args) [0x00000] in <filename unknown>:0 
02-11 10:36:22.736 E/mono    (18479):   at SQLite.SQLiteConnection.CreateTable (System.Type ty, CreateFlags createFlags) [0x00000] in <filename unknown>:0 
02-11 10:36:22.736 E/mono    (18479):   at TI_Mobile_Platform_Android.AndroidDatabaseHandler.GetConnection (System.String id, System.Type type) [0x00046]
...

Possibly relevant additional data: I am attempting to use a generic wrapper class to attach an appropriate primary key, as I do not possess the ability to attach the relevant attributes to the classes themselves, and in some cases I need to jury-rig a combination key. The wrapper appears as follows:

``` C#
private class DatabaseEntry<T>
{
    private long _Key;

    [PrimaryKey]
    public long Key
    {
        get
        {
            return _Key;
        }
    }

    public T Data;

    public DatabaseEntry() { }

    public DatabaseEntry(long key, T data)
    {
        _Key = key;
        Data = data;
    }
}
```

The type T does not appear to matter to the exception, as I get it even with something as simple as object.

**Comment by nurchi** [comment]
Not entirely sure if this is relevant, but try setting your PK type to `int` instead of `long`.

I remember having issue with that on Windows.

**Comment by smattox** [comment]
I will give it a shot, though that poses some problems in and of itself. Not having composite keys, I needed the long in order to support concatenation of what is together the unique row identifiers: an 8-digit ID and a date. Without having enough digits to just concatenate, I'll have to come up with something more clever.

**Comment by praeclarum** [comment]
I'm sorry but this class just isn't a good table class. The primary key needs to be settable. Also, the table mapper does not look deeply in nested objects so your `T Data` would not be serialized.

I believe #422 would help your case, but it has not been worked on.
