### ISSUE TITLE
SQLiteConnection in PCL class

### ISSUE THREAD

**Issue by sely2k** [praeclarum/sqlite-net#349]
Hi. i've created an universal app (with sqlite-net referenced by nuget) and a PCL for host the model of my db. the problem is that  when i call (in the pcl) 

SQLiteConnection(_path)
i recieve this error 

"Something went wrong in the build configuration.  This is the bait assembly, which is for referencing by portable libraries, and should never end up part of the app.  Reference the appropriate platform assembly instead."

i've tried to use a relative path (like sqltest.db) or absolute path 
DB_PATH = Path.Combine(Path.Combine(ApplicationData.Current.LocalFolder.Path, "sample.sqlite"));

**Comment by nurchi** [comment]
What exactly do you mean by "universal app"?

**Comment by hazzik** [comment]
@nurchi probably it means [Xamarin Universal (iOS x64/x86)](http://developer.xamarin.com/samples/Hello_ComplexUniversal/)

**Comment by sely2k** [comment]
no. 
i means the visual studio Universal app. 
i've created an universal app with visualstudio (non xamarin) with windows phone 8.1 app, windows 8.1 app and a "shared project".
I've also creeated a PCL library external (for the model)
i've added (via nuget) sqlite-net at the app and "sqlite-pcl net" to the pcl library. (of course i've referenced the class windows phone sqlite 8.1" to the windows phone app.
i haven't find a way for this architecture.
can you help me?

**Comment by nurchi** [comment]
Because SQLite-net uses DLL-imports, there is a slight chance that it might not work with PCL.
We'd be able to help more if you provided some code, and where the exception occurs. It might be something inside the `sqlite.cs` file (a typo or something somewhere among the `#define ...` and `#if ... #endif` statements...

**Comment by sely2k** [comment]
i've added a basic solution on github https://github.com/sely2k/Universal-Sqlite
i've added also the entire procedure for link sqlite-net lib
the error is
> Something went wrong in the build configuration.
> This is the bait assembly, which is for referencing by portable libraries, and should never end up part of the app.
> Reference the appropriate platform assembly instead.
if you can help me in find a solution will be great!
tnk

**Comment by praeclarum** [comment]
If you upgrade to `v1.4`+ this should all be fixed. Thanks!
