### ISSUE TITLE
SQLiteAsyncConnection Problem

### ISSUE THREAD

**Issue by prasannavl** [praeclarum/sqlite-net#352]
The SQLiteAsyncConnection currently, executes the Func each time its performs a query. Now, this in most scenarios could be ideal, but the problem is how it manages its connection. 

The only reason for the design decision to executes the Func that I can think of, instead of a connection directly is so that that this could possibly create a new connection. When we're providing a direct connection, it might as well be done without a Func. It just becomes an unnecessary indirection. 

But what's alarming is that if you indeed provide a Func that creates a new connection, now a new problem is created. The connection lifetime management becomes tedious. Since the there's no way to close the connection without holding on to the connection itself externally. And if it does create a new connection, the lock becomes redundant.

Now, the only way to really make use of the Async properly is to pass in the same connection through the func, while both the connection, and the async wrapper being managed explicitly. This opens up more responsibilities for the class than it ought to be dealing with it.

I feel the entire of Async functionality here is misleading and creates more problems (or at-the-least encourages anti-patterns) than it really solves. Perhaps, pull it out of the stable packages for now?

PS: I also feel the ConnectionPool is misleading. Its not really a pool. It just look up a dictionary and manages a single connection for each string. Its no pool of connections.

**Comment by praeclarum** [comment]
You make great observations but you are glossing over a lot of real world problems this library faces and making some assumptions. You assume that accessing the DB from multiple threads would gain some perf increase when in fact this library is horribly IO bound. Issuing two IO requests simultaneously does not magically make the IO system faster. Also, when doing multiple operations, a user's code must be designed to handle BUSY errors. No one write's their code that way. They expect the DB to work as simply as its API contract dictates.

In fact, the main goal of the Async connection is to easily take pressure off the UI thread. It is not there for any radical performance improvements.

That said, you may be interested in #505 where we will start allowing parallel reads and writes. Maybe some day parallel reads will be supported too - but only when performance numbers show it would help.

Thanks for your comments!
