### ISSUE TITLE
Insert, misleading summary.

### ISSUE THREAD

**Issue by MKBreeg** [praeclarum/sqlite-net#354]
Is the intended return of the "Insert" method the number of rows added to the table, or is it the latest key inserted? Because if the intended return is the latest PK, then the return shouldn't be "count".
Thanks in advance.

**Comment by nurchi** [comment]
This might help:
https://github.com/praeclarum/sqlite-net/issues/283

**Comment by praeclarum** [comment]
I improved the doc comment: https://github.com/praeclarum/sqlite-net/commit/4cb1296073b9e8b721a6ddb2c26ae03edd2a6130
