### ISSUE TITLE
Alias Table and Column Names

### ISSUE THREAD

**Issue by johnmurphy01** [praeclarum/sqlite-net#355]
I have a Windows Universal app that uses Sqlite-Net. The server that I am communicating with will synchronize the client's local database. It does this by pulling down either the entire or part of a sqlite script. I save this file locally and then reference it using Sqlite-Net. My problem is, the table/column names are not what I want to use when referencing the data.

Example:
In the sqlite file, there is a table called sets that has these columns (_id, __created_on, name, type, etc...)

I would rather have my Sets object use the following naming convention for the columns(ID, CreatedOn, Name, Type).

I've tried using the Attributes to change the table/column names but it doesn't seem to be working. When I run my query, I get no data back. If I change the class and property names to their actual representation within sqlite, I get the expected data.

```
   [SQLite.Table("sets")]
   public class Sets
   {
    [SQLite.PrimaryKey, SQLite.AutoIncrement, SQLite.Column("_id")]
    public int ID { get; set; }

    [SQLite.Column("type")]
    public int Type { get; set; }

    [SQLite.Column("flags")]
    public int Flags { get; set; }

    [SQLite.Column("name")]
    public String Name { get; set; }
     }
```

Am I using the attributes correctly or is there a potential problem with aliasing columns and tables in sqlite-net?

**Comment by nurchi** [comment]
You didn't include `__created_on` field in the class description, otherwise you're doing everything right. The sole purpose of the `Column` attribute is to do exactly what you're doing...

**Comment by praeclarum** [comment]
Everything looks great!
