### ISSUE TITLE
SQLite.SQLiteException: unable to close due to unfinalized statements or unfinished backups ...

### ISSUE THREAD

**Issue by JeroenBer** [praeclarum/sqlite-net#357]
We get this exception sometimes (not reproducible) in a store app.

SQLite.SQLiteException: unable to close due to unfinalized statements or unfinished backups at 
SQLite.SQLiteConnection.Close() 

Would be better to use Close_v2 ?

**Comment by AArnott** [comment]
+1, in a desktop app.

**Comment by Dan1ve** [comment]
+1, in an Android application

**Comment by kevincwq** [comment]
+1, in a desktop app.

**Comment by sampsonye** [comment]
+1, in a desktop app.

**Comment by praeclarum** [comment]
As of `v1.5` the library now uses `close_v2` everywhere. Sorry for the trouble!

**Comment by scastria** [comment]
Version 1.5 of what?  This nuget's latest version is 1.4.118.  Is there a version 1.5 somewhere?
