### ISSUE TITLE
Ignore attribute doesn't work for classes in external assemblies

### ISSUE THREAD

**Issue by demas** [praeclarum/sqlite-net#359]
I have class with property:

``` csharp
[Ignore]
public ObservableCollection<MyEntity> MyEntities { get; set; }
```

It works fine when I create the table:

``` csharp
_connection.CreateTableAcync<MyClass>().Wait();
```

Now I move this class to external assembly (project) and I have an error when the sqlite-net is trying to create table. The error messages said that there is unknown type ObservableCollection. Looks like the [Ignore] attribute doesn't work if the class in external assembly (project).

I am trying to debug the sqlite-net code. Here is [the fragment](https://github.com/praeclarum/sqlite-net/blob/master/src/SQLite.cs#L1787):

``` csharp
var ignore = p.GetCustomAttributes (typeof(IgnoreAttribute), true).Count() > 0;

if (p.CanWrite && !ignore) {
   cols.Add (new Column (p, createFlags));
}
```

I have `ignore == false` for my field with [Ignore] attribute.

**Comment by praeclarum** [comment]
This has been fixed in v1.5. Sorry for the delays!
