### ISSUE TITLE
Documentation error on home page and Getting Started page

### ISSUE THREAD

**Issue by augiem** [praeclarum/sqlite-net#363]
This bit of documentation on the home page and getting started page shows invalid SQLite syntax, using a single quote to surround the column names. According to this:
https://www.sqlite.org/lang_keywords.html

A single-quoted string is a string literal, not an identifier, so this cannot return the correct values from the table. Instead, the column identifiers should be surrounded by escaped double quotes. 

public class Val {
    public decimal Money { get; set; }
    public DateTime Date { get; set; }
}
public static IEnumerable<Val> QueryVals (SQLiteConnection db, Stock stock)
{
    return db.Query<Val> ("select 'Price' as 'Money', 'Time' as 'Date' from Valuation where StockId = ?", stock.Id);
}

**Comment by nurchi** [comment]
Continue reading the same page:

    For resilience when confronted with historical SQL statements, SQLite will sometimes bend the quoting rules above:
    
     - If a keyword in single quotes (ex: 'key' or 'glob') is used in a context where an identifier is allowed but where a string literal is not allowed, then the token is understood to be an identifier instead of a string literal.
    
     - If a keyword in double quotes (ex: "key" or "glob") is used in a context where it cannot be resolved to an identifier but where a string literal is allowed, then the token is understood to be a string literal instead of an identifier.
    ...

**Comment by augiem** [comment]
It doesn't work in my testing.
