### ISSUE TITLE
Status of sqlite-net vs. SQLite.Net PCL

### ISSUE THREAD

**Issue by ps30** [praeclarum/sqlite-net#365]
We have been using sqlite-net with ericsink/SQLitePCL.raw with our C# WPF app and have been very happy with the code.  Since it has been a few months without any activity or updates to sqlite-net (there have been updates to SQLitePCL.raw), we were all curious if there will be more development on sqlite-net or should we start moving to the more active SQLite.Net PCL 3.0.5 by Øystein Krog. Just a heads up would be great, as we are happy now and willing to wait _if_ there will be future development of this code.  Thanks!

**Comment by aredfox** [comment]
Would like to know this as well!

**Comment by corliss** [comment]
Sure would like an answer to this. Even a brief status update would be very helpful.

**Comment by CADbloke** [comment]
probably this: https://github.com/aspnet/Microsoft.Data.Sqlite

**Comment by praeclarum** [comment]
Hi this project is under active development - I'm sorry if I don't release as often as you would like.

Please use `sqlite-net-pcl` as the official distribution.

I have no control over what Øystein Krog publishes.
