### ISSUE TITLE
Using with MonoMac - but which sqlite3.dll?

### ISSUE THREAD

**Issue by polgarijog** [praeclarum/sqlite-net#370]
I'm developing a cross-platform application for .NET 4.5/Monomac. I decided to use sqlite with this great connector and under Windows it works perfectly.

But before creating my OSX bundle I need an sqlite3.dll assembly for OSX/Mono. But where? Please help me to find it.

Thank you guys

**Comment by polgarijog** [comment]
btw i'ts okay if I can use the built-in sqllite3 in osx 10.9...somehow:)

**Comment by polgarijog** [comment]
okay, I've rewrited the path to "/var/lib/sqllite3" and its okay. But in this way I have to compile one version for OSX and one for Win, so it's far not the best solution.

**Comment by praeclarum** [comment]
Hello, yes using the one built-in to the OS is best.

The nuget package `sqlite-net-pcl` takes care of all of this for you.
