### ISSUE TITLE
SQLitePCL.raw 0.8.0 

### ISSUE THREAD

**Issue by mehdyhaghy** [praeclarum/sqlite-net#371]
after updating xamarin.forms prject packages to SQLitePCL.raw package to 0.8.0 ,
sqlite.net pcl stops working.It looks for SQLitePCL.raw_basic (≥ 0.7.1) but it can't match it with  SQLitePCL.raw_basic  0.8.0

**Comment by praeclarum** [comment]
Please try updating as most of our packaging bugs have been worked out. Thank you!
