### ISSUE TITLE
The type or namespace name 'Community' could not be found

### ISSUE THREAD

**Issue by stefan89** [praeclarum/sqlite-net#373]
I tried to implement this library to a Windows Phone project but I couldn't get it work.

The steps I did:
- Added "sqlite-net" 1.0.8 package from Frank Krueger to my Windows Phone 8.0 project using the nuget package manager
- Downloaded and installed the "sqlite-wp81-winrt-3081002.vsix" visual studio extension from http://sqlite.org/download
- Added project extension reference to the sqlite-wp81-winrt-3081002.vsix visual studio extension.

Result when building the Windows Phone app:
The type or namespace name 'Community' could not be found (are you missing a using directive or an assembly reference?

This error occurs in class "SQLite.cs" at:
# if USE_CSHARP_SQLITE

using Sqlite3 = Community.CsharpSqlite.Sqlite3;
using Sqlite3DatabaseHandle = Community.CsharpSqlite.Sqlite3.sqlite3;
using Sqlite3Statement = Community.CsharpSqlite.Sqlite3.Vdbe;
# elif USE_WP8_NATIVE_SQLITE

What step did I missed?

**Comment by BenjaminChambers** [comment]
I just created a test application, targeting Windows Phone 8.1. I used Nuget to add SQLite-net version 1.08, and did not add any other extensions. The project compiles fine.

I would recommend removing the extension you downloaded directly from SQLite.org, and just use the nugget package. It seems to do just fine.

**Comment by stefan89** [comment]
Thanks @BenjaminChambers for your response.

I tried what you said (removed the extension reference) but I still get the same error when building the project.

In my case I am targeting Windows Phone 8.0.

**Comment by praeclarum** [comment]
Would you please try using the latest `sqlite-net-pcl` nuget? This should all be fixed these days.
