### ISSUE TITLE
Exception when setting temp_store_directory: SQLite.Net.SQLiteException: not a writable directory

### ISSUE THREAD

**Issue by ps-sstumpfl** [praeclarum/sqlite-net#374]
I'm using _sqlite-net v4.0.30319_ in my winRT (Windows 8.1 Application)

On App startup, when setting up my database, I'll set the sqlite temp directory:

``` c#
string tempPath = Windows.Storage.ApplicationData.Current.TemporaryFolder.Path;
DBConnection().Execute(string.Format("PRAGMA temp_store_directory = '{0}';", tempPath));
```

This works just fine on my personal pc and for 95% of my users, but there are many crash reports where this doesn't work.

SQLite will throw an exception which tells me the directory is not writeable (Although this is the local app directory which should be writeable at any time):
_SQLite.Net.SQLiteException: not a writable directory_

Attached is the stacktrace:

```
SQLite.Net.SQLiteException: not a writable directory
   at SQLite.Net.Platform.WinRT.SQLiteApiWinRT.Prepare2(IDbHandle db, String query)
   at SQLite.Net.SQLiteCommand.ExecuteNonQuery()
   at SQLite.Net.SQLiteConnection.Execute(String query, Object[] args)
   at .Services.Database.DatabaseService.SetTempDirectory()
   at .Services.Database.DatabaseService..ctor(String dbName)
   at .App.SetupDatabaseService()
```

While investigating this issue I also found out that _temp_store_directory_ is deprecated and shouldn't be used anymore:

https://www.sqlite.org/pragma.html
_This pragma is deprecated and exists for backwards compatibility only. New applications should avoid using this pragma. Older applications should discontinue use of this pragma at the earliest opportunity. This pragma may be omitted from the build when SQLite is compiled using SQLITE_OMIT_DEPRECATED._
I don't know what else I could use since setting temp_store to MEMORY didn't worked either.

**And here is the related issue why I've to set the temp_directory manually in the first place:
https://github.com/praeclarum/sqlite-net/issues/78**

**Comment by praeclarum** [comment]
If you upgrade your package to `sqlite-net-pcl` everything should work more smoothly.
