### ISSUE TITLE
SQLite encryption/password protected

### ISSUE THREAD

**Issue by ferpega** [praeclarum/sqlite-net#375]
Nowadays, with praeclarum/sqlite-net, are there any way to encrypt an unencrypted database-file and/or open/connect to an already encrypted database-file ?

If it is not ready yet, will be very complex to implement it ?

Thanks.

**Comment by benbristow** [comment]
+1 on this please. Any information would be great.

**Comment by adamfisher** [comment]
+1

**Comment by penderi** [comment]
+1

**Comment by Maverick2805** [comment]
Same here

**Comment by mittt** [comment]
+1

**Comment by cabanel** [comment]
1

**Comment by albireo** [comment]
+1

**Comment by fuct** [comment]
+1
Goes without saying, the System.Data.Sqlite implementation uses it (https://system.data.sqlite.org/) - which i use for Desktop apps. And i'd LOVE to see it cross over into yours, which i use for mobile development. It definitely helps as an extra layer of security.

**Comment by silversens** [comment]
+1, I would definitely love that too

**Comment by yarmenteros** [comment]
+1

**Comment by praeclarum** [comment]
I have to admit I'm pretty ignorant of the encryption options out there for sqlite.

I've seen on other bugs (#476) that [SQLCipher](https://www.zetetic.net/sqlcipher/) is brought up and that there would be some benefit to supporting them as a driver.

Would this be sufficient, or are there better approaches you would like to see implemented?

**Comment by DamianSuess** [comment]
It's worth it as a start.

**Comment by praeclarum** [comment]
This is being worked on in #597

**Comment by praeclarum** [comment]
I could use some help testing this out. Would you mind grabbing `sqlite-net-sqlcipher` `1.5.176-beta` [from nuget](https://www.nuget.org/packages/sqlite-net-sqlcipher/1.5.176-beta) and testing with the new `SetKey` methods on the connection? Thanks!

**Comment by JKennedy24** [comment]
Just a heads up when I tested the new nuget out,
I use [SQliteExtensions](https://www.nuget.org/packages/SQLiteNetExtensions/) which has a dependency on Sqlite-Net-PCL so it couldnt cope with conflicting dlls.

I therefore had to revert to the old way of doing it outlined here: https://github.com/praeclarum/sqlite-net/issues/508#issuecomment-301905452

Don't think its anything you can do in your library to fix that but its possibly worth noting

**Comment by praeclarum** [comment]
Since 1.5, the https://www.nuget.org/packages/sqlite-net-sqlcipher package is available. The API is changing a bit in 1.6.

Happy encrypting!

**Comment by nbaua** [comment]
Hi,
I am trying to use -> **sqlite-net-sqlcipher 1.6.292**
in my winforms c# application for storing some client-side sensitive information, which I do not intend to save on our server.

When I try to open my sqlite db which is encrypted (password protected)
I get following error:
SQLiteException: file is not a database

While I am able to open the same database using the **DB Browser (SQLCipher)** GUI...

> ` var databasePath = Path.Combine(Application.StartupPath, "profile.db");`
>` var options = new SQLiteConnectionString(databasePath, true, key: "pass$123@security.com");`
>` conn = new SQLiteAsyncConnection(options);`

Can you please suggest, whats best way to get through this,.?

**Comment by nbaua** [comment]
> using **SQLCipher 4 defaults**

This is an issue I assume, I used **SQLCipher 3 defaults** and the problem is solved. 
Why not support the better cipher methods as well?

**Comment by DamianSuess** [comment]
@nbaua , you can check out my test repo as it may give you some assistance. The repo demos SQLite-Net and SQLite-Net-SQLCipher features using unit tests.
https://github.com/DamianSuess/Test.SQLite.
