### ISSUE TITLE
VS 2015 Nuget package does not fully install

### ISSUE THREAD

**Issue by Sun3** [praeclarum/sqlite-net#377]
I tried to install with the Visual Studio 2015 released version the SQLite-net nugget package does not fully get installed. I can see the SQLite.cs is not there...

Any updates or workarounds?

Thanks

**Comment by thomasforth** [comment]
This happens to me too.

Manually adding the SQLite.cs and SQLiteAsync.cs files to my project worked for me. I put them in a folder called SqlLite but I doubt that matters.

**Comment by JocPelletier** [comment]
Just tested with a console app using nuget sqlite-net version 1.0.8 and it work

**Comment by charlesmilette** [comment]
Check #401

**Comment by praeclarum** [comment]
This will be fixed as a part of #401. In the mean time, please use the package `sqlite-net-pcl`.
