### ISSUE TITLE
UWP version of windows10

### ISSUE THREAD

**Issue by yuudai** [praeclarum/sqlite-net#378]
It has helped us very much in this library.
Do you have a plan that corresponds to UWP of Windows10?
Best regards

**Comment by charlesmilette** [comment]
It is supported, if you use native code for your app, but due to #401 you will need to wait for the nuget package to get a new release to use it

**Comment by praeclarum** [comment]
Please use the nuget package `sqlite-net-pcl` and everything should work for you.

**Comment by yuudai** [comment]
I succeeded using sqlite-net-pcl. 
thank you.
