### ISSUE TITLE
Getting duplicate entries in tablemappings Columns

### ISSUE THREAD

**Issue by mgwalm** [praeclarum/sqlite-net#380]
i have a very complex class strucxture. in aq derived class im newinfg a property becausde the type has changed. therefore the property has the same name.

so when the table mappings are built i get duplicate columns with the same name.

i suggest to add the following code in the3 tablemapping constructor:

```
        foreach (var p in props)
        {
            // make sure not already there, maybe an override of a base property
            if (cols.FirstOrDefault(c => c.PropertyName == p.Name) != null)   //MSI
              continue;

            var ignore = p.IsDefined(typeof (IgnoreAttribute), true);
```

**Comment by praeclarum** [comment]
This code has been recently fixed and will be in the v1.5 release. Please re-open if it doesn't work for you.

Sorry for the trouble!
