### ISSUE TITLE
EnableLoadExtension() throws EntryPointNotFoundException: sqlite3_enable_load_extension on iOS

### ISSUE THREAD

**Issue by jsiemens** [praeclarum/sqlite-net#384]
Calling db.EnableLoadExtension(1) on iOS yields exception:

System.EntryPointNotFoundException: sqlite3_enable_load_extension

I am using the ios unified dll obtained from the Xamarin Components store.

**Comment by jsiemens** [comment]
I have some follow up on this. It turns out the sqlite library that ships with iOS has extension loading disabled. To load an extension, you need to statically link it in with your iOS app (dynamic linking is forbidden by Apple for apps in the app store), and then call some native methods in sqlite to have that extension automatically loaded.

**Comment by praeclarum** [comment]
I'm investigating this with #591 

Need to check if a newer iOS allows this.
