### ISSUE TITLE
any way to Query without Mapping?

### ISSUE THREAD

**Issue by osrufung** [praeclarum/sqlite-net#390]
I don't know the Database structure in runtime, so I need a way to query the rows and cols without an existent Class Mapping. Any idea? Thanks!

**Comment by JosephMichels** [comment]
There doesn't appear to be anything built in, but I added the following function that returns the results of queries as an object array. I mainly did this for performance reasons, but it could easily be adapted for your purposes.

(Note that for my specific query, I only needed to handle the Text and Int datatypes)

In the SQLiteCommand class:

        public IEnumerable<object[]> ExecuteUntypedQuery()
        {
            if (_conn.Trace)
            {
                Debug.WriteLine("Executing Query: " + this);
            }

            var stmt = Prepare();
            var cols = SQLite3.ColumnCount(stmt);
            try
            {
                while (SQLite3.Step(stmt) == SQLite3.Result.Row)
                {
                    object[] result = new object[cols];
                    for (int i = 0; i < cols; i++)
                    {
                        var colType = SQLite3.ColumnType(stmt, i);
                        if(colType == SQLite3.ColType.Integer)
                            result[i] = SQLite3.ColumnInt(stmt,i);
                        else if(colType == SQLite3.ColType.Text)
                            result[i] = SQLite3.ColumnString(stmt,i);
                    }
                    yield return (object[])result;
                }
            }
            finally
            {
                SQLite3.Finalize(stmt);
            }
        }

And then the following function in SQLiteConnection to expose the query command:

        public List<object[]> Query(string query, params object[] args)
        {
            var cmd = CreateCommand(query, args);
            return cmd.ExecuteUntypedQuery().ToList<object[]>();
        }

**Comment by osrufung** [comment]
Thank you! I've solved the problem with a similar solution using directly the sqlite-net wrapper ;)

**Comment by UweKeim** [comment]
@osrufung Possible to share your "…similar solution…"?

Woulde be _very_ helpful to me. 👍
