### ISSUE TITLE
Retrieve custom columns name in query

### ISSUE THREAD

**Issue by luonganhtuanTMA** [praeclarum/sqlite-net#393]
Dear all,
How can I get another value from columns that not exists in the table.
EX:
string sql = "SELECT round(avg(Value)) AS Value, max(Value) AS MaxValue, min(Value) AS MinValue FROM table"
database.QueryAsync<table>(sql);

Please help!

**Comment by praeclarum** [comment]
Create a class to receive the results:

```csharp
class QueryResults {
  public double Value { get; set; }
  public double MaxValue { get; set; }
  public double MinValue { get; set; }
}
```

and then query with it:

```csharp
await database.QueryAsync<QueryResults> (sql);
```
