### ISSUE TITLE
Compact Framework 3.5 support

### ISSUE THREAD

**Issue by AndreMiras** [praeclarum/sqlite-net#397]
I haven't seen any reference to Compact Framework except in https://github.com/praeclarum/sqlite-net/pull/85#issuecomment-7898998.
What is the current policy? Are you willing to support it or not? If not, perhaps we could add a small reference stating so in the README, Wiki or FAQ.
I have ported it myself here https://github.com/AndreMiras/sqlite-net-cf and it seems to be working OK.
I couldn't run unit tests yet because it currently crashes my Visual Studio 2008 instance.
The changes mainly consist in back-porting or skipping features dropped in CF 3.5 and replacing methods default parameters by overloading.
I would understand if you were not interested in moving towards its support because it's quite old and not so much used. But if you're interested in this feature I could put more effort on it, making sure I've made no regression, documenting and also making tests run on Visual 2008.

**Comment by praeclarum** [comment]
I'm sorry, but I think I'm going to pass on this. I appreciate the scenario (I used to be a CF programmer!) but support it would require holding the language of this library back.

Thanks!

**Comment by AndreMiras** [comment]
Agree, but perhaps it's wise to at least state in the README.md or wiki, CF 3.5 is not supported and link to the ticket.
People can always use the fork if they want to.
