### ISSUE TITLE
update nuget dependencies as current one is being deprecated

### ISSUE THREAD

**Issue by tuath** [praeclarum/sqlite-net#404]
Hi Frank, 

while debugging SQLitePCL.raw for UWP, we came into a situation where UWP projects always restore dependencies. I wrote a blog on in here : http://www.modelon.net/2016/01/nuget-and-project-json/

This said, your SQLite-net-pcl has a dependency on sqlitepcl.rawbasic which is being replaced by sqlitepcl.raw which causes problems going forward

Here is the issue on the other project
https://github.com/ericsink/SQLitePCL.raw/issues/44

Any way you can push out a new version with the new nuget dependency ?

I can make a pull request but it's removing a few bytes in a file :)
Erik.

**Comment by ericsink** [comment]
Hey Frank,

After seeing this problem, I decided I'm going to continue keeping the _basic form of SQLitePCL.raw up-to-date for now, but eventually I do want to stop, so it'll be helpful if you can change your dependency from SQLitePCL.raw_basic to SQLitePCL.raw at some point.  Thanks.

**Comment by praeclarum** [comment]
I believe this has all been fixed? Please re-open if not.
