### ISSUE TITLE
Android GingerBread crash with flag fts3

### ISSUE THREAD

**Issue by lufo88** [praeclarum/sqlite-net#420]
Hi,
In Android Gingerbread (API 10) if I create a table with this syntax
db.CreateTable<Foo>(CreateFlags.FullTextSearch3);

the library (and app too) crash with this error: "Syntax error near 'not'".

It seems that Android GingerBread not support "if not exists" when creating virtual table.
A workaround is to check before the create table if the table exist, than create the table without "if Not exist".

Example:
var result = db.ExecuteScalar<int>("SELECT 1 FROM sqlite_master WHERE type='table' AND name= ?", "Foo");
if (result == 0)
 {
 db.Execute("create virtual table Foo using fts3 (Id integer  value varchar)");
 }
Can you fix the problem in the library?
P.S. Sorry for my bad english. Anyway with version 11+ of Android this problem does not exist

**Comment by lufo88** [comment]
The problem seems exist also in ICS and HoneyComb (in these versione Android do not support fts4) I can test on a similar device only in the recent day. Jelly bean 4.1.2 work for sure.

**Comment by praeclarum** [comment]
Thank you finding this problem. It must be a difference in sqlite versions.

**Comment by MKuckert** [comment]
Is support for android 2.3.3 from early 2011 really required? I mean it's 2017 now...

**Comment by praeclarum** [comment]
I think since it works on Jelly Bean, you're right it's OK to leave this error instead of working around it.

https://developer.android.com/about/dashboards/index.html puts everything lower at only 1.4% of the market.
