### ISSUE TITLE
Creating a class with implicit PK, does not create a PK

### ISSUE THREAD

**Issue by MisinformedDNA** [praeclarum/sqlite-net#421]
If I take a model with no attributes and use `CreateTable` with `CreateFlags.ImplicitPK` or `CreateFlags.AllImplicit`, the PK does not seem to actually get created.

If I inspect Table<T>.Table, there is no PK specified. In addition, if I use InsertOrReplace, it inserts duplicate rows (all fields are identical).

**Comment by bgmeiner** [comment]
My tests also show that this isn't working..

If you take the Customer test class and remove the Id property

        public class Customer
        {
            [MaxLength(64)]
            public string FirstName { get; set; }

            [MaxLength(64)]
            public string LastName { get; set; }

            [MaxLength(64)]
            public string Email { get; set; }
        }

and create a table with CreateFlags.AutoIncPK

`conn.CreateTableAsync<Customer>(CreateFlags.AutoIncPK).Wait();`

you'll see that in in SQLite.cs -> `public int CreateTable(Type ty, CreateFlags createFlags = CreateFlags.None)`

this query is produced:

> create table if not exists \"Customer\" (\n\"FirstName\" varchar(64) ,\n\"LastName\" varchar(64) ,\n\"Email\" varchar(64) )

**Comment by praeclarum** [comment]
Your `Customer` class must contain an `int` property called `Id`.

The `CreateFlags.ImplicitPK` and `AutoIncPK` simply allows you to avoid the `[PrimaryKey, AutoIncrement]` attributes.
