### ISSUE TITLE
Using ConcurrentDictionary instead of Dictionary

### ISSUE THREAD

**Issue by Coogison** [praeclarum/sqlite-net#423]
Hello,

we have discovered a problem using your code in multithreading application. 

`System.IndexOutOfRangeExceptionIndex was outside the bounds of the array.
Raw
System.Collections.Generic.Dictionary<TKey, TValue>.Insert(TKey key, TValue value, bool add)
System.Collections.Generic.Dictionary<TKey, TValue>.set_Item(TKey key, TValue value)
SQLite.SQLiteConnection.GetMapping(Type type, CreateFlags createFlags)
SQLite.SQLiteCommand.ExecuteQuery<T>()
SQLite.TableQuery<T>.GetEnumerator()
System.Collections.Generic.List<T>.List(IEnumerable<_> collection)
System.Linq.Enumerable.ToList<TSource>(IEnumerable<_> source)
VykazPrace.Core.BusinessLayer.DbSet<T>.Query(Expression<_> wherePred)`

And we think that it is connected to the usage of classic Dictionaries which are not thread safe instead of ConcurrentDictionaries. 

Do you think it might be connected or is this completely irrelevant?

**Comment by schuettecarsten** [comment]
Same problem here.

**Comment by praeclarum** [comment]
Working on this now!

**Comment by timvandenhof** [comment]
@praeclarum this issue appears to be fixed in the 1.5.166-beta NuGet package. Is there a plan to release a non-prerelease package containing this fix anytime soon?
