### ISSUE TITLE
SQLite3 not provided on Android N

### ISSUE THREAD

**Issue by decriptor** [praeclarum/sqlite-net#427]
https://developer.xamarin.com/releases/android/xamarin.android_6/xamarin.android_6.1/#mono-data-sqlite

**Comment by markjulmar** [comment]
Eric Sink also noted this: https://github.com/ericsink/SQLitePCL.raw/wiki/SQLite-net-and-Android-N

**Comment by MKuckert** [comment]
As far as I can see Frank switched to bundle_green which include binaries for Android N:
https://github.com/praeclarum/sqlite-net/commit/3efe1d547c966279899b215450992d80dbd35d56

**Comment by ericsink** [comment]
Yes.  SQLitePCL.bundle_green is a meta package which brings in the necessary part of SQLitePCL.raw and initializes things.  It was created specifically for sqlite-net-pcl to provide a "batteries included" experience.

**Comment by MKuckert** [comment]
Great. So I think, this issue can be closed, right?

**Comment by MKuckert** [comment]
Who is currently maintaining this project? Seems like this issue may simply be closed by anybody...

**Comment by ericsink** [comment]
I don't appear to have permission to close this. 

I am only the maintainer of SQLitePCL.raw, which is a lower level dependency of the PCL version of this project.

**Comment by praeclarum** [comment]
Yay for Bundle Green!
