### ISSUE TITLE
Compilation Error CS1704

### ISSUE THREAD

**Issue by neurospeech** [praeclarum/sqlite-net#430]
I am getting this error 

```
1>CSC : error CS1704: An assembly with the same simple name 'SQLitePCL.raw' has already been imported. Try removing one of the references (e.g. 'projectname\packages\SQLitePCL.raw.0.9.2\lib\MonoAndroid\SQLitePCL.raw.dll') or sign them to enable side-by-side.
```

Your package has dependency of SQLite.raw (0.9.2), but SQLite.raw package has version SQLite.raw 0.8.5. I think you have included SQLite.raw inside your package as well as you are having dependency on SQLite.raw.

For iOS this works without any error.

**Comment by praeclarum** [comment]
The packages have been updated! Thanks for filing this.
