### ISSUE TITLE
[Proposal] Implement DeleteAsync<T>(Expression<Func<T,bool>> predicate)

### ISSUE THREAD

**Issue by neurospeech** [praeclarum/sqlite-net#433]
Let's say I am using Sqlite to cache items from web service and that as expiration date, I would like to run one simple statement saying
`DELETE FROM CachedItems WHERE Expiration < @now`

Each CachedItem is heavy, I don't see any need to reload it into memory and then delete them one by one.

I know I can use ExecuteAsync, but it does not have Linq support.

**Comment by MKuckert** [comment]
You should be able to do something like
```
var now = DateTime.Now;
connection.Table<CachedItems>().Delete(item => item.Expiration < now);
```

**Comment by abdul-qadirdeveloper** [comment]
Implementation should better be like this
Task<int> DeleteAsync<T>(Expression<Func<T,bool>> predicate)

where return int should show the number of records affected/Deleted.

**Comment by praeclarum** [comment]
I'm looking into this now!

**Comment by praeclarum** [comment]
It's been added! https://github.com/praeclarum/sqlite-net/commit/0735ca45b5336b184a3182cfc8ad0e27362d3668#diff-2388537c7df63c2e1c2c63b815f301b4R1254
