### ISSUE TITLE
Windows App Certification (UWP 8.1) Fails

### ISSUE THREAD

**Issue by belovmal** [praeclarum/sqlite-net#434]
Windows App Certification of UWP 8.1 for Windows 8.1 and Windows Phone 8.1 (I am using Visual Studio 2015 Update 3 now) fails after upgrade to sqlite-net-pcl 1.1.2 (with SQLitePCL.raw 0.8.6)  from sqlite-net-pcl 1.1.1 (with SQLitePCL.raw 0.8.6)  with error:

Supported API test
FAILED

Supported APIs
•Error Found: The supported APIs test detected the following errors:

◦This API is not supported for this application type - Api=sqlite3_aggregate_context. Module=sqlite3.dll. File=SQLitePCL.raw.dll.
◦This API is not supported for this application type - Api=sqlite3_aggregate_count. Module=sqlite3.dll. File=SQLitePCL.raw.dll.
◦This API is not supported for this application type - Api=sqlite3_backup_finish. Module=sqlite3.dll. File=SQLitePCL.raw.dll.
◦This API is not supported for this application type - Api=sqlite3_backup_init. Module=sqlite3.dll. File=SQLitePCL.raw.dll.
◦This API is not supported for this application type - Api=sqlite3_backup_pagecount. Module=sqlite3.dll. File=SQLitePCL.raw.dll.
◦This API is not supported for this application type - Api=sqlite3_backup_remaining. Module=sqlite3.dll. File=SQLitePCL.raw.dll.
◦This API is not supported for this application type - Api=sqlite3_backup_step. Module=sqlite3.dll. File=SQLitePCL.raw.dll.
◦This API is not supported for this application type - Api=sqlite3_bind_blob. Module=sqlite3.dll. File=SQLitePCL.raw.dll.
◦This API is not supported for this application type - Api=sqlite3_bind_double. Module=sqlite3.dll. File=SQLitePCL.raw.dll.
◦This API is not supported for this application type - Api=sqlite3_bind_int. Module=sqlite3.dll. File=SQLitePCL.raw.dll.
◦This API is not supported for this application type - Api=sqlite3_bind_int64. Module=sqlite3.dll. File=SQLitePCL.raw.dll.
◦This API is not supported for this application type - Api=sqlite3_bind_null. Module=sqlite3.dll. File=SQLitePCL.raw.dll.
◦This API is not supported for this application type - Api=sqlite3_bind_parameter_count. Module=sqlite3.dll. File=SQLitePCL.raw.dll.
◦This API is not supported for this application type - Api=sqlite3_bind_parameter_index. Module=sqlite3.dll. File=SQLitePCL.raw.dll.
◦This API is not supported for this application type - Api=sqlite3_bind_parameter_name. Module=sqlite3.dll. File=SQLitePCL.raw.dll.
◦This API is not supported for this application type - Api=sqlite3_bind_text. Module=sqlite3.dll. File=SQLitePCL.raw.dll.
◦This API is not supported for this application type - Api=sqlite3_bind_text16. Module=sqlite3.dll. File=SQLitePCL.raw.dll.
◦This API is not supported for this application type - Api=sqlite3_bind_zeroblob. Module=sqlite3.dll. File=SQLitePCL.raw.dll.
◦This API is not supported for this application type - Api=sqlite3_blob_bytes. Module=sqlite3.dll. File=SQLitePCL.raw.dll.
◦This API is not supported for this application type - Api=sqlite3_blob_close. Module=sqlite3.dll. File=SQLitePCL.raw.dll.
◦This API is not supported for this application type - Api=sqlite3_blob_open. Module=sqlite3.dll. File=SQLitePCL.raw.dll.
◦This API is not supported for this application type - Api=sqlite3_blob_read. Module=sqlite3.dll. File=SQLitePCL.raw.dll.
◦This API is not supported for this application type - Api=sqlite3_blob_write. Module=sqlite3.dll. File=SQLitePCL.raw.dll.
◦This API is not supported for this application type - Api=sqlite3_busy_timeout. Module=sqlite3.dll. File=SQLitePCL.raw.dll.
◦This API is not supported for this application type - Api=sqlite3_changes. Module=sqlite3.dll. File=SQLitePCL.raw.dll.
◦This API is not supported for this application type - Api=sqlite3_clear_bindings. Module=sqlite3.dll. File=SQLitePCL.raw.dll.
◦This API is not supported for this application type - Api=sqlite3_close. Module=sqlite3.dll. File=SQLitePCL.raw.dll.
◦This API is not supported for this application type - Api=sqlite3_close_v2. Module=sqlite3.dll. File=SQLitePCL.raw.dll.
◦This API is not supported for this application type - Api=sqlite3_column_blob. Module=sqlite3.dll. File=SQLitePCL.raw.dll.
◦This API is not supported for this application type - Api=sqlite3_column_bytes. Module=sqlite3.dll. File=SQLitePCL.raw.dll.
◦This API is not supported for this application type - Api=sqlite3_column_count. Module=sqlite3.dll. File=SQLitePCL.raw.dll.
◦This API is not supported for this application type - Api=sqlite3_column_database_name. Module=sqlite3.dll. File=SQLitePCL.raw.dll.
◦This API is not supported for this application type - Api=sqlite3_column_database_name16. Module=sqlite3.dll. File=SQLitePCL.raw.dll.
◦This API is not supported for this application type - Api=sqlite3_column_decltype. Module=sqlite3.dll. File=SQLitePCL.raw.dll.
◦This API is not supported for this application type - Api=sqlite3_column_decltype16. Module=sqlite3.dll. File=SQLitePCL.raw.dll.
◦This API is not supported for this application type - Api=sqlite3_column_double. Module=sqlite3.dll. File=SQLitePCL.raw.dll.
◦This API is not supported for this application type - Api=sqlite3_column_int. Module=sqlite3.dll. File=SQLitePCL.raw.dll.
◦This API is not supported for this application type - Api=sqlite3_column_int64. Module=sqlite3.dll. File=SQLitePCL.raw.dll.
◦This API is not supported for this application type - Api=sqlite3_column_name. Module=sqlite3.dll. File=SQLitePCL.raw.dll.
◦This API is not supported for this application type - Api=sqlite3_column_name16. Module=sqlite3.dll. File=SQLitePCL.raw.dll.
◦This API is not supported for this application type - Api=sqlite3_column_origin_name. Module=sqlite3.dll. File=SQLitePCL.raw.dll.
◦This API is not supported for this application type - Api=sqlite3_column_origin_name16. Module=sqlite3.dll. File=SQLitePCL.raw.dll.
◦This API is not supported for this application type - Api=sqlite3_column_table_name. Module=sqlite3.dll. File=SQLitePCL.raw.dll.
◦This API is not supported for this application type - Api=sqlite3_column_table_name16. Module=sqlite3.dll. File=SQLitePCL.raw.dll.
◦This API is not supported for this application type - Api=sqlite3_column_text. Module=sqlite3.dll. File=SQLitePCL.raw.dll.
◦This API is not supported for this application type - Api=sqlite3_column_text16. Module=sqlite3.dll. File=SQLitePCL.raw.dll.
◦This API is not supported for this application type - Api=sqlite3_column_type. Module=sqlite3.dll. File=SQLitePCL.raw.dll.
◦This API is not supported for this application type - Api=sqlite3_commit_hook. Module=sqlite3.dll. File=SQLitePCL.raw.dll.
◦This API is not supported for this application type - Api=sqlite3_compileoption_get. Module=sqlite3.dll. File=SQLitePCL.raw.dll.
◦This API is not supported for this application type - Api=sqlite3_compileoption_used. Module=sqlite3.dll. File=SQLitePCL.raw.dll.
◦This API is not supported for this application type - Api=sqlite3_complete. Module=sqlite3.dll. File=SQLitePCL.raw.dll.
◦This API is not supported for this application type - Api=sqlite3_config. Module=sqlite3.dll. File=SQLitePCL.raw.dll.
◦This API is not supported for this application type - Api=sqlite3_create_collation. Module=sqlite3.dll. File=SQLitePCL.raw.dll.
◦This API is not supported for this application type - Api=sqlite3_create_function_v2. Module=sqlite3.dll. File=SQLitePCL.raw.dll.
◦This API is not supported for this application type - Api=sqlite3_data_count. Module=sqlite3.dll. File=SQLitePCL.raw.dll.
◦This API is not supported for this application type - Api=sqlite3_db_filename. Module=sqlite3.dll. File=SQLitePCL.raw.dll.
◦This API is not supported for this application type - Api=sqlite3_db_handle. Module=sqlite3.dll. File=SQLitePCL.raw.dll.
◦This API is not supported for this application type - Api=sqlite3_db_readonly. Module=sqlite3.dll. File=SQLitePCL.raw.dll.
◦This API is not supported for this application type - Api=sqlite3_db_status. Module=sqlite3.dll. File=SQLitePCL.raw.dll.
◦This API is not supported for this application type - Api=sqlite3_enable_load_extension. Module=sqlite3.dll. File=SQLitePCL.raw.dll.
◦This API is not supported for this application type - Api=sqlite3_enable_shared_cache. Module=sqlite3.dll. File=SQLitePCL.raw.dll.
◦This API is not supported for this application type - Api=sqlite3_errcode. Module=sqlite3.dll. File=SQLitePCL.raw.dll.
◦This API is not supported for this application type - Api=sqlite3_errmsg. Module=sqlite3.dll. File=SQLitePCL.raw.dll.
◦This API is not supported for this application type - Api=sqlite3_errstr. Module=sqlite3.dll. File=SQLitePCL.raw.dll.
◦This API is not supported for this application type - Api=sqlite3_exec. Module=sqlite3.dll. File=SQLitePCL.raw.dll.
◦This API is not supported for this application type - Api=sqlite3_extended_errcode. Module=sqlite3.dll. File=SQLitePCL.raw.dll.
◦This API is not supported for this application type - Api=sqlite3_extended_result_codes. Module=sqlite3.dll. File=SQLitePCL.raw.dll.
◦This API is not supported for this application type - Api=sqlite3_file_control. Module=sqlite3.dll. File=SQLitePCL.raw.dll.
◦This API is not supported for this application type - Api=sqlite3_finalize. Module=sqlite3.dll. File=SQLitePCL.raw.dll.
◦This API is not supported for this application type - Api=sqlite3_free. Module=sqlite3.dll. File=SQLitePCL.raw.dll.
◦This API is not supported for this application type - Api=sqlite3_get_autocommit. Module=sqlite3.dll. File=SQLitePCL.raw.dll.
◦This API is not supported for this application type - Api=sqlite3_interrupt. Module=sqlite3.dll. File=SQLitePCL.raw.dll.
◦This API is not supported for this application type - Api=sqlite3_last_insert_rowid. Module=sqlite3.dll. File=SQLitePCL.raw.dll.
◦This API is not supported for this application type - Api=sqlite3_libversion. Module=sqlite3.dll. File=SQLitePCL.raw.dll.
◦This API is not supported for this application type - Api=sqlite3_libversion_number. Module=sqlite3.dll. File=SQLitePCL.raw.dll.
◦This API is not supported for this application type - Api=sqlite3_load_extension. Module=sqlite3.dll. File=SQLitePCL.raw.dll.
◦This API is not supported for this application type - Api=sqlite3_log. Module=sqlite3.dll. File=SQLitePCL.raw.dll.
◦This API is not supported for this application type - Api=sqlite3_malloc. Module=sqlite3.dll. File=SQLitePCL.raw.dll.
◦This API is not supported for this application type - Api=sqlite3_memory_highwater. Module=sqlite3.dll. File=SQLitePCL.raw.dll.
◦This API is not supported for this application type - Api=sqlite3_memory_used. Module=sqlite3.dll. File=SQLitePCL.raw.dll.
◦This API is not supported for this application type - Api=sqlite3_next_stmt. Module=sqlite3.dll. File=SQLitePCL.raw.dll.
◦This API is not supported for this application type - Api=sqlite3_open. Module=sqlite3.dll. File=SQLitePCL.raw.dll.
◦This API is not supported for this application type - Api=sqlite3_open16. Module=sqlite3.dll. File=SQLitePCL.raw.dll.
◦This API is not supported for this application type - Api=sqlite3_open_v2. Module=sqlite3.dll. File=SQLitePCL.raw.dll.
◦This API is not supported for this application type - Api=sqlite3_prepare. Module=sqlite3.dll. File=SQLitePCL.raw.dll.
◦This API is not supported for this application type - Api=sqlite3_prepare_v2. Module=sqlite3.dll. File=SQLitePCL.raw.dll.
◦This API is not supported for this application type - Api=sqlite3_profile. Module=sqlite3.dll. File=SQLitePCL.raw.dll.
◦This API is not supported for this application type - Api=sqlite3_progress_handler. Module=sqlite3.dll. File=SQLitePCL.raw.dll.
◦This API is not supported for this application type - Api=sqlite3_realloc. Module=sqlite3.dll. File=SQLitePCL.raw.dll.
◦This API is not supported for this application type - Api=sqlite3_reset. Module=sqlite3.dll. File=SQLitePCL.raw.dll.
◦This API is not supported for this application type - Api=sqlite3_result_blob. Module=sqlite3.dll. File=SQLitePCL.raw.dll.
◦This API is not supported for this application type - Api=sqlite3_result_double. Module=sqlite3.dll. File=SQLitePCL.raw.dll.
◦This API is not supported for this application type - Api=sqlite3_result_error. Module=sqlite3.dll. File=SQLitePCL.raw.dll.
◦This API is not supported for this application type - Api=sqlite3_result_error16. Module=sqlite3.dll. File=SQLitePCL.raw.dll.
◦This API is not supported for this application type - Api=sqlite3_result_error_code. Module=sqlite3.dll. File=SQLitePCL.raw.dll.
◦This API is not supported for this application type - Api=sqlite3_result_error_nomem. Module=sqlite3.dll. File=SQLitePCL.raw.dll.
◦This API is not supported for this application type - Api=sqlite3_result_error_toobig. Module=sqlite3.dll. File=SQLitePCL.raw.dll.
◦This API is not supported for this application type - Api=sqlite3_result_int. Module=sqlite3.dll. File=SQLitePCL.raw.dll.
◦This API is not supported for this application type - Api=sqlite3_result_int64. Module=sqlite3.dll. File=SQLitePCL.raw.dll.
◦This API is not supported for this application type - Api=sqlite3_result_null. Module=sqlite3.dll. File=SQLitePCL.raw.dll.
◦This API is not supported for this application type - Api=sqlite3_result_text. Module=sqlite3.dll. File=SQLitePCL.raw.dll.
◦This API is not supported for this application type - Api=sqlite3_result_text16. Module=sqlite3.dll. File=SQLitePCL.raw.dll.
◦This API is not supported for this application type - Api=sqlite3_result_zeroblob. Module=sqlite3.dll. File=SQLitePCL.raw.dll.
◦This API is not supported for this application type - Api=sqlite3_rollback_hook. Module=sqlite3.dll. File=SQLitePCL.raw.dll.
◦This API is not supported for this application type - Api=sqlite3_set_authorizer. Module=sqlite3.dll. File=SQLitePCL.raw.dll.
◦This API is not supported for this application type - Api=sqlite3_shutdown. Module=sqlite3.dll. File=SQLitePCL.raw.dll.
◦This API is not supported for this application type - Api=sqlite3_sourceid. Module=sqlite3.dll. File=SQLitePCL.raw.dll.
◦This API is not supported for this application type - Api=sqlite3_sql. Module=sqlite3.dll. File=SQLitePCL.raw.dll.
◦This API is not supported for this application type - Api=sqlite3_status. Module=sqlite3.dll. File=SQLitePCL.raw.dll.
◦This API is not supported for this application type - Api=sqlite3_step. Module=sqlite3.dll. File=SQLitePCL.raw.dll.
◦This API is not supported for this application type - Api=sqlite3_stmt_busy. Module=sqlite3.dll. File=SQLitePCL.raw.dll.
◦This API is not supported for this application type - Api=sqlite3_stmt_readonly. Module=sqlite3.dll. File=SQLitePCL.raw.dll.
◦This API is not supported for this application type - Api=sqlite3_stmt_status. Module=sqlite3.dll. File=SQLitePCL.raw.dll.
◦This API is not supported for this application type - Api=sqlite3_table_column_metadata. Module=sqlite3.dll. File=SQLitePCL.raw.dll.
◦This API is not supported for this application type - Api=sqlite3_total_changes. Module=sqlite3.dll. File=SQLitePCL.raw.dll.
◦This API is not supported for this application type - Api=sqlite3_trace. Module=sqlite3.dll. File=SQLitePCL.raw.dll.
◦This API is not supported for this application type - Api=sqlite3_update_hook. Module=sqlite3.dll. File=SQLitePCL.raw.dll.
◦This API is not supported for this application type - Api=sqlite3_user_data. Module=sqlite3.dll. File=SQLitePCL.raw.dll.
◦This API is not supported for this application type - Api=sqlite3_value_blob. Module=sqlite3.dll. File=SQLitePCL.raw.dll.
◦This API is not supported for this application type - Api=sqlite3_value_bytes. Module=sqlite3.dll. File=SQLitePCL.raw.dll.
◦This API is not supported for this application type - Api=sqlite3_value_double. Module=sqlite3.dll. File=SQLitePCL.raw.dll.
◦This API is not supported for this application type - Api=sqlite3_value_int. Module=sqlite3.dll. File=SQLitePCL.raw.dll.
◦This API is not supported for this application type - Api=sqlite3_value_int64. Module=sqlite3.dll. File=SQLitePCL.raw.dll.
◦This API is not supported for this application type - Api=sqlite3_value_text. Module=sqlite3.dll. File=SQLitePCL.raw.dll.
◦This API is not supported for this application type - Api=sqlite3_value_text16. Module=sqlite3.dll. File=SQLitePCL.raw.dll.
◦This API is not supported for this application type - Api=sqlite3_value_type. Module=sqlite3.dll. File=SQLitePCL.raw.dll.
◦This API is not supported for this application type - Api=sqlite3_vfs_find. Module=sqlite3.dll. File=SQLitePCL.raw.dll.
◦This API is not supported for this application type - Api=sqlite3_wal_autocheckpoint. Module=sqlite3.dll. File=SQLitePCL.raw.dll.
◦This API is not supported for this application type - Api=sqlite3_wal_checkpoint. Module=sqlite3.dll. File=SQLitePCL.raw.dll.
◦This API is not supported for this application type - Api=sqlite3_wal_checkpoint_v2. Module=sqlite3.dll. File=SQLitePCL.raw.dll.
◦This API is not supported for this application type - Api=sqlite3_win32_set_directory. Module=sqlite3.dll. File=SQLitePCL.raw.dll.

With additional information:
•Impact if not fixed:  Using an API that is not part of the Windows SDK for Windows Phone Store apps violates the Windows Phone Store certification requirements. 

•How to fix:  Review the error messages to identify the API that is not part of the Windows SDK for Windows Phone Store app. Please note, C++ apps that are built in a debug configuration will fail this test even if they only use APIs from the Windows SDK for Windows Phone Store apps. 

Thanks in advance for any help!

**Comment by ericsink** [comment]
Do I understand you correctly that you were previously on sqlite-net-pcl 1.1.1 (with SQLitePCL.raw 0.8.6) and it was working fine, but you have upgraded to sqlite-net-pcl 1.1.2 (with SQLitePCL.raw 0.9.2) and now it fails?

**Comment by belovmal** [comment]
Eric, yes! I've made update for my existing UWP 8.1 app in store (now it's working with 0.86 version), via Nuget, it's working fine. But before submitting the new version, I've run Windows App Certification Kit - STATUS Failed with error above.

**Comment by ericsink** [comment]
Okay. That probably means I messed up something in 0.9.x for UWP 8.1.  I'll look into it.

**Comment by belovmal** [comment]
Eric, thank you very much! And one more small new issue, after upgrade from 1.1.1 and 0.86 with Microsoft.VCLibs, for Metro one all is ok, for WP 8.1 it becomes with exclamation. I've fixed it by removing and adding Microsoft Visual C++ 2013 Runtime Package... once more, and than it's displayed as Microsoft Visual C++ 2013 Runtime Package for Windows Phone instead of Microsoft.VCLibs... Maybe it's not an issue. 

However, it's seems to me, than with new 0.92 version my app works faster on low end phones.
Eric, the Greatest thanks for supporting and improving sqlite!

**Comment by ericsink** [comment]
Very good. To be fair, I should clarify that I will be traveling for the next two weeks so there will be no progress on this issue until I return.

**Comment by belovmal** [comment]
Ok! Thanks! Have a good vacation! I will do the same ) Now 0.86 version works as a charm!

**Comment by ericsink** [comment]
Working on this.  Current status is stuck with Visual Studio crashing whenever I try to build the store package, which I've never actually done before.

To clarify, this problem happens after you build a store package containing both the desktop and phone versions of your Windows 8.1 universal app, right?

**Comment by ericsink** [comment]
Never mind.  I got past that, and reproduced the error you are seeing, and I think I know what's going on.

**Comment by ericsink** [comment]
The cert kit is actually griping because SQLitePCL.raw contains some DllImport attributes for symbols that are not part of the package.

The error message is somewhere between "confusing" and "wrong".

Also, I would like to claim that the error shouldn't be happening at all, since those pinvoke calls never actually get executed.  In fact, it is interesting to note that when testing the same code in a UWP app (10, not 8.1), the error does not happen.

That said, I am looking into ways to deal with this.  I'll probably need to remove those built-in pinvoke sets for UWP platforms.

**Comment by belovmal** [comment]
Eric, thanks! I build desktop version and phone version separately in borders of UWP 8.1 project (you can check 'Dictutor' project in the store. With the latest version of your library all is OK and work as a charm except certification issue.

**Comment by FANMixco** [comment]
The problem stills exists :\

Error Found: The supported APIs test detected the following errors:
API sqlite3_bind_blob in sqlite3.dll is not supported for this application type. Típicos Salvadoreños W10.exe calls this API.
API sqlite3_bind_double in sqlite3.dll is not supported for this application type. Típicos Salvadoreños W10.exe calls this API.
API sqlite3_bind_int in sqlite3.dll is not supported for this application type. Típicos Salvadoreños W10.exe calls this API.
API sqlite3_bind_int64 in sqlite3.dll is not supported for this application type. Típicos Salvadoreños W10.exe calls this API.
API sqlite3_bind_null in sqlite3.dll is not supported for this application type. Típicos Salvadoreños W10.exe calls this API.

Thanks for your help!

**Comment by tkohub** [comment]
I am facing the same issue with UWP 10 app using https://github.com/ericsink/SQLitePCL.raw 1.1.2

The local certification kit runs fine but after upload i am getting the errors from the original post during certification.

**Comment by chkrishna2001** [comment]
I am having same errors in windows phone 8.1 ? could someone help me fix it please

**Comment by praeclarum** [comment]
@ericsink Have any improvements been made here?

**Comment by ericsink** [comment]
The Win10 issue mentioned above turned out to be nothing.  The original Win81 issue was fixed.  I've seen a couple of followsup (above, even) from people still having trouble, but if in fact there are any remaining problems, I haven't got a good description of what the difficulty is.

**Comment by praeclarum** [comment]
Glad it's over. Thanks for working through it all!

**Comment by artemious7** [comment]
The same has just happened to me after upgrading the package in my Win10 UWP project from v0.8.5 to v0.9.3 (the latest one). The Windows App Cert Kit (for Windows 10.0.15063.0 Version 1703) successfully passes the Supported API tests, while after submitting to the Store, the Store certification fails with the same error message.
