### ISSUE TITLE
SQLiteConnection.Query fails if more than one ? parameter place holder.

### ISSUE THREAD

**Issue by nickgdyer** [praeclarum/sqlite-net#440]
I posted this[ here on StackOverflow](http://stackoverflow.com/questions/38723162/c-sharp-xamarin-android-sqlite-pcl-database-query-returns-no-results) but got no answers so trying here to see if anybody knows what's wrong.

The following c# returns no records:

```
string strSQL = "SELECT encounters.rotation as EncounterID, encounters.encounterdatetime as ApptTime, patients.surname || ', ' || patients.title || ' ' || patients.forename AS PatientName ";
            strSQL += "FROM encounters INNER JOIN patients ON encounters.patientid = patients.rotation LEFT OUTER JOIN consultlinkage on encounters.rotation = consultlinkage.encounterid ";
            strSQL += "WHERE encounters.userid=? AND consultlinkage.encounterid IS NULL AND strftime('%Y-%m-%d',encounters.encounterdatetime) = '?' ORDER BY encounters.encounterdatetime";
            var results= database.Query<EncounterList>(strSQL, uid, ApptDate);

            return results;
```
While the following will:

```
string strSQL = "SELECT encounters.rotation as EncounterID, encounters.encounterdatetime as ApptTime, patients.surname || ', ' || patients.title || ' ' || patients.forename AS PatientName ";
            strSQL += "FROM encounters INNER JOIN patients ON encounters.patientid = patients.rotation LEFT OUTER JOIN consultlinkage on encounters.rotation = consultlinkage.encounterid ";
            strSQL += string.Format("WHERE encounters.userid={0} AND consultlinkage.encounterid IS NULL AND strftime('%Y-%m-%d',encounters.encounterdatetime) = '{1}' ORDER BY encounters.encounterdatetime", uid, ApptDate);
            var results= database.Query<EncounterList>(strSQL);

            return results;
```
It would appear that having more than one parameter placeholder ? (Question Mark) doesn't seem to work. It does work if your query only has one parameter placeholder. This is using sql-net-pcl version 1.1.2.

**Comment by MKuckert** [comment]
How are you executing this query? You have to bind all placeholders!

**Comment by nickgdyer** [comment]
Sorry but not sure what you mean. The parameters are a "long" and a "string" that when you see used with string.format work fine but when used with ? placeholders do not. What do you mean by bind?

**Comment by nickgdyer** [comment]
You can close this issue. I finally worked out what was wrong. I had misunderstood how the binding of parameters worked. [http://stackoverflow.com/a/39015965/4873992](http://stackoverflow.com/a/39015965/4873992)
