### ISSUE TITLE
System.Exception: Something went wrong in the build configuration.  This is the bait assembly, which is for referencing by portable libraries, and should never end up part of the app.  Reference the appropriate platform assembly instead.

### ISSUE THREAD

**Issue by chenjiancan** [praeclarum/sqlite-net#441]
Package version: 1.1.0.0
Solution: Xamarin project with Portable Library
Project: Xamarin.Android 
The app builded and run in Android, the Exception occur when The Database construct execute "base(path)"
```
public class Database<T> : SQLiteConnection where T : DB.BusinessLayer.Contracts.IBusinessEntity, new()
    {
        static object locker = new object();

        // path: Database file name
        public Database(string path) : base(path)
        {
            CreateTable<T>();
        }
......
}
```

> System.Exception: Something went wrong in the build configuration.  This is the bait assembly, which is for referencing by portable libraries, and should never end up part of the app.  Reference the appropriate platform assembly instead.

**Comment by ericsink** [comment]
Add a reference to SQLite-net-pcl to your android project as well, not just to the portable library project.

**Comment by chenjiancan** [comment]
@ericsink I think did add the reference to android project as well, but the exception threw still.
I check the sample code on https://github.com/xamarin/mobile-samples/tree/master/TaskyPortable by Xamarin and found that it reference rather "SQLitePCL.raw" but "SQLitePCL.raw_basic" and targetFramework is MonoAndroid51 compare to my MonoAndroid60.

I've put my Solution on https://github.com/chenjiancan/xamarin_pcl_sample .

**Comment by chenjiancan** [comment]
And I try move my code into The TaskyPortable solution, it works.

**Comment by chenjiancan** [comment]
Finally it works. 
for portable library, it refer these package:
![image](https://cloud.githubusercontent.com/assets/8361107/17545858/a8d720ac-5f11-11e6-9680-d6d09573df1e.png)

for android project, it refer these package
![image](https://cloud.githubusercontent.com/assets/8361107/17545939/39cc3cd2-5f12-11e6-923a-a6d9da004c09.png)
