### ISSUE TITLE
Nuget Package can't find dll in WinRT Component(C#) referenced by UWP(JS) project.

### ISSUE THREAD

**Issue by elvisxia** [praeclarum/sqlite-net#442]
Hi,
I created a UWP Project based on javascript and added a windows runtime component of C#.
In the Component I added SQLite.Net-PCL nuget package and use it.
In UWP main project, I call the component function. And the FileNotFound exception was thrown.
Same problem here: [SO Case](http://stackoverflow.com/questions/38986604/windows-10-slite-not-working).

Currently the workaround is to add the dlls manually.
But still curious to know the root cause of this :)

**Comment by praeclarum** [comment]
Sorry I don't control the `SQLite.Net-PCL` package. This code is released as `sqlite-net-pcl`
