### ISSUE TITLE
Unable to reference it on a Xamarin Droid project using 'Xamarin.Android.Support.v4 23.4.0.1'

### ISSUE THREAD

**Issue by gugavaro** [praeclarum/sqlite-net#443]
I am trying to reference this package on my Xamarin Android project, but I am getting the follow version error.

Is there a reason this package does not work with the v4.23.4.0.1 version of the Xamarin.Android.Support ? it seems that if i downgrade my package to use the 23.3.0 then i can install this package with no problems.

Unable to resolve dependencies. 'Xamarin.Android.Support.v4 23.4.0.1' is not compatible with 'Xamarin.Android.Support.Design 23.4.0.1 constraint: Xamarin.Android.Support.v4 (= 23.4.0.1)', 'Xamarin.Forms 2.3.1.114 constraint: Xamarin.Android.Support.v4 (= 23.3.0)'.
 
Any idea when this package will be update to support the most update version ?

thanks,
Gustavo.

**Comment by brminnick** [comment]
@gugavaro Xamarin.Forms doesn't yet support Xamarin.Android.Support.v4 v23.4.0.1

As of today, the dependancy of the Xamarin.Forms NuGet package is Xamarin.Android.Support.v4 v23.3.0

Source: https://www.nuget.org/packages/Xamarin.Forms/

<img width="493" alt="screen shot 2016-09-08 at 9 55 56 pm" src="https://cloud.githubusercontent.com/assets/13558917/18352008/256b00b6-760f-11e6-8df0-172727f30917.png">

**Comment by gugavaro** [comment]
@brminnick thanks for your message. I understand today the supported version is 23.3.0, but that was not really my question. Let me clarify:

The issue I opened is that I believe we should be able to support it on the 23.4.0.1 version of Xamarin.Android.
Couple of questions:
1- Is there a reason why it is not supported ? Could we recompile and make it available for 23.4.0.1? or actually there is a bigger issue in order to support the 23.4.0.1 version ?
2- When this package will be update to support the 23.4.0.1 version ?

thanks again,
Gustavo.

**Comment by jamesmontemagno** [comment]
This package does not have a dependency on Xamarin.Android.Support.v4 at all, nor does SQLite.raw which this package uses.

Xamarin.Forms updates the support packages regularly after rounds of testing to ensure there are no regressions. This is a topic for the forums: http://forums.xamarin.com, not this github page and it should be closed.

If you really need to compile against those support libraries you could always build Xamarin.Forms from source.

**Comment by gugavaro** [comment]
Hi @jamesmontemagno, thanks for your message. I am really sorry, I think I did a bad job when I wrote title. 
While I am using it in a Xamarin Forms, the issue is actually to reference it on my Droid project. I have no issue referencing it on the Forms project itself, so once again apologise on my bad description.
I have updated the title.
You can reference this project if your droid project is using the Xamarin.Android.Support.v4 v23.3.0 package. once you upgrade your droid project to use the Xamarin.Android.Support.v4 v23.4.0.1 package, you cant reference the sqllite anymore on the project.
try it yourself and you will see.

thanks again,
Gustavo.

**Comment by jamesmontemagno** [comment]
There is no package in Sqlite-net that references support libraries, it has no dependencies, so it most likely isn't the library. 

I am not sure what "project" you are trying to add to your xamarin android project at all. I recommend adding a sample in the issue here.

**Comment by gugavaro** [comment]
@jamesmontemagno I agree with you, what you are saying makes sense. 
Unfortunately this issue was happening with a customer back in the beginning of August and I don't have access to their project code now, at that time they just decided to keep the v23.3.0 to unblock them.
I will close the issue for now and if I heard back from them I will re-open it.
Thanks a lot for all the help.
Gustavo.
