### ISSUE TITLE
Loading SQLite Database From File?

### ISSUE THREAD

**Issue by JamesTheHacker** [praeclarum/sqlite-net#451]
Is it possible to load an SQLite database file? Can't see anything in the docs that shows how to do this. The wiki is sparse to say the least.

**Comment by jamesmontemagno** [comment]
When you create the SQLiteConnection  you can pass it the location of a database, ideally you would probably copy that database to disk somewhere or on Android have it in the Assets folder.

**Comment by JamesTheHacker** [comment]
Is there any example on how to do this? I copy the initial database when the application, but I'm not sure on how to actually load it with sqlite-net.

**Comment by eloekset** [comment]
@JamesTheHacker are you using an ActionOpenDocument Intent to select the database file? I'm trying to do that, but so far I haven't found a way to get from the document URI to an actual file that sqlite-net-pcl is able to open.

```
if (requestCode == ReadRequestCode && resultCode == Result.Ok)
{
    // User selected file using ActionOpenDocument
    Android.Net.Uri uri = data.Data;
    var storage = Android.OS.Environment.ExternalStorageDirectory;
    var path = System.IO.Path.Combine(storage.Path, uri.LastPathSegment.Replace("primary:", "/"));
    _fileService.PathToFile = path;
}
else if (requestCode == FileSelectCode && resultCode == Result.Ok)
{
    // User selected file using ActionGetContent
    var fileUri = data.ToUri(IntentUriType.None);
    
    Java.IO.File file = new Java.IO.File(fileUri);
    if (file.Exists())  // Always returns false. ActionGetContent obviously doesn't return an actual file
    {
        _fileService.PathToFile = file.AbsolutePath;
    }
}
```
A document should be loaded using OpenInputStream according to this: http://stackoverflow.com/a/20565102/1421847

So I probably have to read the "document" as a Stream and write it as a file in my application's folder to be able to load it as a SQLite DB?

**Comment by CodeLiftSleep** [comment]
You pass in the path value...

string DBPath = Application.Path  + "\yourDB.sqlite"
using (SQLiteConnection db = new SQLiteConnection(DBPath)){
//Your code here
}

**Comment by praeclarum** [comment]
I updated the README to demonstrate using the special folder "MyDocuments" to put the database into.
