### ISSUE TITLE
Could not load type 'SQLite.SQLiteConnection' from assembly 'SQLite-net, Version=1.1.0.0, Culture=neutral, PublicKeyToken=null'.

### ISSUE THREAD

**Issue by jbravobr** [praeclarum/sqlite-net#452]
After update a XF App with the latest version of sqlite-net-pcl (version 1.2.0), at the creation of a connection I've got:

Could not load type 'SQLite.SQLiteConnection' from assembly 'SQLite-net, Version=1.1.0.0, Culture=neutral, PublicKeyToken=null'.

**Comment by ericsink** [comment]
Wild guesses, probably dumb ones:  

Something is still referencing the assembly with its old version number?  Force a full rebuild?

Do you have remnants of the pre-1.0 SQLitePCL.raw stuff still around?

Googling the error message results in stuff about the GAC.  But you said XF, which I assume means Xamarin Forms, so probably not?

**Comment by jbravobr** [comment]
Yes, Xamarin Forms. I already remove all assemblies, packages and rebuild
the app and a nothing changes
Em sex, 23 de set de 2016 às 16:57, Eric Sink <notifications@github.com>
escreveu:

**Comment by jbravobr** [comment]
I found a hide directory with a version of SQLite-net 1.1.0, after erase that everything works fine!
