### ISSUE TITLE
1.2.0 breaks existing app with "tostring" not implemented

### ISSUE THREAD

**Issue by jlindborg** [praeclarum/sqlite-net#454]
a little odd - using a GUID as an identifier and I tuck in removable rows prefixed with zeros - this call in the check for that data works with 1.1.2 and breaks when I update to 1.2:

var item = _database.Table<History>().FirstOrDefault(v => v.Id.ToString().StartsWith("00000000"));

with an error about tostring not being implemented.
Hopped back to 1.1.2 and all is well.
it kicked out some other errors after updating as well, I'll go dig those out when I get some time.

**Comment by praeclarum** [comment]
Ah the difference is that FirstOrDefault now accepts a query! It used to be just the LInQ function, but now gets compiled and sent to the DB. The DB doesn't know how to handle ToString. You can change your code. Y adding a ToList before the FirstOrDefault if you want to use code not supported by the translator. 

As a side not, I should improve that error message. :-)
