### ISSUE TITLE
Cache reflection of StoreAsText for enum values types

### ISSUE THREAD

**Issue by GeertvanHorrik** [praeclarum/sqlite-net#458]
Because I am having issues executing some simple queries with date/time ticks, I was checking out the source code. Seems that the support for enums can be faster by caching the reflection results:

https://github.com/praeclarum/sqlite-net/blob/master/src/SQLite.cs#L2362

A ConcurrentDictionary<Type, bool> _storeAsTextCache could solve this?

**Comment by praeclarum** [comment]
I generally don't like to make perf changes without a test demonstrating the problem. Is reflection very slow for enums? -and that's what you're running into?

My guess (without perf numbers) is that the slowdown is in the string creation more than the lookup. (But I could be wrong.)

All that said, this is a new feature (text based enums) so I'd be happy to take a PR. I'm just not sure I would work on it until I saw the profile. 

Thanks!

**Comment by GeertvanHorrik** [comment]
Excellent point, I am first debugging a different issue I am having (that got me into this anyway). Will create a separate issue for that.

**Comment by GeertvanHorrik** [comment]
See #459 for more details.

**Comment by GeertvanHorrik** [comment]
Depending on how often it's used, it might be useful to optimize:

Note that this could also be better for garbage collection (even though strings are cached in string tables).

{code}
        private static Dictionary<MyEnum, string> EnumCache = new Dictionary<MyEnum, string>();

        static void Main(string[] args)
        {
            foreach (MyEnum enumValue in Enum.GetValues(typeof(MyEnum)))
            {
                EnumCache[enumValue] = enumValue.ToString();
            }

            ExecuteWithTimer("Manual Casts", () =>
            {
                var value1 = MyEnum.Value1.ToString();
                var value2 = MyEnum.Value2.ToString();
                var value3 = MyEnum.Value3.ToString();
            });

            ExecuteWithTimer("Cached Casts", () =>
            {
                var value1 = EnumCache[MyEnum.Value1];
                var value2 = EnumCache[MyEnum.Value2];
                var value3 = EnumCache[MyEnum.Value3];
            });

            Console.ReadKey();
        }

        private static void ExecuteWithTimer(string name, Action action, int timesToExecute = 1000 * 100 * 10) // 1 million
        {
            var stopwatch = Stopwatch.StartNew();

            for (var i = 0; i < timesToExecute; i++)
            {
                action();
            }

            stopwatch.Stop();

            var average = stopwatch.ElapsedMilliseconds / (double)timesToExecute;

            Console.WriteLine($"Executed '{name}' in '{stopwatch.Elapsed}', average = '{average}' ms");
        }
    }

    public enum MyEnum
    {
        Value1,

        Value2,

        Value3,

        Value4,
    }
{code}

Output:

![image](https://cloud.githubusercontent.com/assets/1246444/19767133/aac40b32-9c51-11e6-9fb8-b1156998140c.png)

If you are interested I am happy to pr.

**Comment by praeclarum** [comment]
OK, you've convinced me. Thank you for all the effort. If you have an implementation, I will take it!

I worry a little bit about multithreading when you have a cache like this and do wonder if a lock will kill your perf increase but, like I said, I'm willing to accept it! :-)

**Comment by GeertvanHorrik** [comment]
Sorry for my late reply, I was side-tracked. I've been working on an improved example to make sure that even in multithreaded scenarios (where locking would apply to the dictionary), it's much faster:

![image](https://cloud.githubusercontent.com/assets/1246444/20898623/6180da78-bb27-11e6-98e2-e5252bbd91b8.png)

Here is the updated code:

```
namespace EnumPerformance
{
    using System;
    using System.Collections.Generic;
    using System.Diagnostics;
    using System.Threading.Tasks;

    class Program
    {
        private static Dictionary<MyEnum, string> EnumCache = new Dictionary<MyEnum, string>();

        private const int OneMillion = 1000 * 100 * 10;

        static void Main(string[] args)
        {
            foreach (MyEnum enumValue in Enum.GetValues(typeof(MyEnum)))
            {
                EnumCache[enumValue] = enumValue.ToString();
            }

            ExecuteWithTimer("Manual Casts", ActionToInvoke_NotCached);
            ExecuteWithTimerParallel("Manual Casts (Parallel)", ActionToInvoke_NotCached);

            ExecuteWithTimer("Cached Casts", ActionToInvoke_Cached);
            ExecuteWithTimerParallel("Cached Casts (Parallel)", ActionToInvoke_Cached);

            Console.ReadKey();
        }

        private static void ActionToInvoke_NotCached()
        {
            var value1 = MyEnum.Value1.ToString();
            var value2 = MyEnum.Value2.ToString();
            var value3 = MyEnum.Value3.ToString();
        }

        private static void ActionToInvoke_Cached()
        {
            lock (EnumCache)
            {
                var value1 = EnumCache[MyEnum.Value1];
                var value2 = EnumCache[MyEnum.Value2];
                var value3 = EnumCache[MyEnum.Value3];
            }
        }

        private static void ExecuteWithTimer(string name, Action action, int timesToExecute = 10 * OneMillion)
        {
            var stopwatch = Stopwatch.StartNew();

            for (var i = 0; i < timesToExecute; i++)
            {
                action();
            }

            stopwatch.Stop();

            var average = stopwatch.ElapsedMilliseconds / (double)timesToExecute;

            Console.WriteLine($"Executed '{name}' in '{stopwatch.Elapsed}', average = '{average}' ms");
        }

        private static void ExecuteWithTimerParallel(string name, Action action, int timesToExecute = 10 * OneMillion)
        {
            var stopwatch = Stopwatch.StartNew();

            Parallel.For(0, timesToExecute, i => action());

            stopwatch.Stop();

            var average = stopwatch.ElapsedMilliseconds / (double)timesToExecute;

            Console.WriteLine($"Executed '{name}' in '{stopwatch.Elapsed}', average = '{average}' ms");
        }
    }

    public enum MyEnum
    {
        Value1,

        Value2,

        Value3,

        Value4,
    }
}
```

Will start the PR soon.

**Comment by GeertvanHorrik** [comment]
btw had some issues running the unit tests. I think it's better to reference NUnit as nuget instead of a direct reference (could screw up if someone accidentally installed the PCL version of NUnit as well).

I can include this in the PR if you wish.

**Comment by praeclarum** [comment]
Ha I didn't know I still had a direct ref. It's an old project.

The trick is, Xam Studio didn't support v3 of NUnit last I checked. So we need to stick with the v2 line. (Unless XS is fixed?)

**Comment by GeertvanHorrik** [comment]
Happy to stay with 2.* (I am sticking to that as well, still need a big bang for all projects to move to v3). You can still reference v2 via nuget though, will do that in this PR as well.

I also noted that I need the SQLite dll (in my case x64) in the test output directory in order for the tests to succeed. You probably have it installed somewhere and added it to the path, but maybe it's good to have a quick-start guide somewhere (or I must have missed it).

**Comment by GeertvanHorrik** [comment]
See #479

**Comment by praeclarum** [comment]
Yeah I run the tests on a mac and sqlite is installed by the system.

It just occurred to me that the test should be split into 2 to test two different scenarios:

1. Directly binding to sqlite3 as the tests do now
2. Referencing sqlite.raw to test that interface
