### ISSUE TITLE
MigrateTable is never called.

### ISSUE THREAD

**Issue by LuigiMaestrelli** [praeclarum/sqlite-net#461]
When I execute the CreateTable function, the return of Execute(query) is always "1". Even when the table already exists.

**Comment by adamelliottsweeting** [comment]
@LuigiMaestrelli I get the same issue, did you find a solution?

I looked into it and found that `SQLite3.Changes` was returning `1` as the number of rows affected by the create table statement even though the table already exists.

1. Add a property to an existing model which already has an associated table.

2. Call `CreateTable<ModelClass>();` to migrate the table.

Internally, this calls `Execute`, and will only call `MigrateTable` if `count = 0`.
https://github.com/praeclarum/sqlite-net/blob/38a5ae07c886d6f62cecd8fdeb8910d9b5a77546/src/SQLite.cs#L422-L427

`Execute` calls `ExecuteNonQuery`
https://github.com/praeclarum/sqlite-net/blob/38a5ae07c886d6f62cecd8fdeb8910d9b5a77546/src/SQLite.cs#L659

That calls `SQLite3.Changes` which returns rows affected as `1` even though the table already exists.
https://github.com/praeclarum/sqlite-net/blob/38a5ae07c886d6f62cecd8fdeb8910d9b5a77546/src/SQLite.cs#L2157-L2161

I checked my table afterwards by calling `GetTableInfo("tablename");` to get all the fields of the table, the new property does not have an associated field.

**Comment by adamelliottsweeting** [comment]
My particular issue may not be because of SQLite-net.
As I noted, `SQLite3.Changes` returns `1` which, for me, references the `SQLite for Windows Runtime (Windows 8.1)` version `3.15.0` - currently the latest version.
https://visualstudiogallery.msdn.microsoft.com/1d04f82f-2fe9-4727-a2f9-a2db127ddc9a

@LuigiMaestrelli are you using this library or one of it's variants? I haven't seen anywhere to submit issues for it.

**Comment by LuigiMaestrelli** [comment]
@adamelliottsweeting 
I haven't found any solution yet. I'm using this library.

**Comment by praeclarum** [comment]
@LuigiMaestrelli which platform are you running on?

**Comment by LuigiMaestrelli** [comment]
@praeclarum 

I'm running Xamarin.Forms on iOS 9 and 10; Android 4 to 7

**Comment by teracat** [comment]
We have a problem that I think is related to this issue: when we call the CreateTable<> with a class that has a new field, that field is not added to the table causing an Exception when an item is saved (SQLite.SQLiteException: no such column: xxx).

We are running Xamarin.Forms 2.3.3 & sqlite-net-pcl 1.2.1 on Android 6.0.1 (Galaxy Tab S).

**Comment by LuigiMaestrelli** [comment]
@praeclarum 

Nothing yet? 
To help with this, please make the MigrateTable public so we can call yourselves.

**Comment by praeclarum** [comment]
I have fixed the logic for detecting if table already exist and added a test so we hopefully don't regress again.

**Comment by LuigiMaestrelli** [comment]
Thank you, I will test it on a new release.

**Comment by kyluke** [comment]
Has this fix been put into a release?

**Comment by kyluke** [comment]
What's the status on this?
