### ISSUE TITLE
Cannot install nuget package (VisualStudio 2013)

### ISSUE THREAD

**Issue by gimmebytes** [praeclarum/sqlite-net#463]
Hi there,

I tried to install your suggested nuget package to get started with sqlite-net, but the package manager fails with the following error message (translated from german):

> Trying to resolve dependency "SQLitePCLRaw.bundle_green (≥ 1.0.1)".
> "SQLitePCLRaw.bundle_green" is already an dependency for "SQLitePCLRaw.core".

Any hints how to resolve this?

Meta: Visual Studio 2013, .NET 4.5, Mixed Winforms/WPF Application

**Comment by ericsink** [comment]
You need to install nuget 2.12
