### ISSUE TITLE
Show Stopper for New Nuget Package

### ISSUE THREAD

**Issue by spoiledtechie** [praeclarum/sqlite-net#465]
Just so you know, the new NUGET package you released for the PCL version, there is a show stopper.

Getting this error when I am creating the DB and connection for the first time.  NON-async.

you need to call SQLitePCL.raw.SetProvider(). If you are using a bundle package, this is done by calling SQLitePCL.Batteries.Init().

**Comment by ericsink** [comment]
Probably not a show stopper.

I believe you get this error message if you add the nuget package only to your portable library.  You need to add it to your app project as well.

**Comment by praeclarum** [comment]
I added a note to the README, let's hope it's sufficient: https://github.com/praeclarum/sqlite-net/commit/724fb390d84ea56ffe36f09d43be432164e676f6
