### ISSUE TITLE
Split SQLite.cs file

### ISSUE THREAD

**Issue by polkduran** [praeclarum/sqlite-net#466]
**SQLite.cs** (~3500 loc) file could be split in several files. 
It would be easier to follow the changes.
Pull Requests would have less conflicts.

**Comment by nurchi** [comment]
As much as I agree, this was implemented in such a way that you add a single file to your project (NuGet or download directly), no other dependencies (other than sqlite3.dll from the official website). In any other case, this would pretty much have to be packaged as a DLL that needs to be referenced, etc. So it does make debugging less convenient, but easier to implement with less things to ship with your final app...

**Comment by praeclarum** [comment]
I appreciate where you're coming from @polkduran but I'm gonna keep it 1 file for now. Certainly, in the age of nuget, this is less important. But this lib has a long history and I don't care to break a bunch of apps (including my own :-))
