### ISSUE TITLE
UWP error

### ISSUE THREAD

**Issue by erportico** [praeclarum/sqlite-net#469]
In my Xamarin Forms project I updated SQLite library (nuget sqlite-net-pcl) and now I receive this error for Windows project:

> System.NotSupportedException: Cannot compile: Parameter at SQLite.TableQuery1.CompileExpr(Expression expr, List1 queryArgs)
> at SQLite.TableQuery1.CompileExpr(Expression expr, List1 queryArgs) at SQLite.TableQuery1.CompileExpr(Expression expr, List1 queryArgs) at SQLite.TableQuery1.CompileExpr(Expression expr, List1 queryArgs) at SQLite.TableQuery1.GenerateCommand(String selectionList)    at
>   SQLite.TableQuery1.GetEnumerator() at System.Collections.Generic.List`1..ctor(IEnum

iOS is working fine.
Any suggestions? Thank you in advance

**Comment by praeclarum** [comment]
My guess is you're calling "FirstOrDefault" and we switched from doing that on the app vs translating it to a query. So it's trying to make a query where it wasn't before.

Find the line and simply change `query.FirstOrDefault(...)` to `query.ToList().FirstOrDefault(...)`

**Comment by erportico** [comment]
Thanks. It'ws working
