### ISSUE TITLE
different tble name but same table mapping issue

### ISSUE THREAD

**Issue by dashne** [praeclarum/sqlite-net#470]
I have main table(say: main) which one column of it refers to a nother tables (say: t1, and t2 for simplicity)
those tow tables have the same table mapping,the question is how to get the table(t1 or t2) based on selected column names in the main table?

**Comment by praeclarum** [comment]
I'm not sure I fully understand the problem, but I'm guessing you'll have to resort to manual queries:

```
var t1data = c.Query<T>("select * from t1 where id = ?", main.t1);
var t2data = c.Query<T>("select * from t2 where id = ?", main.t2);
```
