### ISSUE TITLE
Loading data without create tables

### ISSUE THREAD

**Issue by armandomusto** [praeclarum/sqlite-net#471]
I am trying to connect to an existing db and I want to load some data from a table.

var db = new SQLiteConnection("Mydatabase.db");
var query = db.Query<TestsNameModel>("SELECT * FROM TESTSNAME");

query object contains 5 TestsModel elements (it is fine), but all the object parameters are always null 

[Table("TESTSNAME")]
    public class TestsNameModel
    {
        [PrimaryKey]
        [MaxLength(2)]
        public string Code { get; set; }
        [MaxLength(25)]
        public string Name { get; set; }
    }

Table
CREATE TABLE [TESTSNAME] (
	[NAME] varchar(25) NOT NULL, 
	[CODE] varchar(2) NOT NULL PRIMARY KEY
);

Can you help me with this? I don't want create the table at the beginning, but I want be able to work with an exisisting db.

Thanks
Armando

**Comment by praeclarum** [comment]
`CreateTable` is poorly named, think of it more as `RegisterTable` - it will only create the table if it doesn't exist. It will also migrate (add columns) to an existing table.

Just call `CreateTable<TestsNameModel>()` and you're all set to query.

**Comment by armandomusto** [comment]
Hi Frank,
thanks you your answer, but it does not solve the issue, my I did not explained it correctly.
I already have a db file with the schema already in place, so I don't need to create table or other schema objects, I need simply to get data from it. When I use the Query statment I got the list of object, but the object does not contains any value. Please check the image to see what I mean

![image](https://cloud.githubusercontent.com/assets/4960206/20389143/6d216036-acc8-11e6-99c5-0227866c3a1a.png)

**Comment by praeclarum** [comment]
OK, I'll have to look at the code path to figure out what's going on.

**Comment by armandomusto** [comment]
Thanks. it is working now. I just updated the libraries from Nuget anf it is fine.
Thanks a lot.

**Comment by praeclarum** [comment]
Glad to hear. Yeah that was confusing!
