### ISSUE TITLE
SQLiteException when I try read a SQLite file generated out of application

### ISSUE THREAD

**Issue by viniciusmaia** [praeclarum/sqlite-net#472]
I'm using SQLite PCL with Xamarin and, in my application, I had to download a SQLite file as a byte array (byte[]) from a web service and use this file in my app as a SQLite DataBase. 

I'm trying to do this, but I'm had SQLiteException: file is encrypted or is not a database

That's the class that I'm tryng to create a SQLite:

```
public abstract class BaseLocalDao<POCO, Entity> : ILocalDao<POCO, Entity> where POCO : class, IPOCO where Entity : class, IEntity, new()
    {
        protected IConverter<POCO, Entity> _converter;
        protected readonly SQLiteConnection _dataBase;

        public BaseLocalDao()
        {
            var controleArquivoBanco = Mvx.Resolve<IControleArquivoBanco>();

            _dataBase = new SQLiteConnection(controleArquivoBanco.GetPath());        
            _dataBase.CreateTable<Entity>();
        }
}
```
The connection is create, but when CreateTable is execute, the app throw the SQLiteExcpetion that I mentioned.

**Comment by praeclarum** [comment]
It sounds to me like the DB is encrypted or corrupted.

Try opening on the command: `sqlite3 my.db`

That should let you know of any troubles.

**Comment by viniciusmaia** [comment]
I used SQLite Studio to check the file generated by web service and there aren't error's on file.

**Comment by viniciusmaia** [comment]
where I has to execute this command?

**Comment by viniciusmaia** [comment]
I find the error. You can delete or close this issue. I was converting the string of SQLite file to byte[] for the wrong way.
