### ISSUE TITLE
The type initializer for 'SQLite.SQLiteConnection' threw an exception. ---> System.DllNotFoundException: e_sqlite3

### ISSUE THREAD

**Issue by JakubHolovsky** [praeclarum/sqlite-net#478]
On our Xamarin Android project we are trying to switch from sqlite-net to official sqlite-net-pcl package.

[![enter image description here][1]][1]

However after this switch when creating a new SQLiteConnection I am getting following exception:

> The type initializer for 'SQLite.SQLiteConnection' threw an exception.
> ---> System.DllNotFoundException: e_sqlite3

Full exception:

> Xamarin caused by: android.runtime.JavaProxyThrowable:
> System.TypeInitializationException: The type initializer for
> 'SQLite.SQLiteConnection' threw an exception. --->
> System.DllNotFoundException: e_sqlite3   at (wrapper
> managed-to-native)
> SQLitePCL.SQLite3Provider_e_sqlite3+NativeMethods:sqlite3_libversion_number
> ()   at
> SQLitePCL.SQLite3Provider_e_sqlite3.SQLitePCL.ISQLite3Provider.sqlite3_libversion_number
> () [0x00000] in <c540576fb3104e48a699677aac26b47f>:0    at
> SQLitePCL.raw.SetProvider (SQLitePCL.ISQLite3Provider imp) [0x00000]
> in <4472a4c16754425197d915f39ebd937e>:0    at
> SQLitePCL.Batteries_V2.Init () [0x0000d] in
> <1125db7e18f0475797b2764ec6653cf1>:0    at
> SQLite.SQLiteConnection..cctor () [0x00000] in
> /Users/fak/Dropbox/Projects/sqlite-net/src/SQLite.cs:171     --- End
> of inner exception stack trace --- 	at
> mono.android.view.View_OnClickListenerImplementor.n_onClick(Native
> Method) 	at
> mono.android.view.View_OnClickListenerImplementor.onClick(View_OnClickListenerImplementor.java:30)
> 	at android.view.View.performClick(View.java:4780) 	at
> android.view.View$PerformClick.run(View.java:19866) 	at
> android.os.Handler.handleCallback(Handler.java:739) 	at
> android.os.Handler.dispatchMessage(Handler.java:95) 	at
> android.os.Looper.loop(Looper.java:135) 	at
> android.app.ActivityThread.main(ActivityThread.java:5254) 	at
> java.lang.reflect.Method.invoke(Native Method) 	at
> java.lang.reflect.Method.invoke(Method.java:372) 	at
> com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
> 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

In the log I can see following info:

> 12-01 10:43:05.356 D/Mono    (11194): DllImport attempting to load:
> 'e_sqlite3'. 12-01 10:43:05.358 D/Mono    (11194): DllImport error
> loading library
> '/storage/emulated/0/Android/data/com.psonar.android/files/.__override__/libe_sqlite3':
> 'dlopen failed: library
> "/data/app/com.psonar.android-1/lib/x86//storage/emulated/0/Android/data/com.psonar.android/files/.__override__/libe_sqlite3"
> not found'. 12-01 10:43:05.360 D/Mono    (11194): DllImport error
> loading library
> '/storage/emulated/0/Android/data/com.psonar.android/files/.__override__/libe_sqlite3.so':
> 'dlopen failed: library
> "/data/app/com.psonar.android-1/lib/x86//storage/emulated/0/Android/data/com.psonar.android/files/.__override__/libe_sqlite3.so"
> not found'. 12-01 10:43:05.360 D/Mono    (11194): DllImport error
> loading library '/system/lib/libe_sqlite3': 'dlopen failed: library
> "/data/app/com.psonar.android-1/lib/x86//system/lib/libe_sqlite3" not
> found'. 12-01 10:43:05.360 D/Mono    (11194): DllImport error loading
> library '/system/lib/libe_sqlite3.so': 'dlopen failed: library
> "/data/app/com.psonar.android-1/lib/x86//system/lib/libe_sqlite3.so"
> not found'. 12-01 10:43:05.360 D/Mono    (11194): DllImport error
> loading library 'libe_sqlite3': 'dlopen failed: library
> "/data/app/com.psonar.android-1/lib/x86/libe_sqlite3" not found'.
> 12-01 10:43:05.361 D/Mono    (11194): DllImport error loading library
> 'libe_sqlite3.so': 'dlopen failed: library
> "/data/app/com.psonar.android-1/lib/x86/libe_sqlite3.so" not found'.
> 12-01 10:43:05.361 D/Mono    (11194): DllImport error loading library
> 'e_sqlite3': 'dlopen failed: library
> "/data/app/com.psonar.android-1/lib/x86/e_sqlite3" not found'. 12-01
> 10:43:05.362 D/Mono    (11194): DllImport error loading library
> '/storage/emulated/0/Android/data/com.psonar.android/files/.__override__/libe_sqlite3':
> 'dlopen failed: library
> "/data/app/com.psonar.android-1/lib/x86//storage/emulated/0/Android/data/com.psonar.android/files/.__override__/libe_sqlite3"
> not found'. 12-01 10:43:05.364 D/Mono    (11194): DllImport error
> loading library
> '/storage/emulated/0/Android/data/com.psonar.android/files/.__override__/libe_sqlite3.so':
> 'dlopen failed: library
> "/data/app/com.psonar.android-1/lib/x86//storage/emulated/0/Android/data/com.psonar.android/files/.__override__/libe_sqlite3.so"
> not found'. 12-01 10:43:05.364 D/Mono    (11194): DllImport error
> loading library '/system/lib/libe_sqlite3': 'dlopen failed: library
> "/data/app/com.psonar.android-1/lib/x86//system/lib/libe_sqlite3" not
> found'. 12-01 10:43:05.364 D/Mono    (11194): DllImport error loading
> library '/system/lib/libe_sqlite3.so': 'dlopen failed: library
> "/data/app/com.psonar.android-1/lib/x86//system/lib/libe_sqlite3.so"
> not found'. 12-01 10:43:05.364 D/Mono    (11194): DllImport error
> loading library 'libe_sqlite3': 'dlopen failed: library
> "/data/app/com.psonar.android-1/lib/x86/libe_sqlite3" not found'.
> 12-01 10:43:05.364 D/Mono    (11194): DllImport error loading library
> 'libe_sqlite3.so': 'dlopen failed: library
> "/data/app/com.psonar.android-1/lib/x86/libe_sqlite3.so" not found'.
> 12-01 10:43:05.365 D/Mono    (11194): DllImport error loading library
> 'libe_sqlite3': 'dlopen failed: library
> "/data/app/com.psonar.android-1/lib/x86/libe_sqlite3" not found'.
> 12-01 10:43:05.365 W/Mono    (11194): DllImport unable to load library
> 'dlopen failed: library
> "/data/app/com.psonar.android-1/lib/x86/libe_sqlite3" not found'.
> 12-01 10:43:05.365 D/Mono    (11194): DllImport attempting to load:
> 'e_sqlite3'. 12-01 10:43:05.366 D/Mono    (11194): DllImport error
> loading library
> '/storage/emulated/0/Android/data/com.psonar.android/files/.__override__/libe_sqlite3':
> 'dlopen failed: library
> "/data/app/com.psonar.android-1/lib/x86//storage/emulated/0/Android/data/com.psonar.android/files/.__override__/libe_sqlite3"
> not found'. 12-01 10:43:05.368 D/Mono    (11194): DllImport error
> loading library
> '/storage/emulated/0/Android/data/com.psonar.android/files/.__override__/libe_sqlite3.so':
> 'dlopen failed: library
> "/data/app/com.psonar.android-1/lib/x86//storage/emulated/0/Android/data/com.psonar.android/files/.__override__/libe_sqlite3.so"
> not found'. 12-01 10:43:05.368 D/Mono    (11194): DllImport error
> loading library '/system/lib/libe_sqlite3': 'dlopen failed: library
> "/data/app/com.psonar.android-1/lib/x86//system/lib/libe_sqlite3" not
> found'. 12-01 10:43:05.368 D/Mono    (11194): DllImport error loading
> library '/system/lib/libe_sqlite3.so': 'dlopen failed: library
> "/data/app/com.psonar.android-1/lib/x86//system/lib/libe_sqlite3.so"
> not found'. 12-01 10:43:05.368 D/Mono    (11194): DllImport error
> loading library 'libe_sqlite3': 'dlopen failed: library
> "/data/app/com.psonar.android-1/lib/x86/libe_sqlite3" not found'.
> 12-01 10:43:05.368 D/Mono    (11194): DllImport error loading library
> 'libe_sqlite3.so': 'dlopen failed: library
> "/data/app/com.psonar.android-1/lib/x86/libe_sqlite3.so" not found'.
> 12-01 10:43:05.369 D/Mono    (11194): DllImport error loading library
> 'e_sqlite3': 'dlopen failed: library
> "/data/app/com.psonar.android-1/lib/x86/e_sqlite3" not found'. 12-01
> 10:43:05.370 D/Mono    (11194): DllImport error loading library
> '/storage/emulated/0/Android/data/com.psonar.android/files/.__override__/libe_sqlite3':
> 'dlopen failed: library
> "/data/app/com.psonar.android-1/lib/x86//storage/emulated/0/Android/data/com.psonar.android/files/.__override__/libe_sqlite3"
> not found'. 12-01 10:43:05.371 D/Mono    (11194): DllImport error
> loading library
> '/storage/emulated/0/Android/data/com.psonar.android/files/.__override__/libe_sqlite3.so':
> 'dlopen failed: library
> "/data/app/com.psonar.android-1/lib/x86//storage/emulated/0/Android/data/com.psonar.android/files/.__override__/libe_sqlite3.so"
> not found'. 12-01 10:43:05.372 D/Mono    (11194): DllImport error
> loading library '/system/lib/libe_sqlite3': 'dlopen failed: library
> "/data/app/com.psonar.android-1/lib/x86//system/lib/libe_sqlite3" not
> found'. 12-01 10:43:05.372 D/Mono    (11194): DllImport error loading
> library '/system/lib/libe_sqlite3.so': 'dlopen failed: library
> "/data/app/com.psonar.android-1/lib/x86//system/lib/libe_sqlite3.so"
> not found'. 12-01 10:43:05.372 D/Mono    (11194): DllImport error
> loading library 'libe_sqlite3': 'dlopen failed: library
> "/data/app/com.psonar.android-1/lib/x86/libe_sqlite3" not found'.
> 12-01 10:43:05.372 D/Mono    (11194): DllImport error loading library
> 'libe_sqlite3.so': 'dlopen failed: library
> "/data/app/com.psonar.android-1/lib/x86/libe_sqlite3.so" not found'.
> 12-01 10:43:05.373 D/Mono    (11194): DllImport error loading library
> 'libe_sqlite3': 'dlopen failed: library
> "/data/app/com.psonar.android-1/lib/x86/libe_sqlite3" not found'.
> 12-01 10:43:05.373 W/Mono    (11194): DllImport unable to load library
> 'dlopen failed: library
> "/data/app/com.psonar.android-1/lib/x86/libe_sqlite3" not found'.

It's obvious what's wrong: **System.DllNotFoundException: e_sqlite3** however I can't find any relevant info that would lead to solving this problem. 

I checked my nuget packages and they all seem to be correctly installed.

[![enter image description here][2]][2]

I checked the package location and it is all correct. Very unsure where the cause might be.

  [1]: https://i.stack.imgur.com/mG9V4.png
  [2]: https://i.stack.imgur.com/TeR0i.png

**Comment by ericsink** [comment]
I can't reproduce this.  I just did a quick sample project and things seem to work fine.  So we need to figure out what's different about your situation.

The references do look right.

Are you building debug or release?

Is this happening in an emulator or on a device?

Are the nuget packages installed into a PCL project, or a Droid app project, or both?

The first thing I would do is go into the build output directory, find the APK file, and use "unzip -l" to examine its contents, and see if lib/x86/libe_sqlite3.so made it there.

**Comment by JakubHolovsky** [comment]
Hello Eric, 

**Is this happening in an emulator or on a device?**
I tried both - emulator and a device (one running API 22 the other one running api 23).

**Are you building debug or release?**
Build in debug (didn't think of trying release).

**Are the nuget packages installed into a PCL project, or a Droid app project, or both?**
Installed in Droid App project

**The first thing I would do is go into the build output directory, find the APK file, and use "unzip -l" to examine its contents, and see if lib/x86/libe_sqlite3.so made it there.**
Good tip, I will try that tomorrow.

**Comment by JakubHolovsky** [comment]
As you were suspecting -  **lib/x86/libe_sqlite3.so** didn't make it there:

http://i26.photobucket.com/albums/c148/Kubatko/sqlite-net-pcl.png

Any suspicion of why that might be happening?

**Comment by ericsink** [comment]
At the moment, I have no idea.  So I'll make some wild guesses of things to check.

Xamarin Android linker settings?

Target Android version?

Force a full rebuild?

Older versions of nuget or Visual Studio or Xamarin Studio?

**Comment by brminnick** [comment]
Do you have the linker enabled? Perhaps the linker is removing the library.

**Comment by JakubHolovsky** [comment]
OK, solved it. Even though I am a little bit confused. If I add the sqlite-pcl packages to my starting project then the libe_sqlite3 appears there correctly. If I have it in my droid project which is referenced by the starting project then it gets stripped away.

To answer the previous questions:

**Xamarin Android linker settings?**
Linker is set to "none".

**Target Android version?**
The latest one.

**Force a full rebuild?**
Tried that as well as deleted bin and obj folders and did complete rebuild.

**Older versions of nuget or Visual Studio or Xamarin Studio?**
All to the latest versions. (using VS 2015)

**Comment by ericsink** [comment]
Oh, yeah.  That would do it.

Not adding the pkg to the app project is a common problem.  But when I saw that you were adding it to a non-PCL Droid-specific project, I assumed that project was the app, not a library.

**Comment by JakubHolovsky** [comment]
All good then, thanks for your help. Closing :)

**Comment by 3green** [comment]
This error is still occurring with Xamarin PCL. 
Environment:  VS2015 Xamarin.Forms.Portable targeting Android
Build : Compile using Android 6.0.
Nugets : In Droid Project
sqlite-net-pcl  v1.3.1
SQLitePCLRaw.bundle_green v.1.1,2


-net-pcl  v1.3.1sqlite-net-pcl  v1.3.1
