### ISSUE TITLE
UWP project Fails to add package

### ISSUE THREAD

**Issue by danmendonca** [praeclarum/sqlite-net#481]
I can add the nuget package to every target plaform and the portable except UWP project.
When trying to add the package through the nugget manager I get the following error:

> Failed to retrieve information from remote source 'C:\Program Files\Microsoft SDKs\Service Fabric\packages\'.			0

**Comment by ericsink** [comment]
That error looks unrelated to sqlite-net or SQLitePCL.raw, and I haven't seen it before.  It kinda looks like a config problem with your tooling.

Can you add *any* nuget packages to your UWP project?

**Comment by danmendonca** [comment]
No, I am sorry I wasted your time, I did not need to add one before. Can you point me in the right direction though?

**Comment by ericsink** [comment]
No worries.  

But I don't think I have enough info to point you in the right direction.  :-(

If you can't add any nuget packages to a UWP project, then probably something with your dev environment (Visual Studio, I assume) is messed up.  You might need to check your configuration or even reinstall.

**Comment by praeclarum** [comment]
It sounds like your dev environment is causing the problem. I'm going to close this in the hopes that you got it worked out.
