### ISSUE TITLE
SELECT COUNT(*) doesn't seem to work in query

### ISSUE THREAD

**Issue by WiteCastle** [praeclarum/sqlite-net#486]
I may be understanding it wrong but I can't seem to get this to work:

```
var subAreaId = "SubAreaId1";
const string command = "SELECT COUNT(*) FROM Tile " +
                                       "WHERE SubAreaId = ?";
count = connection.Query<int>(command, subAreaId).FirstOrDefault();
```

The count is always returned as zero. I can get it to work by having the command return SELECT * and than counting the return list but I would think I could run that SELECT COUNT(*) command to possibly speed things up. Was this not intended?

This works though:

```
const string command = "SELECT * FROM Tile WHERE SubAreaId = ?";
var query = connection.Query<Tile>(command, subArea.Id);              
count = query.Count;
```

**Comment by pver** [comment]
You can use 'ExecuteScalar' for this instead of 'Query':

´´´
const string command = "SELECT COUNT(*) FROM Tile " +
                                       "WHERE SubAreaId = ?";
count = connection.ExecuteScalar<int>(command, subAreaId).FirstOrDefault();
´´´

**Comment by WiteCastle** [comment]
Yup, this looks like it'll work since Count uses it internally. Thank you.

**Comment by acaliaro** [comment]
> .FirstOrDefault();

it seems that ExecuteScalar does not have FirstOrDefault()
