### ISSUE TITLE
Would you take a PR w/ the SQLite.cs file refactored?

### ISSUE THREAD

**Issue by scionwest** [praeclarum/sqlite-net#490]
I wanted to help by improving your serialization time. When I went to look at the source I noticed it was all in 1 file. Is there any specific reason why? If I took the time time to break them up into smaller classes (move enums etc) would take the PR? Usually I don't ask before working on a PR, but in this case i felt like I should ask before I just start pulling it apart and then submitting a PR.

**Comment by ericsink** [comment]
Based on his previous responses to questions like this one, I predict that @praeclarum would say "no".  I believe he likes it as a single source file, to make it easier to use in non-nuget scenarios.

**Comment by praeclarum** [comment]
Thanks for asking! No I like the files how they are right now.
