### ISSUE TITLE
creating temp database

### ISSUE THREAD

**Issue by tofutim** [praeclarum/sqlite-net#492]
sqlite has an option to generate a temp database by passing in an empty string ""  - however sqlite-net blocks this by checking for a null or empty database name

```
		public SQLiteConnection (string databasePath, SQLiteOpenFlags openFlags, bool storeDateTimeAsTicks = true)
		{
			//if (string.IsNullOrEmpty (databasePath))
			//	throw new ArgumentException ("Must be specified", "databasePath");

			DatabasePath = databasePath;
```

**Comment by MKuckert** [comment]
https://www.sqlite.org/c3ref/open.html

> If the filename is an empty string, then a private, temporary on-disk database will be created. This private database will be automatically deleted as soon as the database connection is closed.

**Comment by MKuckert** [comment]
Felt free to "implement" this
