### ISSUE TITLE
Android N libsqlite.so issue

### ISSUE THREAD

**Issue by ptsiogas** [praeclarum/sqlite-net#493]
When i open the app in Android N i get the following warning dialog message:

"12-27 11:23:33.696: W/linker(21984): library "/system/lib/libsqlite.so" ("/system/lib/libsqlite.so") needed or dlopened by "/data/app/Mono.Android.DebugRuntime-1/lib/arm64/libmonosgen-32bit-2.0.so" is not accessible for the namespace "classloader-namespace" - the access is temporarily granted as a workaround for http://b/26394120, note that the access will be removed in future releases of Android."

Can you inform us when the library will support the changes made at the latest Android N?

**Comment by ericsink** [comment]
If you are using this library as packaged below, it should work fine with Android N:

https://www.nuget.org/packages/sqlite-net-pcl

**Comment by ptsiogas** [comment]
Firstly i used it only by copying the SQLite.cs file and it didn't worked and then i performed a nugget installation and it worked just fine.

**Comment by MoeHamoud** [comment]
@ptsiogas Did you remove the SQLite.cs file completely from your project and then added the sqlite-net-pcl nuget?

**Comment by ptsiogas** [comment]
@MoeHamoud yes that's correct. As i mentioned above, you should perform a nugget installation and not just copy the SQLite.cs file into your project.
