### ISSUE TITLE
Select() method returns incorrect data

### ISSUE THREAD

**Issue by JKennedy24** [praeclarum/sqlite-net#497]
Using V1.2.1 

I am writing some Integration tests using my .Net4.5 library.

I have the following:

`var customerIds = database.Table<Customer>().Select(customer => customer.Id);`

This returns the correct amount of customers but all Id's are 0 (default value).

But if I do:

`var customerIds = database.Table<Customer>().ToList().Select(customer => customer.Id);`

this returns the correct information.

This leads me to conclude the Select() method is broken

**Comment by corradolab** [comment]
Indeed.

I worked around it commenting out the whole Select function declaration in SQLite.cs (row 2809).

**Comment by ryanohs** [comment]
I ran into this same issue.

**Comment by JKennedy24** [comment]
Select Statement that causes this is here: [https://github.com/praeclarum/sqlite-net/blob/master/src/SQLite.cs#L2809](https://github.com/praeclarum/sqlite-net/blob/master/src/SQLite.cs#L2809). I dont know enough about the library to know where the error lies though

**Comment by praeclarum** [comment]
Projection isn't supported yet on the DB side; however a recent change will make this work (though it's not efficient).

https://github.com/praeclarum/sqlite-net/commit/2c5f1e1337fddd9f1ae62e3af9828693f2c21d89
