### ISSUE TITLE
DllImport error loading library 'libe_sqlite3'

### ISSUE THREAD

**Issue by 3green** [praeclarum/sqlite-net#499]
Hi I cant get sqlite to work anymore with Xamarin Android, I tried remedies in #478 , but alas that doesn't seem to be working. I created a stock Xamarin solution as detailed below, and then got the error below:

Error = 
 DllImport error loading library 'libe_sqlite3': 'dlopen failed: library "/data/app/POCSQLite.Droid-1/lib/arm/libe_sqlite3" not found'.

Environment is stock:
VS2015

Xamarin.Forms.Portable
targetting Android.

Many Thanks

Android Build:
Compile using Latest Platform ( Android 6.0 )

Nuget in Android Project:
sqlite-net-pcl v1.3.1
SQLitePCLRaw.bundle_green v1.1.2
SQLitePCLRaw.core v1.1.2
SQLitePCLRaw.lib.e_sqlite3.android v1.1.2
SQLitePCLRaw.provider.e_sqlite3.android v1.1.2

**Comment by ericsink** [comment]
Hmmm.

I just did the following and it worked:

Open VS 2015

Create a new Xamarin Android project, Blank App

Add sqlite-net-pcl 1.3.1 to it

In MainActivity.cs, add:

    using SQLite;

and in OnCreate, add:

    var c = new SQLiteConnection(":memory:");
    c.Execute("CREATE TABLE foo(x int);");
    System.Console.WriteLine("Hi");

Run the app (simulator, KitKat)

No errors.

Does this work for you?

If you have a proj/sln that reproduces the problem, can you post it somewhere?

**Comment by 3green** [comment]
OK have had a further look at the code and it is a case as in #478 whereby the 
sqlite is being accessed from an android class library:

But unless I am going mad, this was working OK before with sqlite-net-pcl v1.1.1 and SQLitePCL.raw v0.8.6. and looking at the apk lib there used to be no libe_sqlite3.so in the lib folder? 
It was when upgrading to sqlite-net-pcl v1.3.1 it seemed to stop working.

So if it was working before could it work again?
That is it possible to  have sqlite referenced only from a class library(s)?

My Solution setup is:

Main project : A = POCSQLite ( Portable )
Android : B = POCSQLite.Droid

Portable class lib : C = CLPortable --> SQlite
Class lib Android : D = CLAndroid --> SQlite

A refs C and all database is handled in C and D.
C refs SQLite
D refs SQLite

But neither projects A or B should ref sqlite.

Many thanks

**Comment by ericsink** [comment]
Depends on what you mean by reference.

You must add the nuget package to your android app project, even if that project itself has no code that deals with SQLite.  This is how the packages know to include the right native SQLite library, which is necessary nowadays for compatibility with Android N.

Sorry if I am misunderstanding your question.  If so, please clarify some more.

**Comment by 3green** [comment]
Hi thanks for the response.
Sorry meant I nuget sqlite thereby generating the references.

If I explain our setup then I hope it will clarify/resolve this for me and drive Sqlite forward:
Architecturally we have found it far better to have the data logic in a dedicated library, for non-trivial solutions, plugins and in-house code. So it would be a shame if we have to tightly couple to the Sqlite in the current Android Project.
If Sqlite is backwardly compatible then, could not the latest version of Sqlite  be in the project ( ie class library ) it is being used in without having to also be maintained in the Android Project as well?
Or is this a feature of Android N that demands that Sqlite be installed in the Android project even if Sqlite is not being used in that project, but in another project in the Solution?

Many Thanks

**Comment by ericsink** [comment]
"Or is this a feature of Android N that demands that Sqlite be installed in the Android project even if Sqlite is not being used in that project, but in another project in the Solution?"

Basically, yes, that's correct.

**Comment by 3green** [comment]
Hmnnn

**Comment by praeclarum** [comment]
Sorry but this is a limitation of the current architecture. You must include this package in your app.
