### ISSUE TITLE
1.3.1 IOS Target depends upon Microsoft.Win32.Primitives 4.0.1

### ISSUE THREAD

**Issue by M-Curtis** [praeclarum/sqlite-net#500]
When I try to update my solutions sqlite-net package to 1.3.1 from 1.2.0 I get the following error:

`"Could not install package 'Microsoft.Win32.Primitives 4.0.1'. You are trying to install this package into a project that targets 'Xamarin.iOS,Version=v1.0', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author."`

I'm unsure as to why you would include a win32 package as a dependency for an iOS target, or am I just doing something wrong?

**Comment by M-Curtis** [comment]
Also happy 500th Issue

**Comment by nhwilly** [comment]
Yeah, me, too.  Took a basic Xamarin Forms project with a PCL and Android projects.

I got this:

`You are trying to install this package into a project that targets '.NETPortable,Version=v4.6,Profile=Profile44', but the package does not 
contain any assembly references or content files that are compatible with that framework`

Did I get this wrong?  It installed just fine in the UWP and Droid related projects.

**Comment by praeclarum** [comment]
This has been fixed with version 1.4.

@nhwilly I cannot test profile 44. May I suggest switch to one of the more common ones such as 111 or 259? Even better the library now supports .NET Standard 1.1.

Sorry for the trouble!
