### ISSUE TITLE
How do I add this to a PCL project?

### ISSUE THREAD

**Issue by andyste1** [praeclarum/sqlite-net#501]
I have a VS2015 solution containing a Xamarin Android project that currently contains my SQLite data tier code, using your NuGet package (v1.3.1). I now want to move this code out into a separate project, in case I ever decide to create a Xamarin iOS app in the future. I've added a new PCL project to my solution, but when trying to add your package to it I get this error:

Could not install package 'sqlite-net-pcl 1.3.1'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.0,Profile=Profile24', but the package does not contain any assembly references or content files that are compatible with that framework.

I haven't worked with PCL projects before, so I'm probably doing something stupid but have no idea what.

**Comment by Gigex42** [comment]
Got the same problem just 5 minutes ago.

Tried to install it via nuget but cant get it to work.

**Comment by andyste1** [comment]
I found I was able to install it by clicking the "Target .Net Standard" link below the list of target platforms in the project settings. At this point I have to plead ignorance though - I'm still getting my head around .Net Core, .Net Standard, etc. Have I done the right thing? Are there any implications to this? 

However the PCL project won't compile because of a line of my code with "System.IO.Path(...". Being used to working with the full .Net framework, and not having to worry about such things, what do I need to do to pull in a reference to System.IO in the world of .Net Standard?!

**Comment by freever** [comment]
I have the same problem. It seems to be related to this one:
https://github.com/NuGet/Home/issues/3258

**Comment by valeev** [comment]
Install-package System.Runtime.InteropServices.RuntimeInformation
Just install this package before installing sqlite-net-pcl

**Comment by jmartine2** [comment]
@valeev thanks! That worked for me!

**Comment by GrapeJamMan** [comment]
Can't install this or the thumbed up fix from valeev, System.Runtime.InteropServices.RuntimeInformation, either. Same situation, despite this being a package "for .NET, Mono, and Xamarin applications" it doesn't work with a .NETPortable target.

**Comment by johnmbaughman** [comment]
As @GrapeJamMan stated, this is pretty disappointing and until Microsoft allows picking the platforms for a Xamarin application to target anything higher than 4.5 in a mobile app, it's pretty useless.

However, I was able to install it with the solution @valeev gave. Now, my project that doesn't use .NETStandard wants to update 44 packages it won't use... Is there a better way to do this?

**Comment by ericsink** [comment]
@johnmbaughman  Perhaps try using version 1.2.1?  That version was before NetStandard support was added.

**Comment by flyingxu** [comment]
the workaround of `Install-package System.Runtime.InteropServices.RuntimeInformation` should be noted in the `README.md` file.

**Comment by praeclarum** [comment]
Hi everyone! I'm looking into this now.

I have been testing on VS for Mac and .NET Core. I will test with VS2015 and see if I run into your same problems.

**Comment by praeclarum** [comment]
A couple notes:

1. The PCL is Profile 259 which will allow it to work on most .NET 4.5 based profiles (111, etc.). However 24, is .NET 4.0 based and not supported.

2. The 1.3.1 nuget included a "cheat" .NET std lib that has now been fixed to be compiled correctly and will hopefully fix the need for `System.Runtime.InteropServices.RuntimeInformation`
