### ISSUE TITLE
unauthorized access to "/system/lib64/libsqlite.so"

### ISSUE THREAD

**Issue by ratsey** [praeclarum/sqlite-net#503]
Problems with v1.0.8 and Android Nougat:

Detected problems with app native libraries(please consult log for details): libmonosgen-64bit-2.0.so: unauthorized access to "/system/lib64/libsqlite.so"

From what I read, the low-level Sqlite binary can no longer be used by apps and must be changed to an Android 'approved' way.  

Can we expect an update to the library?  :-)

**Comment by ndastur** [comment]
Getting this error too, but expected it to be okay as using sqlite.raw for sqlite dll loading. Not really sure what's going on here. I have in my log file

Note: I have defined USE_SQLITEPCL_RAW
Xamarin Forms Shared Project
Both sqlite-net.pcl nuget and SQLitePCLRaw.bundle_sqlcipher have been added to iOS and Droid projects and I have Sqlite.cs in by shared project

`
[Mono] DllImport attempting to load: '/system/lib64/libsqlite.so'.
[linker] library "/system/lib64/libsqlite.so" ("/system/lib64/libsqlite.so") needed or dlopened by "/data/app/Mono.Android.DebugRuntime-1/lib/x86_64/libmonosgen-64bit-2.0.so" is not accessible for the namespace: [name="classloader-namespace", ld_library_paths="", default_library_paths="/data/app/com.clinsoftsolutions.hospify-1/lib/x86_64:/data/app/com.clinsoftsolutions.hospify-1/base.apk!/lib/x86_64", permitted_paths="/data:/mnt/expand:/data/data/com.clinsoftsolutions.hospify"]
[Mono] DllImport error loading library '/system/lib64/libsqlite.so': 'dlopen failed: library "/data/app/com.clinsoftsolutions.hospify-1/lib/x86_64//system/lib64/libsqlite.so" not found'.
[linker] library "/system/lib64/libsqlite.so" ("/system/lib64/libsqlite.so") needed or dlopened by "/data/app/Mono.Android.DebugRuntime-1/lib/x86_64/libmonosgen-64bit-2.0.so" is not accessible for the namespace: [name="classloader-namespace", ld_library_paths="", default_library_paths="/data/app/com.clinsoftsolutions.hospify-1/lib/x86_64:/data/app/com.clinsoftsolutions.hospify-1/base.apk!/lib/x86_64", permitted_paths="/data:/mnt/expand:/data/data/com.clinsoftsolutions.hospify"]
[Mono] DllImport error loading library '/system/lib64/libsqlite.so': 'dlopen failed: library "/data/app/com.clinsoftsolutions.hospify-1/lib/x86_64//system/lib64/libsqlite.so" not found'.
[linker] library "/system/lib64/libsqlite.so" ("/system/lib64/libsqlite.so") needed or dlopened by "/data/app/Mono.Android.DebugRuntime-1/lib/x86_64/libmonosgen-64bit-2.0.so" is not accessible for the namespace: [name="classloader-namespace", ld_library_paths="", default_library_paths="/data/app/com.clinsoftsolutions.hospify-1/lib/x86_64:/data/app/com.clinsoftsolutions.hospify-1/base.apk!/lib/x86_64", permitted_paths="/data:/mnt/expand:/data/data/com.clinsoftsolutions.hospify"]
[Mono] DllImport error loading library '/system/lib64/libsqlite.so': 'dlopen failed: library "/data/app/com.clinsoftsolutions.hospify-1/lib/x86_64//system/lib64/libsqlite.so" not found'.
[linker] library "/system/lib64/libsqlite.so" ("/system/lib64/libsqlite.so") needed or dlopened by "/data/app/Mono.Android.DebugRuntime-1/lib/x86_64/libmonosgen-64bit-2.0.so" is not accessible for the namespace: [name="classloader-namespace", ld_library_paths="", default_library_paths="/data/app/com.clinsoftsolutions.hospify-1/lib/x86_64:/data/app/com.clinsoftsolutions.hospify-1/base.apk!/lib/x86_64", permitted_paths="/data:/mnt/expand:/data/data/com.clinsoftsolutions.hospify"]
[Mono] DllImport error loading library '/system/lib64/libsqlite.so': 'dlopen failed: library "/data/app/com.clinsoftsolutions.hospify-1/lib/x86_64//system/lib64/libsqlite.so" not found'.
[Mono] DllImport unable to load library 'dlopen failed: library "/data/app/com.clinsoftsolutions.hospify-1/lib/x86_64//system/lib64/libsqlite.so" not found'.
[Mono] DllImport attempting to load: '/system/lib64/libsqlite.so'.
[linker] library "/system/lib64/libsqlite.so" ("/system/lib64/libsqlite.so") needed or dlopened by "/data/app/Mono.Android.DebugRuntime-1/lib/x86_64/libmonosgen-64bit-2.0.so" is not accessible for the namespace: [name="classloader-namespace", ld_library_paths="", default_library_paths="/data/app/com.clinsoftsolutions.hospify-1/lib/x86_64:/data/app/com.clinsoftsolutions.hospify-1/base.apk!/lib/x86_64", permitted_paths="/data:/mnt/expand:/data/data/com.clinsoftsolutions.hospify"]
[Mono] DllImport error loading library '/system/lib64/libsqlite.so': 'dlopen failed: library "/data/app/com.clinsoftsolutions.hospify-1/lib/x86_64//system/lib64/libsqlite.so" not found'.
[linker] library "/system/lib64/libsqlite.so" ("/system/lib64/libsqlite.so") needed or dlopened by "/data/app/Mono.Android.DebugRuntime-1/lib/x86_64/libmonosgen-64bit-2.0.so" is not accessible for the namespace: [name="classloader-namespace", ld_library_paths="", default_library_paths="/data/app/com.clinsoftsolutions.hospify-1/lib/x86_64:/data/app/com.clinsoftsolutions.hospify-1/base.apk!/lib/x86_64", permitted_paths="/data:/mnt/expand:/data/data/com.clinsoftsolutions.hospify"]
[Mono] DllImport error loading library '/system/lib64/libsqlite.so': 'dlopen failed: library "/data/app/com.clinsoftsolutions.hospify-1/lib/x86_64//system/lib64/libsqlite.so" not found'.
[linker] library "/system/lib64/libsqlite.so" ("/system/lib64/libsqlite.so") needed or dlopened by "/data/app/Mono.Android.DebugRuntime-1/lib/x86_64/libmonosgen-64bit-2.0.so" is not accessible for the namespace: [name="classloader-namespace", ld_library_paths="", default_library_paths="/data/app/com.clinsoftsolutions.hospify-1/lib/x86_64:/data/app/com.clinsoftsolutions.hospify-1/base.apk!/lib/x86_64", permitted_paths="/data:/mnt/expand:/data/data/com.clinsoftsolutions.hospify"]
[Mono] DllImport error loading library '/system/lib64/libsqlite.so': 'dlopen failed: library "/data/app/com.clinsoftsolutions.hospify-1/lib/x86_64//system/lib64/libsqlite.so" not found'.
[linker] library "/system/lib64/libsqlite.so" ("/system/lib64/libsqlite.so") needed or dlopened by "/data/app/Mono.Android.DebugRuntime-1/lib/x86_64/libmonosgen-64bit-2.0.so" is not accessible for the namespace: [name="classloader-namespace", ld_library_paths="", default_library_paths="/data/app/com.clinsoftsolutions.hospify-1/lib/x86_64:/data/app/com.clinsoftsolutions.hospify-1/base.apk!/lib/x86_64", permitted_paths="/data:/mnt/expand:/data/data/com.clinsoftsolutions.hospify"]
[Mono] DllImport error loading library '/system/lib64/libsqlite.so': 'dlopen failed: library "/data/app/com.clinsoftsolutions.hospify-1/lib/x86_64//system/lib64/libsqlite.so" not found'.
[Mono] DllImport unable to load library 'dlopen failed: library "/data/app/com.clinsoftsolutions.hospify-1/lib/x86_64//system/lib64/libsqlite.so" not found'.
`

**Comment by ericsink** [comment]
Are you using the sqlite-net-pcl package?  It (and its SQLitePCL.raw dependency) contains updates to handle Android N issues properly.

https://www.nuget.org/packages/sqlite-net-pcl

**Comment by ndastur** [comment]
Yes, I am. I have just added so on Version 1.3.1
And I switch from the other sqlite.net package for exactly this reason. I.e. ran into the Android N problem

**Comment by ndastur** [comment]
In case it helps, attached is by references
<img width="321" alt="sqlitepcl" src="https://cloud.githubusercontent.com/assets/770545/22603941/3facfa1e-ea41-11e6-8c23-311d6e2036e7.png">

**Comment by ericsink** [comment]
@ndastur The comment I just posted a few minutes ago was probably more aimed at @ratsey 

Your situation may be different.  If I understand correctly, you are using the sqlite-net-pcl package, but you are also compiling SQLite.cs into your code.  That's a problem.  You should not be doing both.  Either use the nuget package, or build SQLite.cs into your app.

The best way forward is to remove SQLite.cs and get things working with the nuget package.  That'll require some rearranging if you are using SQLite.cs from a .shproj, which can't do nuget packages.

Also, if you want to use sqlcipher, you need to not add sqlite-net-pcl to your Droid project, but *do* add the SQLitePCLRaw sqlcipher bundle (as you have done).  Sorry this bit is somewhat confusing, but it's a compromise to allow most developers to use sqlite-net-pcl without needing any special initialization calls.

**Comment by ndastur** [comment]
Thank you @ericsink I'll try removing the SQLite.cs. Presumably, I still do:

`using Sqlite;
var conn = new SQLiteConnection("MyDatabase.db3");
conn.CreateTable<PrivateChats>();
`

to get things going. Or is it better to have `using SqlitePCL` ??

**Comment by ericsink** [comment]
Yeah, I think the code you've got is still what you want.  Your app is still primarily using the sqlite-net API.

**Comment by ndastur** [comment]
We may have made progress. I don't get the dll not found crash anymore, we get as far as can not open database. I'll see if it's a path issue...

**Comment by ndastur** [comment]
Mainly for others that find this thread. It was just a matter of setting a platform specific path. I might write up a wiki page on how to use this in a shared project. @praeclarum would you accept that PR?

**Comment by praeclarum** [comment]
@ndastur I would accept that! That said, the current plans are to make a new package to simplify some of this so the Wiki would have to be updated after that: #568

**Comment by ndastur** [comment]
Yeap. Lets finalise the changes we have discussed in the other issues and then write up a definitive guide

**Comment by LucioMSP** [comment]
someone have a solution for this? 

I have the sql-net-pcl install ()on Visual Studio for Mac and show the popup: 

Detected problems with app native libraries(please consult log for details): libmonosgen-2.0.so: unauthorized access to "/system/lib64/libsqlite.so"

**Comment by TheSayvior** [comment]
Got the same issue as @LucioMSP  on Windows PC in visual Studio

**Comment by LucioMSP** [comment]
Hi @TheSayvior I find the solution, you have to do is uninstall the Nuget you have and install the SQLite-net Official Portable Library author Frank A. Krueger, version 1.4.118. So you just have to change the way you save your information.

**Comment by dillahbaraja** [comment]
the error is happend when using Android 7.0, try to using below 7.0 Nougat...

**Comment by l3ender** [comment]
I currently have a shared project setup, so I am not able to reference the Nuget package. However, if I update SQLite.cs in my shared project, should the issue go away? I've done that (using the SQLite.cs file from master branch), but I am still seeing the access error.

I appreciate any advice. Thanks!

**Comment by ericsink** [comment]
@l3ender For compatibility with Android N, you can't reference the system SQLite, so you now have to bundle a sqlite library into your app.  Are you doing that yet?

And then you need to configure SQLite.cs to talk to your bundled sqlite native library instead of the one from the system.  There are multiple ways to do that.

**Comment by l3ender** [comment]
@ericsink Thanks for your post, that help clarify that there are steps that I am missing.

I believe I'm bundling sqlite into my app by referencing [the latest Mono.Data.Sqlite](https://developer.xamarin.com/releases/android/xamarin.android_6/xamarin.android_6.1/), but I'm not sure how to configure SQLite.cs to use this custom library. Is it related to the connection string? Here is what I'm currently doing for Android:

    var sqliteFilename = "my_database.db3";
    string libraryPath = Environment.GetFolderPath (Environment.SpecialFolder.Personal);
    var path = Path.Combine (libraryPath, sqliteFilename);
    var db = new SQLiteConnection(path);

Much appreciate the help!

**Comment by ericsink** [comment]
I don't have any experience with Mono.Data.Sqlite, but my first attempt at what you are trying to do would be to change LibraryPath in your copy of SQLite.cs from "sqlite3" to "sqlite3_xamarin".

Since your SQLite.cs is in a shared project, you'll need to use #if statements to make this change applicable only on Android.

**Comment by inshalirshad** [comment]
> I don't have any experience with Mono.Data.Sqlite, but my first attempt at what you are trying to do would be to change LibraryPath in your copy of SQLite.cs from "sqlite3" to "sqlite3_xamarin".
> 
> Since your SQLite.cs is in a shared project, you'll need to use #if statements to make this change applicable only on Android.

Can you explain how to put if statement and let it do only for android?

**Comment by ericsink** [comment]
C# can do conditional compilation like this:

    #if FOO
    // code in here will only be compiled when the symbol FOO 
    // was defined using an argument to the compiler
    #endif

See the following link for docs:

https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/preprocessor-directives/preprocessor-if

For Xamarin Android, the `FOO` symbol above should be `__ANDROID__`

**Comment by inshalirshad** [comment]
I have used SQLLite.cs as well as added nugut as described.. but still getting exception

Unhandled Exception:

System.DllNotFoundException: /system/lib64/libsqlite.so occurred

This app is working fine when i changed its target SDK to 23. But when i change it to 28 it give this error. I tried multiple devices. but the problem is still there for nougat and oreo... I have attached the images for more elaboration. I have been stuck on it for all the day to solve it but still didn't got any outcome. Please have a review and suggest me something on it.
![w1](https://user-images.githubusercontent.com/27137921/46031934-b4672c80-c113-11e8-8837-61fd7ade9a64.PNG)
![w2](https://user-images.githubusercontent.com/27137921/46031935-b4ffc300-c113-11e8-98ea-0ef14444d29e.PNG)
![w3](https://user-images.githubusercontent.com/27137921/46031936-b4ffc300-c113-11e8-8156-cfdf797a43c7.PNG)
![w4](https://user-images.githubusercontent.com/27137921/46031937-b5985980-c113-11e8-9e65-6e7a121073c4.PNG)

**Comment by ericsink** [comment]
I can't tell how much of the previous history of this issue's comments are applicable to your situation.

For example, are you trying to use Mono.Data.Sqlite?  I assumed you were, since your first question referenced the `#if` comment, but I don't see that pkg in your references.

From your screen shot, it looks like you have SQLite.cs *and* the sqlite-net pkg, but you only need one or the other.  Usually, you should use the nuget pkg unless you have a specific reason to use SQLite.cs.

If you are using SQLite.cs, you need to define `USE_SQLITEPCL_RAW`.
