### ISSUE TITLE
Inheritance problem

### ISSUE THREAD

**Issue by nosuch** [praeclarum/sqlite-net#507]
I might be doing something wrong. But with my code first db, it seems that the attributes of the base class are ignored. Please see the following code.

   ```
 public class Entity<T>
    {
        [PrimaryKey, AutoIncrement, Indexed]
        public T Id { get; set; }
        public Entity()
        {
            Id = default(T);
        }
    }
```

```
    public class Person : Entity<int>
    {
        [Indexed, NotNull, MaxLength(50)]
        public string FirstName { get; set; }
        [Indexed, NotNull, MaxLength(50)]
        public string Surname { get; set; }
    }
```

But `CreateTable<Person>()` yields the following table to be created.

CREATE TABLE "Person"(
"FirstName" varchar(50) not null ,
"Surname" varchar(50) not null ,
"Id" integer )

I'm using the following package
```
<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="sqlite-net" version="1.0.8" targetFramework="monoandroid60" />
</packages>
```

**Comment by praeclarum** [comment]
Unfortunately that nuget package is very old but I cannot update it. Please switch to `sqlite-net-pcl`. If you must use source code, then grab it from github.

**Comment by CodingOctocat** [comment]
See:

https://github.com/praeclarum/sqlite-net/blob/5f72241035dd48f4305a7c811eba8e7c955e9840/src/SQLite.cs#L2639
