### ISSUE TITLE
UWP project failed to add sqlite-net from nuget.

### ISSUE THREAD

**Issue by SetoKaiba** [praeclarum/sqlite-net#514]
System.Net.Security 4.3.0 provides a compile-time reference assembly for System.Net.Security on UAP,Version=v10.0, but there is no run-time assembly compatible with win10-arm.
One or more packages are incompatible with UAP,Version=v10.0 (win10-arm).
System.Net.Security 4.3.0 provides a compile-time reference assembly for System.Net.Security on UAP,Version=v10.0, but there is no run-time assembly compatible with win10-arm-aot.
One or more packages are incompatible with UAP,Version=v10.0 (win10-arm-aot).
System.Net.Security 4.3.0 provides a compile-time reference assembly for System.Net.Security on UAP,Version=v10.0, but there is no run-time assembly compatible with win10-x64.
One or more packages are incompatible with UAP,Version=v10.0 (win10-x64).
System.Net.Security 4.3.0 provides a compile-time reference assembly for System.Net.Security on UAP,Version=v10.0, but there is no run-time assembly compatible with win10-x64-aot.
One or more packages are incompatible with UAP,Version=v10.0 (win10-x64-aot).
System.Net.Security 4.3.0 provides a compile-time reference assembly for System.Net.Security on UAP,Version=v10.0, but there is no run-time assembly compatible with win10-x86.
One or more packages are incompatible with UAP,Version=v10.0 (win10-x86).
System.Net.Security 4.3.0 provides a compile-time reference assembly for System.Net.Security on UAP,Version=v10.0, but there is no run-time assembly compatible with win10-x86-aot.
One or more packages are incompatible with UAP,Version=v10.0 (win10-x86-aot).

**Comment by ericsink** [comment]
Try updating the UWP package to version 5.2.2.

**Comment by SetoKaiba** [comment]
It's 5.2.2.

**Comment by ericsink** [comment]
Is NetStandard.Library at 1.6.1 ?

**Comment by SetoKaiba** [comment]
Didn't installed NetStandard.Library in the UWP project. But the one in Portable project is 1.6.1.
I tried to create a new project. sqlite-net-pcl is successfully added. But I didn't change the portable project to .net standard yet.

**Comment by SetoKaiba** [comment]
Maybe my project is corrupted before. It's successfully added even I switched the portable project to .net standard.

**Comment by praeclarum** [comment]
It sounds like you got this working!
