### ISSUE TITLE
Cannot use together with "SQLitePCLRaw.bundle_e_sqlite3 "

### ISSUE THREAD

**Issue by gentledepp** [praeclarum/sqlite-net#519]
Hi!

In my xamarin android/ios application, I would like to use sqlitepcl-net with **SQLitePCLRaw.bundle_e_sqlite3**
As far as I know the only difference to **SQLitePCLRaw.bundle_green** is that is uses the latest sqlite version on iOS which is kinda what I want.

However, as sqlite-net seems to reference bundle_green, I get a compile error when calling 
`SQLitePCL.Batteries.Init()`
because the type "Batteries" is defined in both bundles.

We are using project.json by the way.

Any chance I can solve this?

(basically it should be possible, as you also support using **SQLitePCLRaw.bundle_sqlcipher**)

**Comment by ericsink** [comment]
Use Batteries_V2.Init instead.

**Comment by gentledepp** [comment]
Thanks for the response! 👍 
Any explanation for this _V2 thing?

**Comment by ericsink** [comment]
https://github.com/ericsink/SQLitePCL.raw/wiki/SQLitePCL.Batteries.Init

**Comment by gentledepp** [comment]
Thanks for the clarification!!

**Comment by ericsink** [comment]
Good point.  README updated.
