### ISSUE TITLE
Android N (Android 7)

### ISSUE THREAD

**Issue by lauraruggerilinea** [praeclarum/sqlite-net#521]
Support for Android N?

**Comment by ericsink** [comment]
Yes

**Comment by lauraruggerilinea** [comment]
I integrated the library but Android N "libmonosgen-32bit anauthorized access to system / lib / libsqlite Android 7"

**Comment by ericsink** [comment]
How did you integrate the library?

If you use the PCL package below, it provides support for Android N:

https://www.nuget.org/packages/sqlite-net-pcl

**Comment by lauraruggerilinea** [comment]
Yes now work :)

**Comment by manosgovind** [comment]
Hi Eric, 
I have integrated the library in my native app. I am getting the same issue with Android N. I have used the library in a shared project in my solution so that I couldnt get an update from the nuget. how can I solve the issue. Please help...

**Comment by ericsink** [comment]
@manosgovind  You say you "have integrated the library in my native app".  And it also sounds like you did not use the nuget package, so you must have simply added SQLite.cs into your project.  Is that correct?

**Comment by manosgovind** [comment]
Yes, Added SqLite.cs and SqLiteAsync.cs in my shared project.

**Comment by ericsink** [comment]
Your situation is tricky.  Without knowing more about your project structure, I can't be sure of the details, but I would suggest trying something like this:

1.  At the top of your SQLite.cs file, add `#define USE_SQLITEPCL_RAW`

2.  Also in SQLite.cs, find the line that contains `SQLitePCL.Batteries_V2.Init()` and remove it.

3.  For any library projects which reference the shared project which contains SQLite.cs, add the nuget package SQLitePCLRaw.core.

4.  In your app project, add the nuget package SQLitePCLRaw.bundle_e_sqlite3

5.  Also in the app project, wherever is the appropriate place to add app-level initialization, add the `SQLitePCL.Batteries_V2.Init()` call.

**Comment by manosgovind** [comment]
Thanks for the reply Eric, Please have a look on the attachment
![proj](https://cloud.githubusercontent.com/assets/28955658/26488573/95e5d31e-4221-11e7-9792-edc3205822b6.jpg)
, I hope this will help you to understand the project structure.

1) Ex.Android.Shared project contains the common functionalities which can be used in multiple places in the Mobile.Droid project app.

2) Ex.Mobile.Droid is the Main app project.

3) Ex.Mobile.shared is the shared project which contains the SQLite.cs and SQLiteAsync.cs. All the db call interactions are done through this.Both Mobile.Droid and Android.Shared have a reference to this project.

In future,I will have a solution folder for IOS and the plan is that the IOS app projects also use the same shared project for the DB interactions .

Also,
When I add "#define USE_SQLITEPCL_RAW" , I am getting missing assembly referrence error in the below lines in SQLite.cs

#elif USE_SQLITEPCL_RAW
using Sqlite3DatabaseHandle = SQLitePCL.sqlite3;
using Sqlite3Statement = SQLitePCL.sqlite3_stmt;
using Sqlite3 = SQLitePCL.raw;


Is there any way to avoid adding sqlite references in the app projects?

**Comment by ericsink** [comment]
The compiler errors when you define USE_SQLITEPCL_RAW indicate that you need to add a reference to the SQLitePCLRaw.core nuget package.  Because this is a shared project, you would need to add that reference to the actual library project(s) which references the shared project.

> Is there any way to avoid adding sqlite references in the app projects?

For Android N, no.  Android N does not allow apps to use the system SQLite library, so you are required to bundle your own instance of the native SQLite library with your app.  SQLitePCL.raw is designed to be one of the easier ways to accomplish this.

**Comment by manosgovind** [comment]
After adding all the reference and applying all the steps you suggested, I am getting an unhandled exception. 
Can you suggest a best way to handle the db interactions which is suitable for this kind of architecture. (common db layer for all the projects with in both IOS and Android solution folders)

Thanks

**Comment by praeclarum** [comment]
I suggest you put your data access layer in the same assembly (.NET Standard project) and reference that assembly from your app.
