### ISSUE TITLE
Safe To Update Dependency Libraries?

### ISSUE THREAD

**Issue by hvaughan3** [praeclarum/sqlite-net#540]
I am wondering it is safe to update all of the SQLite library dependencies or not? The libraries I am seeing updates for are listed below. Thank you.

**SQLitePCLRaw.bundle_green 1.1.2**
- to -> **SQLitePCLRaw.bundle_green 1.1.5**

**SQLitePCLRaw.core 1.1.2**
 - to -> **SQLitePCLRaw.core 1.1.5**

**SQLitePCLRaw.lib.e_sqlite3.android 1.1.2**
 - to -> **SQLitePCLRaw.lib.e_sqlite3.android 1.1.5**

**SQLitePCLRaw.provider.e_sqlite3.android 1.1.2**
 - to -> **SQLitePCLRaw.provider.e_sqlite3.android 1.1.5**

**SQLitePCLRaw.provider.sqlite3.ios_unified 1.1.2**
 - to -> **SQLitePCLRaw.provider.sqlite3.ios_unified 1.1.5**

**Comment by ericsink** [comment]
Yes, updating all of those should be safe.

**Comment by hvaughan3** [comment]
Awesome, thank you!
