### ISSUE TITLE
CreateTableAsync Result Doesn't say if Created or Modified Table

### ISSUE THREAD

**Issue by maxmin88** [praeclarum/sqlite-net#541]
Perhaps I am missing something.

I used the CreateTableAsync<>().ContinueWithResults(results) =>{...}

I had expected the CreateTableResults to have some kind of field for whether a new table was created or a table was modified. I was planning to use this to populate some generic data if it is a new table.  

And actually the example shown:
var conn = new SQLiteAsyncConnection("foofoo");
conn.CreateTableAsync<Stock>().ContinueWith((results) =>
{
    Debug.WriteLine("Table created!");
});

Writes "Table Created" every time, even if the table exists.

Am I missing something?

**Comment by JakubHolovsky** [comment]
You can try this: https://forums.xamarin.com/discussion/1460/sqlite-how-to-check-if-table-exists

**Comment by praeclarum** [comment]
I will look into this - I agree the result should indicate whether create table was called.
