### ISSUE TITLE
SQLite.cs not working with Android N

### ISSUE THREAD

**Issue by stephanemathis** [praeclarum/sqlite-net#542]
I was using the nugget package to include SQLite in my app, but I needed to handle non-integer enum and nullable enums, so I decided to remove the package and include the SQLite.cs source code.

I've got everything working except when I run my app on Android N, I get this exception : 

`System.DllNotFoundException: /system/lib64/libsqlite.so`

I have no idea what to do to fix that. 
I tried to include your nugget package, but still have an SQLite.cs file but with a different namespace, but it does not work. I even tried to add 'SQLitePCL.Batteries_V2.Init();' without success.

Some help would be much appreciated.

**Comment by elpendor** [comment]
Same issue here. I'm aware there are packages for that but I need to use the Sqlite.cs class.

**Comment by ericsink** [comment]
It should be possible to get this working by adding a define for `USE_SQLITEPCL_RAW` and then add a SQLitePCL.raw bundle package.

**Comment by stephanemathis** [comment]
Thank you very much for your response, I've got it working !

I didn't use the `SQLitePCL.raw` package because it would not compile (because `Batteries_V2` is not in that package).

I ended up doing the fallowing : 
- add at the top of my SQLite.cs file :
```
#if __ANDROID__
#define USE_SQLITEPCL_RAW
#endif
```
The condition is  there because the file is located in a Shared Project (Xamarin)
- add the package `SQLitePCLRaw.bundle_green` to the Android project


That's it.
Thank you again, because after a day searching the solution, without your help **Eric**, I would be **sink**ing in depression...

**Comment by ericsink** [comment]
Yeah, SQLitePCLRaw.bundle_green is what I meant.

Glad it worked.
