### ISSUE TITLE
VISUAL STUDIO ENTERPRISE FOR MAC ERROR

### ISSUE THREAD

**Issue by clbemre** [praeclarum/sqlite-net#543]
Could not install package 'System.Runtime.InteropServices.RuntimeInformation 4.0.0'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile111', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

**Comment by JakubHolovsky** [comment]
@clbemre it seems that you will have to change your PCL profile. Can't see in documentation which profiles are supported but for example on our project we use Profile44.

**Comment by brunoracosta** [comment]
I am with this problem too. 

@JakubHolovsky How do I do this???

**Comment by brunoracosta** [comment]
I discovery how it's done:

1. Double click in project name
2. Build > General > Target Framework

 I put **PCL 4.6 - Profile44** and works fine

**Comment by brunoracosta** [comment]
Now I have this error:

Could not install package 'System.Runtime.InteropServices.RuntimeInformation 4.0.0'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.6,Profile=Profile44', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

**Comment by praeclarum** [comment]
Sorry for the trouble everyone, I'm investigating...

**Comment by praeclarum** [comment]
@brunoracosta I have tested against the latest version and everything is working with the new `v1.4`.

Please try with `v1.4` - it should be fixed. Please open a new issue if it is not.
