### ISSUE TITLE
System.NotSupportedException: Cannot compile: Parameter

### ISSUE THREAD

**Issue by welshrat** [praeclarum/sqlite-net#552]
Latest Xamarin Compiler causes this issue, I have raised with Xamarin but also raising here in the hope someone can fix.

https://bugzilla.xamarin.com/show_bug.cgi?id=56789

**Comment by welshrat** [comment]
Sorry to chase this but is this issue being looked into as Xamarin are pointing to an issue with the package and not their compiler ?

**Comment by welshrat** [comment]
Hi There, just been having a nosey at the code and changing line 3361 from

if (mem.Expression != null && mem.Expression.NodeType == Expression.Parameter)

To
if (mem.Expression != null && (mem.Expression.NodeType == Expression.Parameter || mem.Expression.NodeType == Expression.Convert))

Seems to have fixed it for me, if this doesnt break anything else can we ammend the package ?

**Comment by gralov** [comment]
I'm, having same issue using sqlite-net 1.3.3. in Xamarin for android

**Comment by welshrat** [comment]
That fix above if you compile the package locally has fixed the issue for me, hoping for confirmation of fix here but in the meantime it has resolved it for me.

**Comment by gralov** [comment]
@welshrat can't find this on row 3361, I do however find it on row 3034 in version 1.3.3. Is this the row you mean? https://github.com/praeclarum/sqlite-net/blob/v1.3.3/src/SQLite.cs#L3034

**Comment by welshrat** [comment]
Yes sorry, I have no idea why I put line 3361, that is indeed the correct line, possibly when I first took a copy my editor may have changed the line numbers.

**Comment by welshrat** [comment]
I simply compile the package locally and added it as a nuget package.

**Comment by gralov** [comment]
@welshrat will try to do this as well for now until a propper fix has been amended

**Comment by gralov** [comment]
@welshrat I've tried this solution and it solved the problem for me as well.
There was some fault in the code change you suggested with enums that are compared, here's the correct replacement:
Replace
if (mem.Expression!=null && mem.Expression.NodeType == ExpressionType.Parameter)
with
if (mem.Expression != null && (mem.Expression.NodeType == ExpressionType.Parameter || mem.Expression.NodeType == ExpressionType.Convert))
At row 3034 in SQLite.cs (https://github.com/praeclarum/sqlite-net/blob/v1.3.3/src/SQLite.cs#L3034)

**Comment by welshrat** [comment]
Hi gralov, Yes I think I must have been in a rush to post as that is the exact change I made, The issue had been a major concern for me and hence I had spent a good afternoon finding a solution and then obviously not checked my post, thanks for correcting me though :-)

**Comment by praeclarum** [comment]
Hi everyone, sorry for the trouble. I'm looking at this now...

**Comment by welshrat77** [comment]
I have just updated to the new package and I am still getting the same issue, I have had to revert to the fix I originally posted, should I be doing anything else in order to get the new package to work

**Comment by gertclaassen** [comment]
Hi, has this fix been scheduled for release or is it already part of a released NuGet package? We are running into a similar problem and would like to make use of your fix. We tried building and hosting it ourselves but had some problems with PCL profiles when we installed our NuGet.

**Comment by welshrat77** [comment]
gertclaassen I am still getting the same issue with the new package so I am still having to revert to my original fix
