### ISSUE TITLE
Don't know about System.Collections.Generic.List

### ISSUE THREAD

**Issue by AeonDave** [praeclarum/sqlite-net#553]
After updating the library from 1.2.0 to 1.3.3
i got this error.

Don't know about System.Collections.Generic.List`1[Subcategory]

if i rollback to 1.2.0 it works.

```
Connection.CreateTable<Category>();

------

public class Category
	{
		[PrimaryKey]
		public int id { get; set; }
		public string name { get; set; }
		public string description { get; set; }
		public bool active { get; set; }

		[OneToMany(CascadeOperations = CascadeOperation.All)]
		public List<Subcategory> subcategories { get; set; }
	}

public class Subcategory
	{
		[PrimaryKey]
		public int id { get; set; }
		public string name { get; set; }
		public string description { get; set; }
		public bool active { get; set; }

		[ForeignKey(typeof(Category))]
		public int category_id { get; set; }
	}
```

thank you

**Comment by SoyPan** [comment]
I have the same issue, the latest version I got working is 1.3.1

**Comment by wegascee** [comment]
Try to uninstall all SQL NuGet packages, then install `SQLiteNetExtensions`. All required dependencies will be installed with it.

My problem was that I had the wrong sqlite-net library installed.

**Comment by Szymaniuk** [comment]
I got exact same issue, after updating 1.2.0 to 1.3.3. And after that, also investigated, that last "working" version (in this case) is 1.3.2.
I've tried to uninstall all sql nugets, and start installation from SQLiteNetExtensionsAsync, but issue still occurs at 1.3.3 (and NOT at 1.3.2, where it's working fine).

**Comment by praeclarum** [comment]
I'm investigating, sorry for the trouble.

**Comment by praeclarum** [comment]
This has been fixed in https://github.com/praeclarum/sqlite-net/commit/05e71dc1b9a64d7c539947a967be6c501d711310
