### ISSUE TITLE
After delete, I want to know about the state of Id(PrimaryKey, AutoIncrement)

### ISSUE THREAD

**Issue by lch32111** [praeclarum/sqlite-net#554]
I have this DB data structure

```
[Table("ToDoList")]
    public class ToDoList
    {
        [PrimaryKey, AutoIncrement, Column("Id")]
        public int Id { get; set; }

        [MaxLength(50), Column("DateTime")]
        public string Datetime { get; set; }

        [MaxLength(50), Column("ToDo")]
        public string ToDo { get; set; }

        public ToDoList()
        {
            Datetime = "";
            ToDo = "";
        }

        public ToDoList(string DT, string list)
        {
            Datetime = DT;
            ToDo = list;
        }
    }
```

And my delete operation is

```
 public string RemoveTask(int id)
        {
            string dbPath = Path.Combine(Environment.GetFolderPath
                   (Environment.SpecialFolder.Personal), dbFilename);
            var db = new SQLiteConnection(dbPath);

            db.Delete<T>(id);
            return "Record Deleted...";
        }
```

After the method RemoveTask, I loaded the data from my data file. 

And I checked the Id which I deleted was 2. 
However, when I loaded all data from my file by this method, 

```
public T GetTaskById(int id)
        {
            string dbPath = Path.Combine(Environment.GetFolderPath
                   (Environment.SpecialFolder.Personal), dbFilename);
            var db = new SQLiteConnection(dbPath);

            var item = db.Get<T>(id);
            // return item.Id + " " + item.active + " " + item.Time + " " + item.Place;
            return item;
        }
```

I got a System.InvalidOperationException: Sequence contains no elements from Id 2.
So, I understood that after deleting an record in the table, the Id of all records will not change.
Is that right?

I originally thought that after deleting, the Id of all records should be adjusted. But It doesn't

So, In this case, How can I adjust the id of all data?

**Comment by lch32111** [comment]
After one day, I just realized i need update query statement.
So, I did 
```
string name = typeof(T).Name;
 db.Query<T>("Update " + name + " SET Id = Id - 1");
```

However, This query does not decrease the number of Id. So, I just deleted all records.
and i inserted renewed data into table. This fulfilled what i want.

Yes. This is very stupid, because if the quantity of the data is very large, it cause much time to insert.
However, I can't help using that. and my case is on the simple android application. So, I guess It will not harm the peroformance.

So, If there is anyone who knows why the query statement is not working, let me know about it.

**Comment by DanielGilbert** [comment]
If you want to handle the Id's "your way", and not how SQLite does, then you shouldn't use autoinc.

Normally, if you used an Id once, and delete the record, you don't want to reuse it. It's simply gone. And you don't want to adjust the id's of existing records either, because that means the database must know which foreign keys exist, so that the foreign keys can also be adjusted.

That's why you normally don't do that. What are you trying to achieve? Maybe there is another way round.

**Comment by lch32111** [comment]
@DanielGilbert 
The reason why I want to edit the id of records is that My code, loading data from db, is like below.

```
public void LoadData()
        {
            if (todolistDB.isRecordEmpty())
            {

            }
            else
            {
                for (int i = 1; i <= todolistDB.GetRecordSize(); ++i)
                {
                    var item = todolistDB.GetTaskById(i);
                    itemToDoList.Add(item);
                    itemToDoList.Sort( (a,b) => { return a.Datetime.CompareTo(b.Datetime); });
                }
            }
        }
```

So, I just use the method 'GetTaskById' through the 'for' statement. 
If I deleted one record once and want to load records from db, this code will make an error.
Because the id which i deleted is not in record. 
So, Is there any way that I can get records from db with this error done and autoinc of id used?

**Comment by DanielGilbert** [comment]
Sure, just do a foreach on the table itself. That should work:

(I'm assuming that todolistDB is the SQLiteConnection object)
```
var query = todolistDB.Table<ToDoList>();

foreach (var todoItem in query)
	Debug.WriteLine("ToDo: " + todoItem.ToDo);
 ```

**Comment by lch32111** [comment]
@DanielGilbert 

I really appreciate you! 

I'm not used to C# language. So, I don't have the idea of foreach at all.

Thanks bro! Have a good day.
