### ISSUE TITLE
Includes and Association Insert

### ISSUE THREAD

**Issue by mpgalo** [praeclarum/sqlite-net#555]
Hi.

I got some questions about sqlite-net pcl:

1-Is there any way i can get a entity and your child associations (lists) filled, like EF 'Includes' do?

2-Is there any way i can auto insert the child associations of a entity (lists) or did i have to manually insert one by one in a transaction?

Thank You

**Comment by praeclarum** [comment]
Foreign keys don't have direct support, sorry. Some day...

**Comment by praeclarum** [comment]
I would like to merge in some functionality with SQLiteNetExtensions

**Comment by mpgalo** [comment]
I believe this issue is no longer relevan
