### ISSUE TITLE
How to handle schema change

### ISSUE THREAD

**Issue by alberk8** [praeclarum/sqlite-net#560]
Hi,

I come from using Sqlite.Net PCL (https://github.com/oysteinkrog/SQLite.Net-PCL) which handle changes to schema automatically.  How is this sqlite-net handling it,  What I get now is that I get an exception.  For example change from 

```
public class TestTable
    {
        [PrimaryKey, AutoIncrement]
        public int? key_id { get; set; }
        public string name { get; set; }
        public float quantity { get; set; }
    public  TestTable(){}
   }
```

TO

```
public class TestTable
    {
        [PrimaryKey, AutoIncrement]
        public int? key_id { get; set; }
        public string name { get; set; }
        public float quantity { get; set; }

        public float price {get; set;}

    public  TestTable(){}
   }
```

**Comment by ianjonesau** [comment]
Are you calling the CreateTable method once you establish the connection?
e.g. dbCnn.CreateTable<TestTable>();
This 'refreshes' the column definitions, and should add the 'price' column for you.

**Comment by alberk8** [comment]
After spending some hours doing trail and error, process of elimination, I think I have manage to get this working.

Go to VS Menu -> Project -> Appname Properties -> Android Options -> Linker - Skip linking assemblies 
and paste in the following

SQLite-net;SQLitePCLRaw.batteries_v2;SQLitePCLRaw.core

Go to VS Menu Build -> Clean Solution.

Build and Deploy.

**Comment by praeclarum** [comment]
Ah yes, you should not link your own assemblies. Alternatively you can use the `[Preserve]` attribute.
