### ISSUE TITLE
Win8.1 generates Unable to load DLL 'e_sqlite3': The specified module could not be found. (Exception from HRESULT: 0x8007007E)

### ISSUE THREAD

**Issue by uwantfries** [praeclarum/sqlite-net#562]
Repro: Create a new windows 8.1 project (VS2015 Win10x64)
Add the nuget.
Add the following code MainPage.xaml.cs to exercise SQLite

```
namespace Win81SQL
{
    public class Stock
    {
        [PrimaryKey, AutoIncrement]
        public int Id { get; set; }
        [MaxLength(8)]
        public string Symbol { get; set; }
    }


    /// <summary>
    /// An empty page that can be used on its own or navigated to within a Frame.
    /// </summary>
    public sealed partial class MainPage : Page
    {
        public MainPage()
        {
            this.InitializeComponent();

            var path = Path.Combine(ApplicationData.Current.LocalFolder.Path, "foofoo");
            var db = new SQLiteConnection(path);

            db.CreateTable<Stock>();

            MainPage.AddStock(db, "Appl");

            var query = db.Table<Stock>().Where(v => v.Symbol.StartsWith("A"));

            foreach (var stock in query)
                Debug.WriteLine("Stock: " + stock.Symbol);


        }

        public static void AddStock(SQLiteConnection db, string symbol)
        {
            var s = db.Insert(new Stock()
            {
                Symbol = symbol
            });
            //Console.WriteLine("{0} == {1}", s.Symbol, s.Id);
        }

    }
}

```

**Comment by praeclarum** [comment]
@ericsink Are there any known issues with Win 8.1?

**Comment by ericsink** [comment]
I hadn't noticed this one yet.  The problem is *probably* needing to add the reference to the Visual C++ runtime lib.  That's the only common thing that happens with Win 8.1.

**Comment by uwantfries** [comment]
Thank you for looking into this for me.
Is this something I can work around in my code or is a change to the nuget package required to fix this?

**Comment by ericsink** [comment]
Sorry, I should have explained more.

You probably just need to Add a reference to the Visual C++ extension SDK.  Right Click on the project.  Choose Add, then Reference.  Look under Windows / Extensions.  The item you want is Microsoft Visual C++ 2013 Runtime package for Windows.

**Comment by uwantfries** [comment]
Hi,
I had tried that (based on some random blog page I have long since lost). It seemed to make no difference (I also tried setting the filename to ":memory:" because I was not sure of filesystem differences)

Attached is a screenshot of what I currently have. VCLibs broken reference seems to be appear after closing and re-opening VS2015

![sql](https://user-images.githubusercontent.com/9169211/27482917-29795948-581b-11e7-849c-894b60b37b2b.PNG)

**Comment by ericsink** [comment]
Hmmm.  I just did the following steps:

1.  Open Visual Studio 2015
2.  New Project, Windows 8.1 blank app
3.  Add sqlite-net-pcl nuget package, version 1.3.3
4.  Copy and paste your code from above into MainPage.xaml.cs.
5.  Add using SQLite, using Windows.Storage, and using System.Diagnostics at the top of MainPage.xaml.cs
6.  Run the app.  It fails with the error you describe above.
7.  Add the reference to "Microsoft Visual C++ 2013 Runtime package for Windows"
8.  Build the app.  The build fails because it is Any CPU.
9.  Change the target to x86 and run the app.  It works, and your diagnostic message is printed.

**Comment by uwantfries** [comment]
Interesting. The one that did not work was done using the same steps (but probably different order). Another test following your steps exactly worked. Taking that working project and adding it to a different solution and it stops working? Could there be any settings at the solution level that mess it up?

**Comment by ericsink** [comment]
"Could there be any settings at the solution level that mess it up?"

Nothing I can think of.  Except perhaps the contents of the nuget packages directory.  If you clear the packages and reload them all, does it work?

**Comment by praeclarum** [comment]
Glad this got worked out!
