### ISSUE TITLE
DllImport error loading library './libe_sqlite3': 'dlopen failed

### ISSUE THREAD

**Issue by SSElliott** [praeclarum/sqlite-net#563]
This may be a duplicate off a number of number of existing issues but I cannot  Open a SQLite DB with out getting an error. All I get is the following message shown in the stack below. 

I have tried all of the other suggestions but nothing works at all.

**Stack Trace**
06-18 15:42:12.995 D/Mono    ( 7451): Assembly Ref addref SQLite-net[0xb42dcbe0] -> System.Threading[0x9f159880]: 4
06-18 15:42:12.997 D/Mono    ( 7451): Assembly Ref addref SQLite-net[0xb42dcbe0] -> SQLitePCLRaw.batteries_v2[0xb42dcca0]: 2
06-18 15:42:12.997 D/Mono    ( 7451): Assembly Ref addref SQLitePCLRaw.batteries_v2[0xb42dcca0] -> mscorlib[0xb40f1c40]: 44
06-18 15:42:12.997 D/Mono    ( 7451): Assembly Ref addref SQLitePCLRaw.batteries_v2[0xb42dcca0] -> SQLitePCLRaw.provider.e_sqlite3[0xb42dcdc0]: 2
06-18 15:42:12.997 D/Mono    ( 7451): Assembly Ref addref SQLitePCLRaw.provider.e_sqlite3[0xb42dcdc0] -> mscorlib[0xb40f1c40]: 45
06-18 15:42:12.997 D/Mono    ( 7451): Assembly Ref addref SQLitePCLRaw.provider.e_sqlite3[0xb42dcdc0] -> SQLitePCLRaw.core[0xb42dcd00]: 3
06-18 15:42:12.999 D/Mono    ( 7451): Assembly Ref addref SQLitePCLRaw.batteries_v2[0xb42dcca0] -> SQLitePCLRaw.core[0xb42dcd00]: 4
06-18 15:42:13.001 D/Mono    ( 7451): DllImport attempting to load: 'e_sqlite3'.
06-18 15:42:13.001 D/Mono    ( 7451): DllImport error loading library './libe_sqlite3': 'dlopen failed: library "/data/app/Pirana.Droid-1/lib/x86/./libe_sqlite3" not found'.
06-18 15:42:13.002 D/Mono    ( 7451): DllImport loaded library './libe_sqlite3.so'.
06-18 15:42:13.002 D/Mono    ( 7451): DllImport searching in: 'e_sqlite3' ('./libe_sqlite3.so').
06-18 15:42:13.002 D/Mono    ( 7451): Searching for 'sqlite3_libversion_number'.
06-18 15:42:13.010 D/Mono    ( 7451): DllImport searching in: 'e_sqlite3' ('./libe_sqlite3.so').
06-18 15:42:13.010 D/Mono    ( 7451): Searching for 'sqlite3_open_v2'.
06-18 15:42:13.024 D/Mono    ( 7451): [0x9e084580] hill climbing, change max number of threads 2

I have two projects, one a PCL and the other an Android One targeting Android 6. The PCL project targets  net 4.5.1, Win 8.1, Android iOS, iOS classic and Mac.

**SQLite Android Project Packages**
 package id="sqlite-net-pcl" version="1.3.3" targetFramework="monoandroid60" 
  package id="SQLitePCLRaw.bundle_green" version="1.1.5" targetFramework="monoandroid60" 
  package id="SQLitePCLRaw.core" version="1.1.5" targetFramework="monoandroid60" 
  package id="SQLitePCLRaw.lib.e_sqlite3.android" version="1.1.5" targetFramework="monoandroid60"
  package id="SQLitePCLRaw.provider.e_sqlite3.android" version="1.1.5" targetFramework="monoandroid60

**SQLite PCL Package Properties**

  package id="sqlite-net-pcl" version="1.3.3" targetFramework="portable46-net451+win81" 
  package id="SQLitePCLRaw.bundle_green" version="1.1.5" targetFramework="portable46-
  net451+win81"
  package id="SQLitePCLRaw.core" version="1.1.5" targetFramework="portable46-net451+win81" 

I cannot see what is wrong or missing, so I desperation I am submitting it here to see if I have missed something. 

Kind regards

Steven

**Comment by ericsink** [comment]
As long as your Android project is an app project and not an Android library project, I don't see an obvious problem here.

So the first thing I would do is check to see if libe_sqlite3.so is actually making it into the apk.  Look in the build output of your android app.  Make sure it's there.  Find the apk itself, unzip it, and see if it's there.

If it's not there, then we need to figure out why, and it's a build issue.

If it is there, then we need to figure out why it fails to load, and it's something weirder.

**Comment by SSElliott** [comment]
Hi Eric

Thank you for your reply. I have already checked it is in there. This is really confusing me. 

![image](https://user-images.githubusercontent.com/29478656/27261880-e5269e8e-5443-11e7-9807-0ad50b250432.png)

**Comment by SSElliott** [comment]
I should add I am using MVVMCross 5 but I would imagine this should have no  bearing on this.

**Comment by ericsink** [comment]
Hmmm. Maybe that error line is a red herring. I've seen cases before where that line appears but then the load actually succeeds.

Suppose you ignore that line. What other symptoms of a problem do you see?

**Comment by SSElliott** [comment]
The project bombs out with an Unhandled Exception.

**Comment by SSElliott** [comment]
More specifically it cannot Open the Database when I try to create  table.

**Comment by ericsink** [comment]
I think that's the real error. Why would SQLite's open function return an error? Where is the error code or message? Are there more details on that exception? Does your app have permission to write the file at the path you have specified? Does the file already exist, or not? Etc.

**Comment by SSElliott** [comment]
There is no other error reported in debug window that is reported. You can see where it go to in the bottom right hand corner of this picture.

![image](https://user-images.githubusercontent.com/29478656/27262310-c4459c8a-544b-11e7-83cc-5be25137d386.png)

The permisions are......

	<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
	<uses-permission android:name="android.permission.CAMERA" />
	<uses-permission android:name="android.permission.INTERNET" />
	<uses-permission android:name="android.permission.NFC" />
	<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
	<uses-permission android:name="android.permission.FLASHLIGHT" />
	<uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />

Am I missing something. Before I upgraded all my SQLITE packages I did not have a problem before.

Still really confused.

**Comment by ericsink** [comment]
So you upgraded and then it started failing? What versions were you using before?

**Comment by ericsink** [comment]
You're looking at the debug output. You need the exception details. Maybe look in locals and see if it's there. Or put in a try catch and set a break point in the catch and look at the exception object that got thrown.

**Comment by SSElliott** [comment]
There is not a lot of helpful information there.

![image](https://user-images.githubusercontent.com/29478656/27262547-a4e162b6-5450-11e7-8f38-78612aab3f75.png)


![image](https://user-images.githubusercontent.com/29478656/27262549-cc2f3f14-5450-11e7-95b5-74f575f9040f.png)

**Comment by SSElliott** [comment]
Steven

**Comment by ericsink** [comment]
Hmmm. Try changing the file name from "Test" to ":memory:" (an in-memory db instead of a file) and see what happens.  I'm still curious about whether this is file system issues or native code or what.

**Comment by ericsink** [comment]
Closed? So what was it?

**Comment by SSElliott** [comment]
Sorry I clicked the wrong button. I will try your suggestion

**Comment by SSElliott** [comment]
Setting it to :memory: works. Which suggests it has something to do with the file system.

**Comment by ericsink** [comment]
Cool. So the dlopen error message isn't real.

Now perhaps change the file name to something else, like "test8675309". Is the problem with a specific file, or does it happen with any file?

**Comment by SSElliott** [comment]
I tried "thisisasimpletest" but it still had the same affect. It happens with any file name.

**Comment by ericsink** [comment]
So, what directory is being used when you give a plain file name without a path? Is your app have able to write to that directory? Try using System.IO calls to just create a file. Does it work?

**Comment by SSElliott** [comment]
Any System.IO functions failed with an Unauthorized message (such as a simple create file). So what happens if I do not specify a path, where does the db reside by default?

**Comment by SSElliott** [comment]
A little progress 
  var path = System.Environment.GetFolderPath(System.Environment.SpecialFolder.Personal);
            path = Path.Combine(path,"pbcare.db3");

  SQLiteConnection con = new SQLiteConnection(path);
            con.CreateTable<Shire.Repository.WorkOrder>();

in the android project works. However I need this in the PCL and  I cannot specify the enviroment variables in a PCL.

Steven

**Comment by ericsink** [comment]
I never do file IO on a mobile device without specifying a path.

For the PCL issue, you can do the path stuff in platform code and pass it in to the PCL.  Or try a library like PCLStorage, which I'm using for one of my projects.

**Comment by praeclarum** [comment]
@SSElliott I advice you to always use absolute paths - especially with critical database files. You should put this path into a config variable somewhere. sqlite-net runs on too many platforms to make guesses about where to put your files.

**Comment by SSElliott** [comment]
Point taken. I have adjusted my code accordingly. I appreciate the help and assistance provided (especially by Eric). Many thanks, and I am happy for this to be closed. 
Kind regards

Steven
