### ISSUE TITLE
Could it use SQLite 1.0.105.2 ?

### ISSUE THREAD

**Issue by unluckykc** [praeclarum/sqlite-net#564]
Hello, I am experiencing some issues due to multiple versions of the same DLL on my computer. I needed 1.0.105.2 to make VS 2015 understand how to add a SQLite ADO.NET Model from the interface, but now I get an error when I try to add it to my prohect because it cannot cast a 1.0.101.0 to a 1.0.105.2....
I am so desesperate, SQL Server Embedded CE won't work either :(

**Comment by ericsink** [comment]
You are using System.Data.SQLite.  Using sqlite-net with that will be ... difficult.  I would pick one or the other.

**Comment by unluckykc** [comment]
Thank you for your quick answer. You are right, I have both installed because I followed a tutorial, which partially worked, and I discovered this package through stackoverflow on a thread where someone was stuck at the same point as me. 
It helped me because I could go further in the wizard, so I felt that I was going the right way. 
I will try only with your package and I hope it'll work ! Thanks
