### ISSUE TITLE
'sqlite3_bind_blob' does not have an implementation.

### ISSUE THREAD

**Issue by MartinRobins** [praeclarum/sqlite-net#567]
I am using SQLite-net-pcl 1.3.1 with a Xamarin Forms application. All works fine on Android, but if I run the UWP application on Windows Mobile 10 - on ARM - (10.0.14393.1066) I get the following exception:

> TypeInitializationException: The type initializer for 'SQLite.SQLiteConnection' threw an exception.
> 
> TypeLoadException: Method 'sqlite3_bind_blob' in type 'SQLitePCL.SQLite3Provider_e_sqlite3' from assembly 'SQLitePCLRaw.provider.e_sqlite3, Version=1.0.0.0, Culture=neutral, PublicKeyToken=9c301db686d0bd12' does not have an implementation.

Thoughts?

**Comment by ericsink** [comment]
Hmmm.  That seems bad.

At the moment I have no clue what this could be.  I use SQLitePCL.raw with UWP every day, and I've never seen this.

**Comment by MartinRobins** [comment]
Could it have anything to do with being on ARM?
Is there anything else I should be installing at the same time (I tried adding "Microsoft Visual C++ 2013 Runtime Package for Windows Universal" for example as another post seemed to indicate it might be required but it has made no difference)?

**Comment by ericsink** [comment]
ARM?  Yeah that's a good clue for the detective work.  Let me check something...

**Comment by MartinRobins** [comment]
Just to add some fuel, I can create a new SQLiteAsyncConnection("path") without an error, but the error is then thrown when I call SQLiteAsyncConnection.CreateTableAsync<T>.

**Comment by ericsink** [comment]
Well there is an arm build for UWP, so that's not the problem.

You're talking about UWP 10, not the previous universal windows app stuff for win 8.0/1, right?  Because you mentioned the "Microsoft Visual C++ 2013 Runtime Package for Windows Universal", that made me wonder.

**Comment by MartinRobins** [comment]
I have just tried running the same application on the desktop (Debug, Any CPU [ = x86 ]) and I am seeing exactly the same error. For my own sanity, I then ran it again on Android and - as previously - it runs fine.

**Comment by MartinRobins** [comment]
Definitely UWP and Windows 10; not Windows 8.0/8.1.
"Microsoft Visual C++ 2013 Runtime Package for Windows Universal" was a red herring I picked up from another post.

**Comment by ericsink** [comment]
"I have just tried running the same application on the desktop (Debug, Any CPU [ = x86 ]) and I am seeing exactly the same error."

Well that's helpful, so now we know it's not related to arm.  Does x64 give the same problem?

**Comment by MartinRobins** [comment]
Yes, same on x64 (Debug).

**Comment by MartinRobins** [comment]
Not sure if this helps, but the PCL and platform projects all have "sqlite-net-pcl" installed whilst "SQLitePCLRaw.bundle-green" is installed for the platform projects only (though not the UWP platform project) and "SQLitePCLRaw.core" is installed for all of the platform projects. Seems a little strange to me that the UWP platform project is not referencing the "SQLitePCLRaw.bundle-green" project like the others (or is it using a native implementation instead?)

**Comment by ericsink** [comment]
Well yeah, that looks wrong.  The UWP platform project should be referencing bundle_green, I would think.

**Comment by MartinRobins** [comment]
Just creating a new project now and adding "sqlite-net-pcl" to see what ends up installed and referenced...

**Comment by MartinRobins** [comment]
If I create a new project with Android/iOS and UWP and then install the latest "sqlite-net-pcl" (1.3.3) the "SQLitePCLRaw.bundle-green" is not installed to the UWP project, but neither is "SQLitePCLRaw.core".

None of the "SQLitePCLRaw.lib.e_sqlite3.*" packages are installed to UWP either.

**Comment by ericsink** [comment]
If you explicitly install bundle_green into the UWP project, what happens to that error?

**Comment by MartinRobins** [comment]
That fixes it.

Do not know if I am interpreting this correctly, but it looks to me as if there may be a problem with the "sqlite-net-pcl" nuget package as it is not installing the "SQLitePCLRaw.bundle-green" dependency for UWP?

Thanks for your help.

**Comment by ericsink** [comment]
Strictly speaking, no, that's not a problem with sqlite-net-pcl.  I'm pretty sure what you're seeing is a difference in the way Xamarin projects handle transitive nuget dependencies compared to UWP.  :-)

**Comment by MartinRobins** [comment]
Having never tried to create a nuget package, I would not know - hence my wording it above as a question :) 

Again, thanks for all of your help; I will make a mental note to ensure I always add the "SQLitePCLRaw.bundle-green" dependency in the future (or at least check to make sure it has been added).

Martin.

**Comment by ericsink** [comment]
Yeah, I was just trying to answer the question.  No criticism or emotion was implied.  Cheers.

**Comment by MartinRobins** [comment]
None taken.
