### ISSUE TITLE
Remove dependancy on SQLitePCLRaw.bundle_green

### ISSUE THREAD

**Issue by ndastur** [praeclarum/sqlite-net#568]
This seems to be an iOS only problem. But the dependency on SQLitePCLRaw.bundle_green means that even if I install SQLitePCLRaw.bundle_sqlcipher it is not substituted. We could just let users choose or even better if a dependency must be added add the cipher on. As without the PRAGMA key it will act just like an un-encrypted DB

**Comment by ericsink** [comment]
We discussed this back when the decision was made.  There are tradeoffs either way.

1.  If sqlite-net-pcl takes a dep on any bundle, then the most common use cases work with no extra steps, and there are tricks to deal with the other cases.

2.  If sqlite-net-pcl takes a dep on just SQLitePCLRaw.core, then everyone has to add a bundle and call an initialization method.  The SQLCipher case ends up being no more difficult than any other case.

Personally, I would probably have voted for (2).  But it's a close call, maybe 60/40 for me, and I understand the rationale for wanting *most* users to have a path that requires no extra steps.

cc @praeclarum in case he wants to chime in.

Anyway, I daresay it is too late to make the change now.  It would be a breaking change for lots of apps.

I would also strongly oppose the idea of switching the dependency from bundle_green to sqlcipher.  The sqlcipher builds are not as well maintained, and more difficult to maintain, and there are crypto export considerations, and the versions lag the bug fixes from the core sqlite team, etc.

I do sometimes wish we had two versions of the sqlite-net-pcl nuget package:  One the way it is now, and one that does not reference a bundle, to "let users choose" (which can be read as "force users to choose").

BTW, if you're interested in the "tricks" I mentioned above, start here:

https://github.com/ericsink/SQLitePCL.raw/wiki/How-to-use-SQLCipher-with-SQLite-net

**Comment by ericsink** [comment]
BTW, the Akavache project faced the same decision, and they chose a bundle as well.  The tradeoffs are somewhat different, as Akavache is not a way to access sqlite, but rather, a library which happens to use sqlite as part of its implementation.  Nonetheless, people on Akavache often want substitute sqlcipher as well.

Also, the Entity Framework Core team faced the same decision.  In their case, they decided to do two versions of their package (as I mentioned above), one which references a bundle, and one which does not.  Most users would choose the one with the bundle dependency, and all other cases (most of which are sqlcipher) would choose the one that requires (read: allows) extra steps.

**Comment by ndastur** [comment]
Thank you @ericsink . I see all those reasons.

I think I saw in a different post that for non-PCL i.e. shared projects the "best" way forward is to remove the sqlite-net-pcl package and just add the Sqlite.cs file with various mods. I think I'll try that.

Just as opinion but the different packages idea is probably the one I favour. In reality I don't think there are that many everyday choices for providers and so could even have a plain and a sql cipher package

**Comment by praeclarum** [comment]
@ndastur Perhaps I should start releasing a SQLCipher nuget? Since that seems to be the only "other" bundle people want.

**Comment by ndastur** [comment]
@praeclarum yeap, I'd agree with that. I suspect there aren't that many other use cases and will make up a very small percentage.

**Comment by ericsink** [comment]
Actually, although bundle_sqlcipher is in second place, I *do* regularly see requests for bundle_e_sqlite3 and custom builds and so on.  I've dealt with two such situations this week, and it's only Tuesday.

I'd love to see a second package, but my vote would be for the second one to *not* reference a bundle.  That's the easiest case for me when I'm trying to help people sort things out.  I can just explain how to add the bundle they want (to their app package) and add one line of Init() code.

**Comment by ndastur** [comment]
@ericsink @praeclarum  I'm happy with that. Potentially simpler to have just 2 packages. A sort of get you up and running one and a custom one that users need to think more about. If there is some more documentation in this Repo then I can't see a problem going forward

**Comment by ericsink** [comment]
To implement this, you need another build which is different from the `sqlite-net-pcl` build in two ways:

1.  Change the dependency from `SQLitePCLRaw.bundle_green` to `SQLitePCLRaw.core`

2.  Don't call `SQLitePCL.Batteries_V2.Init()`

And of course you'll need this new package to have a name other than `sqlite-net-pcl`.  Naming things is hard.  :-)

**Comment by praeclarum** [comment]
I hate the current naming, so let's stick with it ;-)

Perhaps `sqlite-net-core`?

**Comment by ericsink** [comment]
I like it, but anything with "net-core" in the name sounds like it's for .NET Core.  I frequently lament the diminished usefulness of the word core.

`sqlite-net-base` ?

`sqlite-net-foundation` ?

`sqlite-net-empty` ?

`sqlite-net-common` ?

`sqlite-net-lib` ?

**Comment by ndastur** [comment]
```sqlite-net-empty``` I think best describes it ... unless of course you could bring yourself to do ```sqlite-net-empty-so-you-need-to-add-another-package``` ;)

**Comment by ericsink** [comment]
`sqlite-net-hollow` ?

**Comment by praeclarum** [comment]
So far I like `base`, `common`, and `empty`. But I can't decide.

`sqlite-net-pro`?

`sqlite-net-configurable`?

`sqlite-net-unbundled`?

`sqlite-net-for-raw`?

**Comment by ericsink** [comment]
No strong opinion here.  Whatever it's called, I'm looking forward to having this package exist.  :-)

**Comment by ndastur** [comment]
My vote is for -empty. BUt like @ericsink I'm looking forward to it's existance

**Comment by praeclarum** [comment]
I went with `sqlite-net-base`

Version `1.5.147-beta` is up on nuget now. Would either of you mind giving it a spin to make sure I got it right?

Would either of you also mind peeking at https://github.com/praeclarum/sqlite-net/pull/596 to see if it looks right to you? Thanks!

**Comment by praeclarum** [comment]
Oops, I did mess up, try `1.5.151-beta`

**Comment by ericsink** [comment]
I just wrote a little test program against 1.5.151-beta, and it worked as expected.  And I looked at the diffs in #596, and they look fine.

LGTM

**Comment by praeclarum** [comment]
Great, it's in!

**Comment by ndastur** [comment]
Thank you @praeclarum. I have tested in my app and both ios and android now "load" sqlitecipher.

**Comment by SuhanKoh** [comment]
Is there documentation or example on how to use sqlite.net + sqlitepclraw.bundle_cipher + sqlcipher?

I have read this: https://github.com/ericsink/SQLitePCL.raw/wiki/How-to-use-SQLCipher-with-SQLite-net but as someone who only used sqlite.net, I don't see how to use the cipher underneath.

**Comment by ericsink** [comment]
https://www.zetetic.net/sqlcipher/sqlcipher-api/

**Comment by SuhanKoh** [comment]
@ericsink Thanks, I was supposed to use SQLite.Net-PCL, which is a fork of this repo.
