### ISSUE TITLE
There's no DeleteAllAsync

### ISSUE THREAD

**Issue by opcodewriter** [praeclarum/sqlite-net#571]
`SQLiteAsyncConnection` doesn't have a `DeleteAllAsync` only a `DeleteAsync`

**Comment by opcodewriter** [comment]
I found this: https://github.com/praeclarum/sqlite-net/pull/298
Someone implemented this 3 years ago! But the PR wasn't merged...

**Comment by praeclarum** [comment]
Sorry about that. Looking into it along with everything else with: https://github.com/praeclarum/sqlite-net/issues/480
