### ISSUE TITLE
SQLiteException: near "where": syntax error when updating table with only keys

### ISSUE THREAD

**Issue by Szymaniuk** [praeclarum/sqlite-net#572]
It's same issue, as here - https://github.com/oysteinkrog/SQLite.Net-PCL/issues/309
It behaves exactly the same.

Having such data model:
```
[Table(nameof(MyModel))]
public class MyModel
{
    [PrimaryKey]
    public string MyModelId { get; set; }
}
```

and trying to invoke **InsertOrUpdate** with some **MyModel** object(s), causes:
`SQLiteException: near "where": syntax error`

while adding additional table column even not using, is workarounding this issue:
```
[Table(nameof(MyModel))]
public class MyModel
{
    [PrimaryKey]
    public string MyModelId { get; set; }
    public string SomethingAdditional { get; set; }
}
```

**Comment by praeclarum** [comment]
Ahh good catch. I'll add a test for this.

Also, you don't need to do `[Table(nameof(MyModel))]` tables will be named with the type name by default.
