### ISSUE TITLE
Reflection problem on getting Table map

### ISSUE THREAD

**Issue by LuigiMaestrelli** [praeclarum/sqlite-net#573]
I have a base class to all my domain classes who access the database, and it looks like this:

```
public class MyBaseClass
{
        [PrimaryKey, Indexed]
        public virtual int Id { get; set; }
}
```

I some cases I need to override the Id property.

```
    public class MyClass: MyBaseClass
    {
        [PrimaryKey, AutoIncrement]
        public override int Id { get; set; }
        ....
    }
```

When the TableMapping is created, it is created with the Id column from the MyBaseClass and not from MyClass

**Comment by hvaughan3** [comment]
@praeclarum @LuigiMaestrelli  
Possibly related to my [post here](https://github.com/praeclarum/sqlite-net/issues/549#issuecomment-315137240)?

**Comment by praeclarum** [comment]
Darn. Adding a test for this now...

**Comment by praeclarum** [comment]
This was fixed in https://github.com/praeclarum/sqlite-net/commit/05e71dc1b9a64d7c539947a967be6c501d711310
