### ISSUE TITLE
Make it possible to enable trace for SQLiteAsyncConnection

### ISSUE THREAD

**Issue by wezzix** [praeclarum/sqlite-net#579]
Currently **Trace** and **Tracer** are properties of **SQLiteConnection** but these are not available when creating a **SQLiteAsyncConnection** instance. It seems to me anyone wanting to use async needs to roll her own or be without Trace ability when things go wrong. Or am I missing anything?
Please make it possible to **enable trace for SQLiteAsyncConnection**. Ideally there should be a factory we can override to control how connections are created.
Thanks

**Comment by praeclarum** [comment]
Ahhh, great idea!

**Comment by praeclarum** [comment]
The work will be done in https://github.com/praeclarum/sqlite-net/issues/480
