### ISSUE TITLE
Depedency Issue with Version 1.3.3 on Monodevelop 5.10

### ISSUE THREAD

**Issue by AndrewOfC** [praeclarum/sqlite-net#582]
Attempting to install Sqlite.net-pcl into a project produces the following error:

Adding sqlite-net-pcl...
Attempting to resolve dependency 'SQLitePCLRaw.bundle_green (≥ 1.1.5)'.
Downloading SQLitePCLRaw.bundle_green 1.1.5...
'SQLitePCLRaw.bundle_green' already has a dependency defined for 'SQLitePCLRaw.core'.

**Comment by ericsink** [comment]
That error message usually means you need to get a more up-to-date version of nuget.

**Comment by AndrewOfC** [comment]
I've brought nuget up to version 2.8.7 on Ubuntu 16.04 LTS.    With the following result:

andrew@andrew-VirtualBox:/opt/Store2$ nuget help
NuGet Version: 2.8.7.0

andrew@andrew-VirtualBox:/opt/Store2$ nuget install sqlite-net-pcl
Attempting to resolve dependency 'SQLitePCLRaw.bundle_green (≥ 1.1.5)'.
'SQLitePCLRaw.bundle_green' already has a dependency defined for 'SQLitePCLRaw.core'.

**Comment by ericsink** [comment]
Have you tried nuget 3.x?  or 4.x?

**Comment by praeclarum** [comment]
Sorry for the trouble but .NET's going through some growing pains and I've decided to push ahead with the new nugets. You'll need to update!
