### ISSUE TITLE
VACUUM command

### ISSUE THREAD

**Issue by jruetas** [praeclarum/sqlite-net#584]
I am trying to issue the "VACUUM" command on Android using the sqlite-net library and it does not appear to complete, return or throw an exception.  I have tried running the command directly from a connection object issuing the Execute() command and from a command object issuing the ExecuteNonQuery() command and both approaches never complete.  When I broke out of the ExecuteNonQuery() method it appears to be stuck at the line "r = SQLite3.Step (stmt);":

		public int ExecuteNonQuery ()
		{
			if (_conn.Trace) {
				Debug.WriteLine ("Executing: " + this);
			}
			
			var r = SQLite3.Result.OK;
			var stmt = Prepare ();
			r = SQLite3.Step (stmt);  // Running "VACUUM" command appears stuck here
			Finalize (stmt);
			if (r == SQLite3.Result.Done) {
				int rowsAffected = SQLite3.Changes (_conn.Handle);
				return rowsAffected;
			} else if (r == SQLite3.Result.Error) {
				string msg = SQLite3.GetErrmsg (_conn.Handle);
				throw SQLiteException.New (r, msg);
			}
			else if (r == SQLite3.Result.Constraint) {
				if (SQLite3.ExtendedErrCode (_conn.Handle) == SQLite3.ExtendedResult.ConstraintNotNull) {
					throw NotNullConstraintViolationException.New (r, SQLite3.GetErrmsg (_conn.Handle));
				}
			}

			throw SQLiteException.New(r, r.ToString());
		}

**Comment by praeclarum** [comment]
Ouch. I don't have any experience with the VACUUM command and will need to write a test for it.

Is it possible the command is just taking a long time to execute?

**Comment by jruetas** [comment]
Thanks for reply.  Actually you are correct.  We have large databases over 1 & 1/2 Gigs and growing that were created with auto-vacuum on.  When we eventually ran the vacuum command it took a long time to complete.  So the vacuum command does work but when done on large databases that are fragmented it takes a very long time.


Sent from Outlook<http://aka.ms/weboutlook>

________________________________

**Comment by praeclarum** [comment]
Yeah IO on these devices isn't lightning fast. :-)
