### ISSUE TITLE
How to configure sqlite-net-pcl to use a plug in a .Net Standard project?

### ISSUE THREAD

**Issue by BrianDT** [praeclarum/sqlite-net#589]
Currently in the process of transitioning a number of PCL projects that use Microsoft’s SQLitePCL nuget package into .Net Standard projects that use sqlite-net-pcl. One reason sqlite-net-pcl was chosen was the ability to work with SQLitePCLRaw.bundle_sqlcipher as a move to data encryption was also a goal.
If both the SQLitePCLRaw.bundle_sqlcipher and sqlite-net-pcl nuget packages are added to a .Net Standard project this ultimately results in the following error when the UWP solution is built.

Error		Payload contains two or more files with the same destination path 'SQLitePCLRaw.batteries_v2.dll'. Source files: 
C:\Users\xxxx\.nuget\packages\SQLitePCLRaw.bundle_green\1.1.5\lib\uap10.0\SQLitePCLRaw.batteries_v2.dll
C:\Users\xxxx\.nuget\packages\SQLitePCLRaw.bundle_sqlcipher\1.1.7\lib\portable-net45+netcore45+wpa81+MonoAndroid10+MonoTouch10+Xamarin.iOS10\SQLitePCLRaw.batteries_v2.dll	SQLiteCryptTestApp			

Is there any way of controlling the dependencies in the package referencing in the .Net Standard project .csproj file
  <ItemGroup>
    <PackageReference Include="sqlite-net-pcl" Version="1.4.118" />
    <PackageReference Include="SQLitePCLRaw.bundle_sqlcipher" Version="1.1.7" />
  </ItemGroup>

That would manage the source of the SQLitePCLRaw.batteries_v2.dll?

**Comment by ericsink** [comment]
I answered this same question over in the ericsink/SQLitePCL.raw#169

**Comment by praeclarum** [comment]
I updated the README again with the important line that you have to include it in your app project.
