### ISSUE TITLE
CreateTable does not create new columns

### ISSUE THREAD

**Issue by xleon** [praeclarum/sqlite-net#590]
This seams like a regresion bug. 
Adding a property to an existing entity won´t add the corresponding column, thus any insert query will fail with "No such column" error

**Comment by praeclarum** [comment]
I just added a specific test but am not seeing any problems with migration.

Can you provide an example that's not working?

**Comment by xleon** [comment]
Yeah, I need some time to isolate the issue from my project

**Comment by kyluke** [comment]
Hey, I am experiencing the same thing. CreateTableAsync does not create new columns.

**Comment by LuigiMaestrelli** [comment]
Maybe it is related to this issue: https://github.com/praeclarum/sqlite-net/issues/461
It was fixed a few days ago.

**Comment by xleon** [comment]
It looks like the same issue. Is #461 available in a nuget?

**Comment by LuigiMaestrelli** [comment]
I don't think so.
The last release was 12 days ago. And the fix was 6 days ago.

**Comment by xleon** [comment]
I didn´t test it, but I think the test @praeclarum wrote for this issue is not failing due to #461 fix. This issue may be just a duplicate.

**Comment by praeclarum** [comment]
Yeah I assume the #461 fix will fix this, was just looking for confirmation.

Current releases are going to **1.5.xxx-beta** and you could grab one of those.

**Comment by xleon** [comment]
@praeclarum Awesome. No need to say your library is pretty handy for tons of devs. Thank you.

**Comment by duzenko** [comment]
Is this still in beta? When can we expect it in stable?
