### ISSUE TITLE
Load extension

### ISSUE THREAD

**Issue by dunha** [praeclarum/sqlite-net#591]
Hi
I would like to use sqlite-net with a SQLite extension, and while there is an implementation for sqlite3_enable_load_extension, sqlite3_load_extension does not appear to be implemented.
I realise extensions can be loaded with an SQL function, but I have not been able to make this work with sqlite-net or System.Data.SQLite (although this has a load extension function). 
It does work with the sqlite shell, so I guess it is not available in the precompiled binaries

I had a look at wrapping the function myself, but I don't quite understand the C side of it, so I wonder if it could be included in a future release if it's not too much trouble

Thanks

**Comment by praeclarum** [comment]
I have recently exposed `EnableLoadExtension`: https://github.com/praeclarum/sqlite-net/commit/0829d449f6f3c4dae3b9f519f6a142a87fca717f

I will need to look into `LoadExtension`

**Comment by dunha** [comment]
Much appreciated

Oddly, where I have successfully loaded the extension, it doesn't seem to matter whether extension loading is enabled or not

**Comment by MKuckert** [comment]
As far as I understand this seems to not be possible at least on iOS. The underlying SQLitePCL.raw library doesn't provide a binding for `sqlite3_load_extension`: https://github.com/ericsink/SQLitePCL.raw/blob/master/src/cs/isqlite3.cs#L250

**Comment by praeclarum** [comment]
@MKuckert Yeah I was worried about that. Thanks for looking into it!

I'm going to keep this open as it could still be implemented for those who use the source code version of this library.

**Comment by praeclarum** [comment]
@MKuckert do you think I should remove `EnableLoadExtension` in light of this?

**Comment by MKuckert** [comment]
Yes, I would eliminate this method because there's no use in enabling it when you can't even load the extension then.

**Comment by dunha** [comment]
I was intending to use this with the source code version
The extension is too hard to make multiplatform anyway (for me at least)
This is for spatialite as referenced in another issue

**Comment by dunha** [comment]
I recently implemented this as a partial class and works OK with minimal change to the original source . Only tested on and intended for Windows

**Comment by jean-gblr** [comment]
> I recently implemented this as a partial class and works OK with minimal change to the original source . Only tested on and intended for Windows

Hello, i am also interested in loading the spatiliate extension using sqlite-net, is it possible for you to give information on how or share the part of code to modify ? I am not very experienced regarding this platform

**Comment by dudylan** [comment]
hi Can you load the extension normally now

**Comment by dunha** [comment]
I only tested this with the amalgamation and my copy of SQLite3, but it seems that the binding might now be provided in the underlying SQLitePCL.raw library. I couldn't find the file referenced in the earlier comment.
I don't use this lib much now as it's not getting much love these days, but you can add the following functions to load extensions ( no warranty)
Remember, you should not need to provide a file extension or entry point to load the extension

SQLiteConnection class

		/// <summary>
		/// Load extension.
		/// </summary>
		public void LoadExtension (string filename)
		{
			SQLite3.Result r = SQLite3.LoadExtension (Handle, filename, 0, 0);
			if (r != SQLite3.Result.OK) {
				string msg = SQLite3.GetErrmsg (Handle);
				throw SQLiteException.New (r, msg);
			}
		}

SQLite3 class

	[DllImport(LibraryPath, EntryPoint = "sqlite3_load_extension", CallingConvention=CallingConvention.Cdecl)]
	public static extern Result LoadExtension (IntPtr db, [MarshalAs(UnmanagedType.LPStr)] string filename, int entry, int msg);

**Comment by dudylan** [comment]
what is LibraryPath

**Comment by dunha** [comment]
It can be found it in the code, but there is no need to call that function, it is just the low level binding to SQLite called from the connection.LoadExtension wrapper
Note: there is no SQL function

**Comment by dudylan** [comment]
@dunha 
The language I use is C#
When I use the "Microsoft. Data. Sqlite" package, LoadExtension function is normal
But I am using "sqlite net sqlcipher" and he does not have this function
Because I need to use sqlcipher encryption

**Comment by dunha** [comment]
It's all C#. I don't understand what you want to do. You can either use this lib with sqlcipher and the additional extension loading functions, or go back to the Microsoft driver with sqlcipher [see here](https://learn.microsoft.com/en-us/dotnet/standard/data/sqlite/encryption?tabs=netcore-cli)

**Comment by dudylan** [comment]
@dunha I submitted an example

Please take a look
https://github.com/dudylan/SqliteCheck

**Comment by dunha** [comment]
I don't know what you want. You don't say if it worked or not, or what worked and what didn't
However, you shouldn't need to call the native library calling EnableLoadExtension twice, and 
```
_db.EnableLoadExtension(true);
_db.LoadExtension("Simple");
```
should be enough to load it. I can't really help further than that, although it looks like you are trying to load spatialite at some point and I believe that can be a challenge
