### ISSUE TITLE
WITHOUT ROWID support?

### ISSUE THREAD

**Issue by mohammadomt** [praeclarum/sqlite-net#595]
Any way to have [without rowid](https://sqlite.org/withoutrowid.html) table in sqlite-net?

**Comment by praeclarum** [comment]
No simple way.

Of course you can always Execute "CREATE TABLE" yourself.

**Comment by mohammadomt** [comment]
I think it would be great if we had access to the basic Sqlite methods beside automated methods in library.
For example having a function to get a row without any class defined like what @tofutim has done [here #82](https://github.com/praeclarum/sqlite-net/issues/82)

**Comment by praeclarum** [comment]
@mohammadomt You do have access to everything. Use the Handle property and the Sqlite3 class to do whatever you want.

I have reopened #82

**Comment by MKuckert** [comment]
Added an implementation in my fork by adding the `TableAttribute` with a new `WithoutRowId` property. The `CreateTable` method reads this property and adds `without rowid` to the create table – pretty straight forward.

What do you think?
