### ISSUE TITLE
SQLiteConnection Crash

### ISSUE THREAD

**Issue by prupleCode** [praeclarum/sqlite-net#602]
Hello，I Find Some Error:

1.in iOS, 'new SQLiteConnection("sqlite.db", SQLiteOpenFlags.Create);'  caused crash: Could not open database file: sqlite.db (Misuse), if use 'new SQLiteConnection("sqlite.db");' constructor I not find sqlite file in the sandbox documents,  it's so confusing

2.in Android, SQLiteConnection whatever invoke who constructor, caused crash: Could not open database file: sqlite.db (Misuse)

**Comment by praeclarum** [comment]
Hello!

1. You should always use complete paths unless you explicitly set the current working directory to a writable location.

2. Again, use absolute paths. Trusting the OS here is dangerous and error prone.

This code works well:

```csharp
Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.MyDocuments), "sqlite.db")
```

**Comment by prupleCode** [comment]
Thank you !!
