### ISSUE TITLE
SQLiteConnection.Commit sometimes leaves transactions alive causing permanent future transaction failures in the same process

### ISSUE THREAD

**Issue by ptsoccer** [praeclarum/sqlite-net#604]
When committing a transaction, there is a chance that it will fail if, according to [https://sqlite.org/lang_transaction.html](https://sqlite.org/lang_transaction.html), there is "another thread or process has a shared lock on the database that prevented the database from being updated". AKA, if some other connection is in the middle of a select statement and you try to commit a transaction, you will get SQLITE_BUSY on the commit. 

Well this is an issue because there is an internal variable called _transactionDepth that tries to track if we are in an active transaction. The problem is, _transactionDepth is set to 0 and then commit is executed on the database. Well, the commit fails and "When COMMIT fails in this way, the transaction remains active and the COMMIT can be retried later after the reader has had a chance to clear". The catch statements in the RunInTransaction family of functions catch this and call rollback, but since _transactionDepth is 0, the transaction isn't actually rolled back. So the next time begin transaction is called on the same connection, sqlite-net attempts to begin a new transaction (because _transactionDepth is 0), which promptly fails because there is still an active transaction on the connection. Well now we are in big trouble because _transactionDepth got set to 1, and when begin transaction fails in this manner, the transaction isn't rolled back (which would have set _transactionDepth to 0). From now on, any SQLiteConnection with the same connection string, because of connection pooling, fails when calling RunInTransaction(Async) because _transactionDepth is set to 1 and will never be set back to 0 unless for some reason Rollback is called manually.

My suggestion is to handle this problem in the commit function. If commit fails for whatever reason, the transaction should be rolled back, and the exception rethrown.

**Comment by praeclarum** [comment]
Ouch. Looks like I need a test for this. Thanks for reporting.

I'll be honest, I haven't looked at that code in years. :-)

This might be related to #329
