### ISSUE TITLE
Got a SIGSEGV while executing native code.

### ISSUE THREAD

**Issue by minafaw** [praeclarum/sqlite-net#610]
> 08-13 13:07:01.920 E/mono-rt (24966): No native Android stacktrace (see debuggerd output).
> 08-13 13:07:01.920 E/mono-rt (24966): 
> 08-13 13:07:01.920 E/mono-rt (24966): 
> 08-13 13:07:01.920 E/mono-rt (24966): =================================================================
> 08-13 13:07:01.920 E/mono-rt (24966): Got a SIGSEGV while executing native code. This usually indicates
> 08-13 13:07:01.920 E/mono-rt (24966): a fatal error in the mono runtime or one of the native libraries 
> 08-13 13:07:01.920 E/mono-rt (24966): used by your application.
> 08-13 13:07:01.920 E/mono-rt (24966): =================================================================
> 08-13 13:07:01.920 E/mono-rt (24966): 
> 08-13 13:07:01.920 F/libc    (24966): Fatal signal 11 (SIGSEGV), code 1, fault addr 0x6974746553676e in tid 24993 (Finalizer)

any one could know how can I fix this issue

**Comment by praeclarum** [comment]
Which version were you using? It's hard to fix with so little information here.

**Comment by minafaw** [comment]
version is 3.1.1

when I target Android N , the same issue with Mac iOS 10

**Comment by praeclarum** [comment]
Sorry there is no version 3.1.1 of this library. The current release is 1.4. The nuget package is `sqlite-net-pcl`

**Comment by minafaw** [comment]
Sorry you are right I download anther library beside yours that was the cause of this issue when I remove all sqlite libraries and inset yours its working  I will close this issue
