### ISSUE TITLE
Wrong version number for SQLite-net.dll targeting netstandard1.1

### ISSUE THREAD

**Issue by Dabbel** [praeclarum/sqlite-net#621]
The SQLite-net.dll targeting netstandard1.1 has a wrong version number. The Version number is 1.0.0.0 but should be the same as the dll targeting portable Profile 259.

Because of that i'm unable to run a UWP app.

**Comment by praeclarum** [comment]
This is fixed in 1.5.166-beta and will get out of prerelease soon.
