### ISSUE TITLE
Do I need to use a lock object with SQLiteAsyncConnection?

### ISSUE THREAD

**Issue by Project4MobileDev** [praeclarum/sqlite-net#635]
Should I be using a lock object while using SQLiteAsyncConnection? I have a problem where I'm trying to save data but it seems to completely freeze. Each operation is being awaited before the next one starts though so it seems that there shouldn't be a problem with deadlock. I noticed that there's a SQLiteConnectionWithLock but I thought I'd ask whether locking was necessary when using SQLiteAsyncConnection or if it's done automatically under the hood? Many thanks.

**Comment by praeclarum** [comment]
Yes synchronization is done under the hood for you and you do not need to do any yourself.
