### ISSUE TITLE
Database  VACUUM

### ISSUE THREAD

**Issue by hupo376787** [praeclarum/sqlite-net#644]
Hi, is "vacuum" available?

**Comment by nitinphansalkar** [comment]
I have used it as: `db.Execute("vacuum");` in my UWP app.
where `db `is the `SQLiteConnection`. I can confirm that it works.

**Comment by hupo376787** [comment]
@nitinphansalkar Thanks, man!

**Comment by codrut-n** [comment]
It is not available.
