### ISSUE TITLE
Can I avoid referencing sqlite-net in main app?

### ISSUE THREAD

**Issue by Yorch7** [praeclarum/sqlite-net#647]
So I just read  #437 , and I think  I'm facing the same problem. 

I have a final PCL app project that accesses another PCL library project. In that library I handle all requests to databases and I have references to sqlite-net-pcl in three projects: pcl, android and ios. My final project does not communicate directly with the database. As that final project is maintained by another team, I do not have access to add references, only in my data access library.  **Is there any workaround to avoid referencing sqlite-net in the final project?**

I made an apk with sqlite-net nugget installed in my final project and in my data access library and another one in which I installed it only in the library. I decompressed them and saw that in the second two files are omitted:
SQLitePCLRaw.lib.e_sqlite3.dll
SQLitePCLRaw.batteries_green.dll

**Why are they omitted, if my library has a android project that uses them?**

**Comment by ericsink** [comment]
I don't think there is any workaround to do what you want.

And I don't think there is anything we can do to change it.  That's just the way nuget transitive dependencies work with a PCL.

The pattern is actually very common with nuget packages.  In order for nuget to get the platform-specific parts, it is necessary to reference package X from the app project, even if package X is not directly used there.

But in your situation, this is unfortunate.

**Comment by Yorch7** [comment]
Thank you very much for your quick answer @ericsink
