### ISSUE TITLE
Database is locked

### ISSUE THREAD

**Issue by awattar** [praeclarum/sqlite-net#654]
https://github.com/praeclarum/sqlite-net/blob/5603ee0c66276e2242f4bd5bf654afb9bfc91db9/tests/ConcurrencyTest.cs#L146

This change breaks the test with "database is locked" exception during execution:

ExecuteScalar<string> ("PRAGMA journal_mode=WAL");

in

public SQLiteConnection (string databasePath, SQLiteOpenFlags openFlags, bool storeDateTimeAsTicks = true)

for the subsequent DBReader SELECT query.

When switching back to ReadOnly for DBConnection in DbReader test works as expected.

The other workaround is to set the same BusyTimeout for ExecuteScalar query as for rest of the code:

BusyTimeout = TimeSpan.FromSeconds (0.1);
if (openFlags.HasFlag (SQLiteOpenFlags.ReadWrite)) {
    ExecuteScalar<string> ("PRAGMA journal_mode=WAL");
}
because above code from base constructor is called first before the code form inherited object constructor that is trying to adjust the timeout:

    public class DbConnection : SQLiteConnection
    {
        private static string DbPath = TestPath.GetTempFileName();

        public DbConnection(SQLiteOpenFlags openflags) : base(DbPath, openflags)
        {
            this.BusyTimeout = TimeSpan.FromSeconds(5);
        }

        public void CreateTables()
        {
            CreateTable<TestObj>();
        }
    }
Probably base constructor with new busyTimeout parameter will be better to set correct busy timeout value right from the beginning.

**Comment by praeclarum** [comment]
Fixed in 1.5
