### ISSUE TITLE
NullReferenceException 

### ISSUE THREAD

**Issue by awattar** [praeclarum/sqlite-net#657]
https://github.com/praeclarum/sqlite-net/blob/5603ee0c66276e2242f4bd5bf654afb9bfc91db9/src/SQLiteAsync.cs#L1380

This line will throw

`System.NullReferenceException : Object reference not set to an instance of an object.`

when no operations was taken after SQLiteAsyncConnection creation.

Sample code:

```
			var db = new SQLiteAsyncConnection(path, true);
			db.CloseAsync().Wait();
```

**Comment by JKennedy24** [comment]
I am also seeing this bug. Is there any way to work around this error?

**Comment by MadManMarkAu** [comment]
Another confirmation of this bug.

As part of testing and debugging, we're opening the database when the app loads, then closing, deleting, and recreating the database with fresh test data. We're getting a NullReferenceException on the "await ms_sacConnection.CloseAsync();" line.

**Comment by praeclarum** [comment]
Sorry for the trouble. I put a fix in. Hopefully will release today.
