### ISSUE TITLE
SQLiteDb.db.InsertAsync always returns 1

### ISSUE THREAD

**Issue by caciocode** [praeclarum/sqlite-net#668]
Whenever I try to insert in a loop I always get 1. For example;
`int g = await SQLiteDb.db.InsertAsync(market);`

**Comment by hupo376787** [comment]
1 means success, ok.

**Comment by caciocode** [comment]
How can I get the id of the created object? I think the documents state that it returns the id of the created object.

**Comment by hlubovac** [comment]
For me, the property decorated with `[PrimaryKey]' attribute (which is an int) gets set automatically by the `Insert` method. The return value represents either success or the number of affected records (not sure). We're normally not interested in this value at all :)

**Comment by hupo376787** [comment]
You can Read the docs https://github.com/praeclarum/sqlite-net

If you want to get the id(auto generated), then you can use 

```
Stock stock = new Stock()
{
	Symbol = "AAPL"
};

var conn = new SQLiteAsyncConnection(databasePath);

await conn.InsertAsync(stock);

Debug.WriteLine("New customer ID: {0}", stock.Id);
```

This is also in the docs. @praeclarum , our great man, wrote it very clear.

**Comment by praeclarum** [comment]
Insert actually returns the number of rows inserted.

As @hupo376787 said, the Id is stored in the designated PrimaryKey of the object you inserted.

**Comment by AntvissMedia** [comment]
Wow. Just wanted to stop by and say thanks for this! First time a piece of code makes me feel retarded and is also an eye opener. I've been doing all sort of gymnastics trying to get that ID when it was actually assigned to the object by default this whole time. 😄

**Comment by Nullstr1ng** [comment]
![image](https://user-images.githubusercontent.com/260633/80800404-f56ecf00-8bdb-11ea-9c21-adac24aa4486.png)

Task<int> InsertAsync(object obj)
**Insert** and **Retreives** its auto incremented primary key if it has one.  
  
c'mon guys .. It could've said "Retreives" or "Returns the number of rows inserted"
