### ISSUE TITLE
UWP Target "Fall Creators Update" with Sql-net-sqlcipher fails with FileNotFoundException

### ISSUE THREAD

**Issue by JKennedy24** [praeclarum/sqlite-net#681]
Ok So I have a UWP project which references uses .NetStandard 1.4 libraries

I had SqlCipher working fine but then needed to upgrade my UWP project min/target version both to `Fall Creators Update`

Since then my .Net Standard library returns the following error when using any of the Sqlite-Net api calls:

> Could not load file or assembly 'SQLite-net, Version=1.5.166.0, Culture=neutral, PublicKeyToken=null'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

I think this is a similar error to this one: https://github.com/praeclarum/sqlite-net/issues/601

As the Version of the `Sqlite-net.dll` in the `.netstandard1.1` folder of the nuget package is `V1.0.0`

Here is my standard .csproj package reference file

    <PackageReference Include="sqlite-net-pcl" Version="1.5.166-beta" ExcludeAssets="All" />
    <PackageReference Include="sqlite-net-sqlcipher" Version="1.5.176-beta" />
    <PackageReference Include="SQLiteNetExtensions">
      <Version>2.0.0</Version>
    </PackageReference>
    <PackageReference Include="SQLiteNetExtensions.Async">
      <Version>2.0.0</Version>
    </PackageReference>
    <PackageReference Include="SQLitePCLRaw.bundle_green" Version="*" ExcludeAssets="All" />
    <PackageReference Include="SQLitePCLRaw.bundle_sqlcipher" Version="1.1.9" />

**Comment by JKennedy24** [comment]
ok so this is kind of a blocking bug for me implementing this.

I think it is something to do with this change set:
https://github.com/praeclarum/sqlite-net/commit/8c72783cade5095f1bd187ede7b7a59df4c6f350#diff-bb0bb6d07ba2b63f62634603dca084c9

but don't know enough of what is going on there to fix it

**Comment by ericsink** [comment]
So it looks like you have sqlite-net-pcl referenced in a portable library of yours?  And you are using a PackageReference with ExcludeAssets="All" to try and replace it in your UWP project?

Here's something to try:

In your portable/netstandard library, replace the sqlite-net-pcl package with sqlite-net-base:

https://www.nuget.org/packages/sqlite-net-base

In your UWP project, remove the package references for sqlite-net-pcl, sqlite-net-sqlcipher, and bundle_green.

This should get rid of all the extra stuff floating around, but IIRC, now you need to init the SQLitePCL library.  So in your UWP project, very early on, add:

    SQLitePCL.Batteries_V2.Init()

I hope this helps.

**Comment by JKennedy24** [comment]
I think the bottom line here is that the `Sqlite-Net-Sqlcipher` nuget package does not work with UWP because the version is incorrect
