### ISSUE TITLE
DateTime fields stored as text are not read from database

### ISSUE THREAD

**Issue by MarcoMiltenburg** [praeclarum/sqlite-net#688]
I had an existing SQLite database and my new code was not reading the date/time fields. I looked at the code and found the following in [/src/SQLite.cs](https://github.com/praeclarum/sqlite-net/blob/master/src/SQLite.cs) (lines 2874 - 2886):

```csharp
else if (clrType == typeof (DateTime)) {
    if (_conn.StoreDateTimeAsTicks) {
        return new DateTime (SQLite3.ColumnInt64 (stmt, index));
    }
    else {
        var text = SQLite3.ColumnString (stmt, index);
        DateTime resultDate;
        if (!DateTime.TryParseExact (text, DateTimeExactStoreFormat, System.Globalization.CultureInfo.InvariantCulture, System.Globalization.DateTimeStyles.None, out resultDate)) {
            resultDate = DateTime.Parse (text);
        }
        return resultDate;
    }
}
```

The line that is causing the problem I think is line 2881:

```csharp
        if (!DateTime.TryParseExact (text, DateTimeExactStoreFormat, System.Globalization.CultureInfo.InvariantCulture, System.Globalization.DateTimeStyles.None, out resultDate)) {
```

The NOT operator (`!`) should be left out. If `TryParseExact` succeeds, the `Parse` should be called. This bug was added in commit e0ba8bc3daec3ff2f430760e0d96f66cb3e4a067.

**Comment by ptsoccer** [comment]
That line looks correct to me. If TryParseExact succeeds, resultDate will be set.

**Comment by MarcoMiltenburg** [comment]
Ah yes, `TryParseExact` also has `resultDate` as an out parameter. OK, then I will have to download the source code and use that directly in my project and debug why I don't get the date/time fields from my SQLite database. I will open a new issue if necessary.
