### ISSUE TITLE
SQLiteAsyncConnection stops working after app resumes execution

### ISSUE THREAD

**Issue by rraallvv** [praeclarum/sqlite-net#695]
In Xamarin.Forms for Android after I go to the home screen and resume the application execution, calling async methods in an instance of SQLiteAsyncConnection doesn't work.

- Do I have to create a new SQLiteAsyncConnection instance when the app resumes execution?

- How can I know is the connection's been lost before trying to execute some async query in it?

Keep up the good work.

**Comment by Weldryn** [comment]
Try put `SQLite.SQLiteAsyncConnection.ResetPool();` inside your overrided `OnSleep` in your `App` before `base.OnSleep`.

Consider cleaning up your app every time it goes through `OnSleep` and load what you neede when `OnResume`

Hope it helps

**Comment by rraallvv** [comment]
@Weldryn , it did the trick. Thanks so much!

**Comment by Weldryn** [comment]
Glad to help. Please, close the issue.
