### ISSUE TITLE
Using Sqlite-net beta lowers the version of its dependencies

### ISSUE THREAD

**Issue by dompham** [praeclarum/sqlite-net#702]
Hi All,
We were wondering why going from 1.4.118 to 1.5.166-beta lowered the versions for SQLitePCLRaw core, bundle_green, and provider.sqlite3.ios_unified from 1.1.9 to 1.1.8?  Are we safe to keep the 3 dependencies at their original versions?  Thanks in advance.

**Comment by ericsink** [comment]
You should be fine using 1.1.9 with 1.5.166-beta
