### ISSUE TITLE
Old columns not dropped

### ISSUE THREAD

**Issue by bnserig** [praeclarum/sqlite-net#704]
Hello,

I have a problem with the CreateTable function. It does not drop old columns when I delete one property from the class.

Example with old class :
```
public class TableExample {
    [PrimaryKey, AutoIncrement]
    public int Id { get; set; }

    public int Col1 {get; set; }
    public int Col2 {get; set; }
    public int Col3 {get; set; }
}
```
New class :
```
public class TableExample {
    [PrimaryKey, AutoIncrement]
    public int Id { get; set; }

    public int Col1 {get; set; }
    public int Col2 {get; set; }

    public int Col4 {get; set; }
}
```

The old column Col3 is not dropped from the table (and I think it is the same with indexes).

Another subject : when can we expect a new stable nuget version ?

Thanks,
Benoît

**Comment by Weldryn** [comment]
I don't think the table migration involves column deletion. sqlite-net is only providing a way to use sqlite in a cross platform way. However it has nothing to do (neither sqlite) with what to do with the data **you** stored in it.
If you want to 'clean' your table, you will need to create the SQL script yourself as only you own the knowledge of what is important or not about the data.

**Comment by bnserig** [comment]
I didn't know that SQLite doesn't support drop column. So I wrote some function to rename the table, recreate with new columns and insert into new table.
Thanks for your answer.

**Comment by Weldryn** [comment]
Glad to help. Please, close this issue if it has been resolved.
