### ISSUE TITLE
CloseAsync is not available.

### ISSUE THREAD

**Issue by tedrog36** [praeclarum/sqlite-net#709]
I am using the latest version of the Nuget package referenced in the documentation.  Looks like this was last updated on July 27, 2017.  Looks like CloseAsync was added after that.

Is there a different package I should be using or should I be using it via source code?

What is the recommendation @praeclarum et al?

Ted

**Comment by tedrog36** [comment]
I got around my issue by installing the beta version of sqlite-net-pcl.

Any idea when this might be released?

**Comment by praeclarum** [comment]
I've been collecting feedback because it had a change in behavior.

But it would seem that it's working for everyone so I'll try to ship it out this weekend or next week.

**Comment by tedrog36** [comment]
@praeclarum Any plans to release the beta or update this library in general?
