### ISSUE TITLE
How to backup in-memory database?

### ISSUE THREAD

**Issue by sorencoder** [praeclarum/sqlite-net#711]
Hi, How can I backup an in-memory database?
I created an in-memory database with this code:
`DatabaseConnection = new SQLiteConnection(":memory:");`

Thanks.

**Comment by michaldobrodenka** [comment]
You have to use methods like:

raw.sqlite3_backup_init
raw.sqlite3_backup_step
raw.sqlite3_backup_pagecount

**Comment by praeclarum** [comment]
v1.6 has a new Backup() method that will handle writing a complete backup for you!
