### ISSUE TITLE
Xamarin iOS, issue with connection when db file does not exist

### ISSUE THREAD

**Issue by icemokka** [praeclarum/sqlite-net#715]
Hi,

I'm using Xamarin 4.9.0 with Xamarin.iOS 11.8 targeting iOS v11 , in VS.net 2017.
Plugin version is 1.4.118 with the 3 'Raw' packages versioned as 1.1.11.

My platform specific code follows at the end.
When I create the connection in the IPhone 6 simulator with iOS 11, I get following error :

> SQLite.SQLiteException: Could not open database file: /Users/user139934/Library/Developer/CoreSimulator/Devices/63C1DF25-8BA0-454F-9D95-D565CE101324/data/Containers/Data/Application/23C69EB4-5B16-4F49-963E-FCA7647BD7FA/Documents/.config/SchindlerTA.db3 (Misuse)

I can't find an iOS permission that relates to local storage, so I'm not sure what's wrong.

Any idea's ?

```
private string getDatabaseName()
        {
            string pathForDb = System.Environment.GetFolderPath(System.Environment.SpecialFolder.ApplicationData);
            pathForDb = Path.Combine(pathForDb, Utils.DatabaseFileName);

            return pathForDb;
        }

        public SQLiteConnection GetConnection()
        {
            string databaseName = getDatabaseName();
            if (!File.Exists(databaseName))
            {
                return new SQLiteConnection(databaseName,SQLiteOpenFlags.Create);
            }
            else
                return new SQLiteConnection(databaseName);
        }
```

**Comment by tessarolli** [comment]
i had this problem before, try removing the Create Flag.

**Comment by icemokka** [comment]
I just found the issue, it was my lack of knowledge about the iOS filesystem restrictions.
I had to add 'Library' at the end of the path appearantly.

`string documentsPath = Environment.GetFolderPath(Environment.SpecialFolder.Personal); // Documents folder
            string libraryPath = Path.Combine(documentsPath, "../Library/"); // Library folder
            var path = Path.Combine(libraryPath, Utils.DatabaseFileName);`
