### ISSUE TITLE
no such function: parse

### ISSUE THREAD

**Issue by acaliaro** [praeclarum/sqlite-net#717]
Hi guys.

I have this code

```
        public async Task<List<TruckDetail>> TruckDetailSelectAsync(string barcode)
        {
            var rows = _sqliteAsyncConnection.Table<TruckDetail>().Where(o => o.Prscam == long.Parse(barcode));
            return await rows.ToListAsync();
            //return await _sqliteAsyncConnection.Table<TruckDetail>().Where(o => o.Prscam == long.Parse(barcode)).ToListAsync();
        }
```

When I execute it, the ToListAsync() raise an exception:

**no such function: parse**

Am I wrong?

**Comment by acaliaro** [comment]
I am using it with Xamarin.Android... Insert works fine...

**Comment by Weldryn** [comment]
From what I can understand, this is normal. When you call `Table<T>()`, it creates a deferred expression based object [(TableQuery<T>)](https://github.com/praeclarum/sqlite-net/blob/5603ee0c66276e2242f4bd5bf654afb9bfc91db9/src/SQLite.cs#L3057) works on the same principle than `Linq`. **_However_**, it is **not** `Linq`. The expression you put in there is analysed and "translated" to SQL but it is **not executed** (although, I don't know into what it is translated when it does not recognise an expression...).
That`s why you need to put simple expression (e.g. logic comparison) that expresses what you want and do all the calculation/parsing/processing before the expression.

To take your example, you would need to do:

	public async Task<List<TruckDetail>> TruckDetailSelectAsync(string barcode)
	{
		var code = long.Parse(barcode);
		var rows = _sqliteAsyncConnection.Table<TruckDetail>().Where(o => o.Prscam == code);
		return await rows.ToListAsync();
	}

Hope this helps

**Comment by acaliaro** [comment]
I try thamks

**Comment by acaliaro** [comment]
It works. thanks
