### ISSUE TITLE
Subclassing of SQLiteCommand is not possible because of internal constructor.

### ISSUE THREAD

**Issue by ekoezle** [praeclarum/sqlite-net#718]
The factory method  SQLiteConnection.NewCommand() can't be used to create a subclass of SQLiteCommand.

**Comment by Weldryn** [comment]
Why would you like to do so?

**Comment by ekoezle** [comment]
This ist the comment to the  SQLiteCommand.OnInstanceCreated()-method:

This can be overridden in combination with the <see cref="SQLiteConnection.NewCommand"/>
method to hook into the life-cycle of objects.

This exactly what i want to do: 

- Subclass the SQLiteCommand
- Create an object of my SQLiteCommand-Subclass in SQLiteConnection.NewCommand()
- call a method on my persistent stateful objects in SQLiteCommand.OnInstanceCreated() to set the right state an so on

**Comment by praeclarum** [comment]
Sorry about that!
