### ISSUE TITLE
Conflicts between sqlite-net-pcl and sqlite-net-sqlcipher

### ISSUE THREAD

**Issue by kyzeofsd** [praeclarum/sqlite-net#722]
I am currently trying to implement encryption on a database for a mobile app and currently have an internally developed package that depends on sqlite-net-pcl version 1.4.118 I however, want to implement sqlcipher so I have installed sqlite-net-sqlcipher as mentioned in #597 which works pretty well except that my other package begins to throw an exception:
`System.MissingMethodException: Method 'SQLite.SQLiteConnection.CreateTable' not found.`

I believe this might have something to do with conflicting namespaces and I'm wondering if someone can help me determine if I have something configured wrong or if this isn't possible.

**Comment by ericsink** [comment]
I usually suggest:

1.  Remove sqlite-net-pcl everywhere.  In portable libraries (netstandard), replace it with sqlite-net-base.
2.  In your app projects (the one that actually builds an exe or an app), reference SQLitePCLRaw.bundle_sqlcipher.
3.  If you get an error at runtime saying you need to init or call SetProvider, add this to your app project initialization: `SQLitePCL.Batteries_V2.Init();`

**Comment by arjunkr92** [comment]
Hi, I'm facing a similar problem, when I try to install sqlite-net-base in my PCL project,  I'm getting an error as below:

> Could not install package 'sqlite-net-base 1.5.231'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile259', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.
