### ISSUE TITLE
No merged pull request in almost a year

### ISSUE THREAD

**Issue by Rivolvan** [praeclarum/sqlite-net#730]
i'd like to know the status of this project. It hasn't seen an update in almost a year. Pull requests are piling up with features that are very much needed and wanted by the community.
@praeclarum any thoughts?

**Comment by opcodewriter** [comment]
It's called OPEN SOURCE. Which means absolutely no reliability. The maintainer can sign out from it with no excuses needed. 
Sad but this is the reality.

**Comment by opcodewriter** [comment]
I'd definitely contribute with some $ if the maintainer asks for it.
Unfortunately he didn't setup any way to contribute yet.

I wish it becomes a standard for open source to ask for $ contribution when the creator\maintainer really wishes to maintain his work ONLY IF there's enough $.
Otherwise, with no such contribution plan setup, this really means the creator has no intention of contributing. And this kind of work needs to be seen with caution.

**Comment by superyetkin** [comment]
Ona can always fork an open source project and carry on. If there are people interested in this, we can setup a new one.

**Comment by Rivolvan** [comment]
@opcodewriter i'd like to extend your point though, since this is open source, the creator/maintainer must let others "maintain" this and make others accept pull requests on his stead, since open source SHOULD be about the community building a better product. but sad that this is still the way open source is perceived. always on the brink of obsolescence.

**Comment by Rivolvan** [comment]
@superyetkin I think we can say, there is a pretty big number of people interested in this project as seen in the issues tracker and pull requests. the challenge will be to herd these developers to another fork and make them feel assured that this will be maintained much better.

**Comment by ToddThomson** [comment]
If anyone is interested, I have a new repo that targets Sqlite and is cross platform ( .NetStandard 2.0). It is in the early stages of development, but I believe provides the features of this inactive repo. [Entities.Sqlite](https://github.com/achilles/entities.sqlite).

If there is an active owner to this repo, please feel free to delete this comment. I only want to offer an alternative if this repo is inactive.

**Comment by Weldryn** [comment]
> If anyone is interested, I have a new repo that targets Sqlite and is cross platform ( .NetStandard 2.0). It is in the early stages of development, but I believe provides the features of this inactive repo. Entities.Sqlite.

This is actually not completely true. To name only a few:

- This project targets .Net Standard 1.1
- Entities.Sqlite makes use of `dynamic` which is a no-go if you are targetting iOS

Would you be keen on including these constraints?

**Comment by praeclarum** [comment]
Thank you for your concern over this repo.
