### ISSUE TITLE
Vacuum

### ISSUE THREAD

**Issue by EdCFong** [praeclarum/sqlite-net#734]
Hello, how can I use "vacuum" , I need re-order the Keys after delete a row

**Comment by Weldryn** [comment]
Like that: `Execute("VACUUM");`
Be careful, there is some side effects, see the [doc](https://www.sqlite.org/lang_vacuum.html).

Hope this helps!

Don't forget to close the issue when done

**Comment by lnaie** [comment]
you can also do something like this:

```
await _database.DbConnection.RunInTransactionAsync((SQLiteConnection conn) => {
    conn.Query<SettingEntity>("DELETE FROM Settings");
    conn.Query<SettingEntity>("DELETE FROM sqlite_sequence WHERE name = 'Settings'");
});
```

**Comment by DenZuck** [comment]
Execute("VACUUM"); does not reduce the size of the DB. It seems not working but I get no errors or exception. Someone can help me ?
