### ISSUE TITLE
[Q] How to add custom setter

### ISSUE THREAD

**Issue by rraallvv** [praeclarum/sqlite-net#736]
Is it ok if I add a custom setter backed by a private field in a SQLite backed class?

Particularly I want a property, let's say the property `Checked`, that additionally to changing its value in the database when set, will also update the value in a second property with the modification time, in this case the updated property would be `Modified`.

	public class MyTable
	{
		[PrimaryKey, AutoIncrement]
		public int ID { get; set; }
		public bool Checked { get; set; }
		public DateTime Modified { get; set; }
	}

**Comment by cisoun** [comment]
Hi.

Despite I didn't try it myself, I don't see why it couldn't work. Unless some internal sqlite-net-pcl behavior prevents that, I would have tried this:

```C#
public class MyTable
{
	private bool checked;

	[PrimaryKey, AutoIncrement]
	public int ID { get; set; }
	public bool Checked
	{
		get => checked;
		set
		{
			checked = value;
			Modified = DateTime.Now;
		}
	}
	public DateTime Modified { get; set; }
}
```
Have you tried since then ?

**Comment by rraallvv** [comment]
@cisoun I tried what you suggested, but there is some kind of recursion in my code that is preventing it to work. At least that my guess. I'll try to isolate the code that is causing the issue. What I ended up doing was this:

```
public class MyTable
{
	[PrimaryKey, AutoIncrement]
	public int ID { get; set; }
	public bool Checked { get; set; }
	public DateTime Modified { get; set; }

	public void SetChecked(bool checked)
	{
		Checked = checked;
		Modified = DateTime.Now;
	}
}
```

Then I just set the property like this `SetChecked(true)`

Thanks for taking a look into this :)

**Comment by cisoun** [comment]
Yes, that's actually a better solution and I'm ashamed I forgot about that...
Cheers !

**Comment by Weldryn** [comment]
>      public class MyTable
>      {
> 	 	  [PrimaryKey, AutoIncrement]
> 	 	  public int ID { get; set; }
> 	 	  public bool Checked { get; set; }
> 	 	  public DateTime Modified { get; set; }
> 	     
> 	 	  public void SetChecked(bool checked)
> 	 	  {
> 	 	  	Checked = checked;
> 	 	  	Modified = DateTime.Now;
> 	 	  }
>     }

This is the right thing to do since sqlite-net use the setter when rehydrating the data. With the backing field version, you might or might not find yourself with a wrong `Modified` value depending on the order of setter's call inside the rehydration phase since the `Modified` data is also part of the data structure in the DB.

Sqlite-net requires for a property to be mapped in the database to have both the setter and the getter public and to not have the `Ignore` attribute. If you want to have a decent amount of logic and/or have data encapsulation from a class user point of view, you might want to wrap it in a proxy like this:

    public class MyTableProxy
    {
        private MyTable _data;
        
        public MyTableProxy(MyTable data)
        {
            _data = data;
        }
        
        //  Property forwarding
        public int ID { get => _data.ID; set => _data.ID = value }
        
        //  Because Modified should only be modified when Checked for example
        public DateTime Modified => _data.Modified;
        
        //  Add some logic here for Checked and Modified
        public bool Checked
        {
            get => _data.Checked;
            set
            {
                _data.Checked = value;
                _data.Modified = DateTime.Now;
            }
        }
        
        //  Just for convenience...
        public static implicit operator MyTable(MyTableProxy proxy) => proxy._data;
    }

Hope this helps!

**Comment by rraallvv** [comment]
@Weldryn thanks, I like the approach with a proxy.
