### ISSUE TITLE
app crash when dispose sqliteconnection 

### ISSUE THREAD

**Issue by suihanhbr** [praeclarum/sqlite-net#737]
My app crash when I dispose sqliteconnection instance in multi-thread .
![](https://user-images.githubusercontent.com/17265184/43579809-de137bc8-9685-11e8-9c34-5112d02b722d.jpg)
here is my code:
```
		public override void reSet() {
			Interlocked.Exchange(ref isWaitToReset, 1);
			excuteReset();

		}

		void excuteReset() {
			try {
				if (Interlocked.Read(ref isWaitToReset) != 1) {
#if DEBUG
					Debug.WriteLine("reset not need.");
#endif
					return;
				}
				if (Interlocked.Read(ref isOperating) != 0
				|| Interlocked.Read(ref isInTransaction) != 0) {
#if DEBUG
					Debug.WriteLine("reset delay.");
#endif
					return;
				}
				var temp = dataBase;
				if (temp == null) return;
				lock (lockObject) {
					if (Interlocked.Read(ref isWaitToReset) != 1
						|| Interlocked.Read(ref isOperating) != 0
						|| Interlocked.Read(ref isInTransaction) != 0) {
#if DEBUG
						Debug.WriteLine("reset must be delay.");
#endif
						return;
					}
					dataBase = null;
					Interlocked.Exchange(ref isWaitToReset, 0);
				}
				temp?.Dispose();


#if DEBUG
				Debug.WriteLine("reset success.");
#endif
			} catch (Exception exception) {
				ErrorReporter.Report(exception);
			}

		}
```

**Comment by cisoun** [comment]
Hi !

Off-topic tip : you can get ride of those `#if Debug / #endif` directives. `Debug.WriteLine` will only appear as long as you compile in DEBUG mode.

**Comment by Weldryn** [comment]
Don't do try to dispose the connection yourself, they are pooled.
See #716 for the correct way of releasing a connection.

A word about your code, if I may: are you sure all these `Interlocked` are necessary? Seems to me like a code smell.


Don't forget to close the issue if you found a satisfying answer! :)

**Comment by suihanhbr** [comment]
Finally, I fix this issue by using the native implement of Android.
Think you.
