### ISSUE TITLE
Is this repo still active?

### ISSUE THREAD

**Issue by ToddThomson** [praeclarum/sqlite-net#741]
It has been about a year since any commits to this project. Are there any active contributors?

**Comment by ToddThomson** [comment]
If anyone is interested, I have a new repo that targets Sqlite and is cross platform ( .NetStandard 2.0). It is in the early stages of development, but I believe provides the features of this inactive repo. [Entities.Sqlite](https://github.com/achilles-software/entities.sqlite).

If there is an active owner to this repo, please feel free to delete this comment. I only want to offer an alternative if this repo is inactive.

**Comment by FoggyFinder** [comment]
#730

**Comment by 40345839668** [comment]
Evet

**Comment by praeclarum** [comment]
Yes it is.
