### ISSUE TITLE
Insert doesn't return PK

### ISSUE THREAD

**Issue by henningpohl** [praeclarum/sqlite-net#743]
The [documentation ](https://github.com/praeclarum/sqlite-net/wiki/GettingStarted) currently states that:
> If the table contains an auto-incremented primary key, then the value for that key will be available to you after the insert

Yet, the code for the insert method in [SQLite.cs](https://github.com/praeclarum/sqlite-net/blob/master/src/SQLite.cs) returns the number of rows inserted (line 1666 right now). If I look at the history, this seems to have been the case for many years.

So what is it? And how can we get the primary key of what was just inserted now?

**Comment by lnaie** [comment]
it works, but you got to make the PK nullable.
see this one: https://github.com/praeclarum/sqlite-net/issues/327

**Comment by henningpohl** [comment]
If this is the intended behavior then the documentation should be updated. The example currently is:
```
public static void AddStock(SQLiteConnection db, string symbol) {		
    var Id = db.Insert(new Stock() {		
        Symbol = symbol		
    });		
    Console.WriteLine("{0}", Id);		
}
```

**Comment by praeclarum** [comment]
Sorry for the confusion. The README is now fixed.

**Comment by henningpohl** [comment]
Nothing in the README.md file changed with regard to inserting. The text still reads the same as quoted above.

**Comment by pha3z** [comment]
For anyone else who is having problems with this, the correct method is described in this other issue here:
https://github.com/praeclarum/sqlite-net/issues/37
