### ISSUE TITLE
SQlite ORM Doesn't Work On Updated SDK(higher than API Level 23)

### ISSUE THREAD

**Issue by alirezafathi84** [praeclarum/sqlite-net#746]
I've received this error : 

Unhandled Exception: System.TypeInitializationException: The type initializer for 'DataAccess.infoRepository' threw an exception.

when the target compile version is higher than API Level 23 . Now i need to update my app for play store and it doesn't work.what shuld i do???

**Comment by 40345839668** [comment]
Windows marketi deneyin.

**Comment by mpapadis** [comment]
Check permissions. See this [https://developer.android.com/guide/topics/permissions/overview](https://developer.android.com/guide/topics/permissions/overview) or this [https://blog.xamarin.com/requesting-runtime-permissions-in-android-marshmallow/](https://blog.xamarin.com/requesting-runtime-permissions-in-android-marshmallow/)
