### ISSUE TITLE
System.DllNotFoundException: /system/lib/libsqlite.so exception on Android 7

### ISSUE THREAD

**Issue by dehghani-mehdi** [praeclarum/sqlite-net#747]
Hi,

I copied `SQLite.cs` and `SQLiteAsync.cs` in order to use `Sqlite-net` in my Xamarin.Android project, my app works on all Android versions but v7.0 (I didn't test on v+7.0).

I got following exception:
> System.DllNotFoundException: /system/lib/libsqlite.so exception on Android 7

Error happens here: [`LibVersionNumber = SQLite3.LibVersionNumber ();`,](https://github.com/praeclarum/sqlite-net/blob/master/src/SQLite.cs#L260)

Is this a bug, or I miss something?

**Comment by Weldryn** [comment]
You are missing how to use a package.
I recommend you always have a deep read of the [Readme](https://github.com/praeclarum/sqlite-net) of a repository before doing anything. Also, reading the [online tutorials](https://developer.xamarin.com/guides/android/data-and-cloud-services/data-access/part-3-using-sqlite-orm/) definitely help, they are meant for that.
Don't just copy/paste source files unless you know what you are doing.

Hope this helps!

Don't forget to close the issue when done with it please.

**Comment by dehghani-mehdi** [comment]
@Weldryn I think you need to read the [Readme](https://github.com/praeclarum/sqlite-net) again, specially following section:

[source-installation](https://github.com/praeclarum/sqlite-net#source-installation)

There is no warning, use with caution or something like that.

I read mentioned article and some other articles, and I know how to solve this problem (actually I already did), I report this issue, just to help and contribute. 

BTW, there is no reason to understand everything in order to use source code of some library. using source code (specially when the developer mentioned in Readme section, like this project) is good idea, even if you don't know and understand all of its codes.

**Comment by praeclarum** [comment]
Hi, Please use the `sqlite-net-pcl` nuget package. Using from source requires that you provide your own binary for sqlite.

**Comment by dehghani-mehdi** [comment]
@praeclarum Okay, can you add this note to README? I think it helps.

**Comment by nnnhi** [comment]
@dehghani-mehdi How do you over come it?

**Comment by dehghani-mehdi** [comment]
@nnnhi I removed `SQLite.cs` and `SQLiteAsync.cs` and then installed [sqlite-net-pcl](https://www.nuget.org/packages/sqlite-net-pcl/)

**Comment by mofadevs** [comment]
> Hi, Please use the `sqlite-net-pcl` nuget package. Using from source requires that you provide your own binary for sqlite.

Good day @praeclarum 
I am using the `sqlite-net-pcl 1.1.1` and `SQLitePCL.raw 0.8.6` nugets since a long time in the same app. Everything was working fine, until recently compiled against Android 7 and tested on an Android device with 7, and facing the issue, `System.DllNotFoundException: /system/lib64/libsqlite.so`. App crashes. Do I need to update the nugets? Please advise.

**Comment by JFMG** [comment]
I've updated my SQLite class with this property:

```csharp
[DllImport("sqlite3", EntryPoint = "sqlite3_config", CallingConvention = CallingConvention.Cdecl)]
internal static extern Result Config(ConfigOption option);
```

In the constructor of my SQLite class I called
```csharp
Config(ConfigOption.Serialized);
```

It works now.

**Comment by ghd258** [comment]
{System.TypeInitializationException: The type initializer for 'SQLite.SQLiteConnection' threw an exception. ---> System.DllNotFoundException: e_sqlite3 assembly:<unknown assembly> type:<unknown type> member:(null)
  at (wrapper managed-to-native) SQLitePCL.SQLite3Provider_e_sqlite3+NativeMethods.sqlite3_libversion_number()
  at SQLitePCL.SQLite3Provider_e_sqlite3.SQLitePCL.ISQLite3Provider.sqlite3_libversion_number () [0x00000] in <a8b44b00879c49c3afe1464977fda362>:0 
  at SQLitePCL.raw.SetProvider (SQLitePCL.ISQLite3Provider imp) [0x00008] in <61f7edf725d84e86bad37534de465b1f>:0 
  at SQLitePCL.Batteries_V2.Init () [0x00005] in <1e145190beee47768df5e21ac9abfe79>:0 
  at SQLite.SQLiteConnection..cctor () [0x00016] in <d1788edcec634c19b907698bb77ed371>:0 
   --- End of inner exception stack trace ---
  at (wrapper managed-to-native) System.Object.__icall_wrapper_mono_generic_class_init(intptr)
  at PhxGaugingAndroid.Fragments.WorkOrderFragment.GetWorkOrderList () [0x00087] in E:\LdarVOCsTool\PhxGaugingV6\PhxGaugingAndroid\Fragments\WorkOrderFragment.cs:1966
