### ISSUE TITLE
Database Locked Error

### ISSUE THREAD

**Issue by danielPollackGitHub** [praeclarum/sqlite-net#757]
I have upgraded from 1.4.118 to 1.5.231 and whenever I try to execute a scalar on an asynchronous connection, I receive an error that the database is locked. I had do downgrade to 1.4.118 and the issue is no longer present. What changed? I'm using this for a Xamarin forms project in conjunction with MVVMCross 6.2. Here is the simple method I call:

public async Task<bool> TableExists()
        {
            try
            {
                var command =
                    $"SELECT count(tbl_name) FROM sqlite_master WHERE type = 'table' AND name = '{typeof(T).Name}'";
                var count = await DbAsynchronousConnection.ExecuteScalarAsync<int>(command).ConfigureAwait(false);
                
                return count > 0;
            }
            catch (SQLiteException sqLiteException)
            {
                throw;
                //todo: handle the exception
            }
        }

**Comment by mpapadis** [comment]
What is this DbAsynchronousConnection you are using?
Try creating a new instance of a SQLiteAsyncConnection and using that for the ExecuteScalarAsync command. I think you use a single instance of SQLiteAsyncConnection for multiple queries and that is the source of your problems. 
Moreover, check if you have storage permission acquired before running commands on the database.

**Comment by ClausElmann** [comment]
First time i works, but next time i open my app, I also get Database Locked.
no problems in  1.4.118 :-)

**Comment by praeclarum** [comment]
This should be fixed in the 1.6-beta. Please let me know if it is not!

**Comment by InquisitorJax** [comment]
@praeclarum any updates on the 1.6 release ETA?
