### ISSUE TITLE
Can't create table with List<T>

### ISSUE THREAD

**Issue by alvseek** [praeclarum/sqlite-net#758]
I got
```
System.NotSupportedException: Don't know about System.Collections.Generic.List`1[System.Double]
```
when I tried to create table with

```C#
public class CustomMessage
    {
        [PrimaryKey, AutoIncrement]
        public long Id { get; set; }
        public string Text { get; set; }
        public List<double> Geo { get; set; }
    }
```

Is this normal or it's a bug?

EDIT: I tried other data types and it also gives error

If this is normal, then what should I do if I need to have `List<T>`?

I'm using v 1.5.231

Thank you!

**Comment by alvseek** [comment]
Wait, I tried making another class with the exact properties and it doesn't give error. This is mind blowing...

**Comment by alvseek** [comment]
Seems like I have to serialize it manually

**Comment by georgerappel** [comment]
@alvseek How did you do it manually?

**Comment by alvseek** [comment]
> @alvseek How did you do it manually?

I serialized it to json using newtonsoft json
