### ISSUE TITLE
RunInTransaction documentation

### ISSUE THREAD

**Issue by damirarh** [praeclarum/sqlite-net#76]
I'd like to add some documentation on correct usage of `RunInTransaction` methods (both synchronous and asynchronous).

I'm not sure what would be the correct location for it. Currenlty the documentation seems to be in two places: the Wiki pages and the `README.mdown` file.

What's the preffered location, i.e. where should I put the additional documentation?

**Comment by ATopeCode** [comment]
Hello. What do you know if the transaction was executed ok?
Does RunInTransaction() method throws exceptions?

Thanks.

**Comment by praeclarum** [comment]
@ATopeDev I added a small section to the doc mentioning how exceptions are bubbled up.
