### ISSUE TITLE
Result of COUNT(*) always zero when using QueryAsync

### ISSUE THREAD

**Issue by Bunogi** [praeclarum/sqlite-net#763]
I am executing a query like so:
```C#
var query = await DatabaseConnection.QueryAsync<CountId>(
        "SELECT COUNT(*), channelid " +
        "FROM ChannelLog " +
        "GROUP BY ChannelId " +
        "ORDER BY 1 DESC");
```

Where CountId is a simple class implemented like so:
```C#
internal class CountId {
    public uint Count { get; set; }
    public long ChannelId { get; set; }
}
```
However, the resulting CountId's `Count` variable will always be set to 0. `ChannelId` is set to the expected value as verified by running the query inside a database browser.

**Comment by FoggyFinder** [comment]
maybe you could try `SELECT COUNT(*) as count, channelid ...`

**Comment by Bunogi** [comment]
That works, thanks!
