### ISSUE TITLE
Proposed SQLCipher, Database Keying, and WAL changes

### ISSUE THREAD

**Issue by sjlombardo** [praeclarum/sqlite-net#765]
Hello @praeclarum, 

Thanks again for the recent release of sqlite-net. I wanted to follow up on the discussion from #597 regarding the database keying for SQLCipher and WAL. To recap the issue, SQLCipher provides a number of PRAGMAs that are very commonly used to control settings for key derivation, security options, page sizes, performance optimization, and data migrations. However, these all need to be called prior to the first use of the database (i.e. first read or write), and some need to be called even prior to keying SQLCipher. The current implementation, which sets the key via constructor and then immediately enables WAL journal mode (which writes to the database), makes executing any of the SQLCipher PRAGMAs impossible. As a result many frequently used SQLCipher options and several common data migration operations are currently unusable. 

A secondary concern has to do with forcing journal_mode = WAL when a SQLiteConnection is opened. While WAL mode is typically a good choice, there are some specific cases where it is not. Setting journal_mode = WAL in the constructor effectively prevents an application from using any other journal mode (i.e. even if they turn off WAL mode, the next time a SQLiteConnection is instantiated it will be changed back). This could be really undesirable for certain cases. Calling journal_mode = WAL repeatedly is also not strictly necessary because that journal mode is persistent and stored by SQLite in the database header. Thus, it only needs to be run one time and then subsequent database opens will automatically open in WAL mode, so there is no need to set it on every connection.

We'd like to propose two changes. The first would be to add preKey and postKey actions to the default constructor that would allow an application to provide initialization blocks e.g.:

```
public SQLiteConnection (string databasePath, SQLiteOpenFlags openFlags, bool storeDateTimeAsTicks = true, object key = null, Action<SQLiteConnection> preKey = null, Action<SQLiteConnection> postKey = null)
```
Inside the constructor, these would be executed prior to and immediately after keying respectively.

The second optional change would be to move PRAGMA journal_mode = WAL out to a separate method of SQLiteConnection, e.g. enableWal(). Since WAL can be enabled at any time, an application could simply call it once after a connection was opened to turn on the feature. This would be consistent with how other SQLite API wrappers do things, e.g. enableWriteAheadLogging() in Android. Since that journal mode is persistent, applications enabling it will automatically use it on all future connections.

What do you think about these proposed changes? We'd be happy to discuss further or submit a pull request if you feel one or both would be worthwhile. Thank you for your consideration.

**Comment by sjlombardo** [comment]
Hi @praeclarum - I was wondering if you have any feedback on these proposals? An imminent release of SQLCipher will change a number of default settings. This will make it difficult or impossible to use the current version of sqlite-net with the new version of SQLCipher to open existing databases. Since this would be confusing and troublesome for users, we'd prefer to avoid that situation. We'd be happy do the work of preparing a pull request and coordinating the change with you, either by implementing these proposals, or an alternate approach if you have one that you'd prefer. Let us know what you think, and thanks for your time!

**Comment by praeclarum** [comment]
Hello,

Sorry for my delayed response. I have accepted the PR and pulled in a bunch of features.

I have decided that you're right, and I will make WAL opt-in via a function call.

Please keep an eye out for 1.6-beta with these changes.

**Comment by praeclarum** [comment]
I have changed the API a bit so as not to overwhelm the main ctor - you can now pass in your pre and post actions into the `ConnectionString` ctor.
