### ISSUE TITLE
SQLiteAsyncConnection not creating the database file Android

### ISSUE THREAD

**Issue by IsmaelMendonca** [praeclarum/sqlite-net#773]
Hello everyone, 

I am facing a mind-blowing issue with the SQLiteAsyncConnection from the sqlite-net-pcl package.

I am creating a new Connection as usual using the class below:

```
public sealed class AndroidStoreConnection : IConnectionContext
    {
        public AndroidStoreConnection()
        {
            Database = new SQLiteAsyncConnection(ConnectionPath(), storeDateTimeAsTicks: false);
        }

       public SQLiteAsyncConnection Database
        {
            get;
            private set;
        }

        private string ConnectionPath()
        {
            string databaseName = "FapMobile.db3";
            string documentsPath = System.Environment.GetFolderPath(System.Environment.SpecialFolder.Personal); // Documents folde
            return Path.Combine(documentsPath, databaseName);
        }
    }
```

The problem is that starting a new instance of SQLiteAsyncConnection is not creating the db file into the Android's local system file.

I already checked the permissions in the AndroidManifest and WRITE_EXTERNAL_STORAGE and READ_EXTERNAL_STORAGE is set up.

Now the most strange behavior is that no exceptions has been raised, otherwise I could check what's going on.

I am using the release 1.5.231.

Please can anyone help me? I am getting crazy with that!

**Comment by Weldryn** [comment]
Just use the ctor with `CreateFlags` parameter. The flag you are looking for is `SQLiteOpenFlags.Create`.
I am creating connections like that:

    public bool DateTimeStoredAsInteger => true;

    public SQLiteOpenFlags CreationFlags { get; } =
        SQLiteOpenFlags.ReadWrite |
        SQLiteOpenFlags.Create |
        SQLiteOpenFlags.SharedCache |
        SQLiteOpenFlags.FullMutex,;

    private SQLiteAsyncConnection ConnectionFactory(string dbPath) =>
        new SQLiteAsyncConnection(dbPath, CreationFlags, DateTimeStoredAsInteger);

**Comment by IsmaelMendonca** [comment]
> Just use the ctor with `CreateFlags` parameter. The flag you are looking for is `SQLiteOpenFlags.Create`.
> I am creating connections like that:
> 
> ```
> public bool DateTimeStoredAsInteger => true;
> 
> public SQLiteOpenFlags CreationFlags { get; } =
>     SQLiteOpenFlags.ReadWrite |
>     SQLiteOpenFlags.Create |
>     SQLiteOpenFlags.SharedCache |
>     SQLiteOpenFlags.FullMutex,;
> 
> private SQLiteAsyncConnection ConnectionFactory(string dbPath) =>
>     new SQLiteAsyncConnection(dbPath, CreationFlags, DateTimeStoredAsInteger);
> ```

Well thank you for the advice, is nice to know that we can control the database creation from these flags.

I actually found a "solution", the device file system is not showing the sqlite db file anymore. Using the Android adb prompt command I figured out that the file had been created but I could not access it without a rooted device. Well I tried to root by myself and I lost my device cofigurations, needing to reset it after that. Here is an advice guys: DON'T TRY TO DO IT WITH YOUR PERSONAL DEVICE.


Anyway I ended up forgetting this idea of get the db file to see how it's had been created, I am gonna try another approach, nothing in mind yet but I am working on it.
