### ISSUE TITLE
Using sqlite-net-pcl in wpf

### ISSUE THREAD

**Issue by DenZuck** [praeclarum/sqlite-net#774]
I've tried this code in a WPF application. I don't understand why the returned s variable is of int type. It should be of Stock type according to you example. Where is the problem ?

`            var s = db.Insert(new Stock()
            {
                Symbol = symbol
            });`

**Comment by yuudai** [comment]
I think that is not a problem.
The return value of Insert() is  retrun value of sqlite3_changes().
sqlite3_changes () returns the affected row.

**Comment by yuudai** [comment]
It means the following example code.
`public static void AddStock(SQLiteConnection db, string symbol) {
	var s = db.Insert(new Stock() {
		Symbol = symbol
	});
	Console.WriteLine("{0} == {1}", s.Symbol, s.Id);
}`
I think this was a mistake.

**Comment by Weldryn** [comment]
@yuudai first answer is correct. When you insert a single item, `Insert` returns the PK or RowId of this item in the table where it was inserted.
As for @DenZuck problem, why do you consider a problem not having the item you inserted from the method returned while you have it in the first place as a parameter ??

**Comment by DenZuck** [comment]
If return type is PK or RowId then this example should be corrected because it expects a Stock return type.

```javascript
public static void AddStock(SQLiteConnection db, string symbol) {
	var s = db.Insert(new Stock() {
		Symbol = symbol
	});
	Console.WriteLine("{0} == {1}", s.Symbol, s.Id);
}
```

You can find it here:
https://github.com/praeclarum/sqlite-net

**Comment by Weldryn** [comment]
You are right it should be. The documentation is a bit out of date I think.
It should also be noted that declaring a class with an auto incremented PK like that

    public class Stock
    {
        [PrimaryKey, AutoIncrement]
        public int Id { get; set; }
        public string Symbol { get; set; }
    }

will end up having issue. Instead you should do that

    public class Stock
    {
        [PrimaryKey, AutoIncrement]
        public int? Id { get; set; }
        public string Symbol { get; set; }
    }

**Comment by DenZuck** [comment]
I agree.
