### ISSUE TITLE
Database is locked / No way to set the connection timeout before "PRAGMA journal_mode=WAL" is executed

### ISSUE THREAD

**Issue by dominik-weber** [praeclarum/sqlite-net#778]
In the recent update of sqlite-net the behavior was changed to execute `PRAGMA journal_mode=WAL` in the SQLiteConnection constructor automatically.
Unfortunately, due to the call being made in the constructor itselt, we can't set the connection timeout for the journal_mode call (it is always 0.1s). Because of this we get a "Database is locked" exception in `new SQLiteConnection(...)`

Please add some method how we can configure the timeout in this case. Maybe an additional constructor parameter for the default timeout, or you could move the journal_mode call to CreateTable or some new method, so we can configure the BusyTimeout before...

**Comment by dominik-weber** [comment]
In the recent update of sqlite-net the behavior was changed to execute `PRAGMA journal_mode=WAL` in the SQLiteConnection constructor automatically.
Unfortunately, due to the call being made in the constructor itselt, we can't set the connection timeout for the journal_mode call (it is always 0.1s). Because of this we get a "Database is locked" exception in `new SQLiteConnection(...)`

Please add some method how we can configure the timeout in this case. Maybe an additional constructor parameter for the default timeout, or you could move the journal_mode call to CreateTable or some new method, so we can configure the BusyTimeout before...

**Comment by awattar** [comment]
Simply use code version instead of nugget and pass timeout parameter to the constructor.

**Comment by laDanz** [comment]
I also have issues with the way you deal with WAL.

Maybe you could introduce a new `SQLiteOpenFlag` "SQLITE_OPEN_WAL" like here: https://www.sqlite.org/c3ref/c_open_autoproxy.html and then only enable WAL when this flag is set?

Would be a great help for me!

**Comment by praeclarum** [comment]
I have switch WAL to be opt-in via a call to `EnableWriteAheadLogging`. This should make it possible for you to set your timeouts or not use it at all. See #765 for reference. Thanks!

**Comment by praeclarum** [comment]
You'll be able to see this in the 1.6-beta

**Comment by jonathanantoine** [comment]
@praeclarum thanks a lot for working on this ! Any idea of the "final release date" ?
