### ISSUE TITLE
Version 1.5.231 breaks QueryAsync

### ISSUE THREAD

**Issue by corradolab** [praeclarum/sqlite-net#779]
Query executed via QueryAsync works with 1.4.118 but fails with 1.5.231.
Application throw "SQLite.SQLiteException no such table" while table actually exists.

**Repro project** (Net Core Console app)

```
using SQLite;
using System.Threading.Tasks;

namespace SQLiteNetBug
{
  [Table("Customers")]
  public class Customer
  {
    public int CustomerID { get; set; }
    public string Name { get; set; }
  }

  class Program
  {
    static async Task Main(string[] args)
    {
      SQLiteAsyncConnection connection = new SQLiteAsyncConnection(":memory:", false);
      await connection.CreateTableAsync<Customer>();

      Customer customer = new Customer
      {
        CustomerID = 1,
        Name = "Joe"
      };

      await connection.InsertAsync(customer);

      await connection.QueryAsync<Customer>("select * from Customers");
    }
  }
}
```

(Enable C# 7.1 or above in Project properties / Compile / Advanced to allow async Main)

**Expected result**
The application starts and immediatly stops with SQLite-net 1.4.118

**Actual result**
The application starts and throws "SQLite.SQLiteException no such table: Customers" with SQLite-net 1.5.231

**Comment by praeclarum** [comment]
I am able to repro, thanks. Investigating now.

**Comment by praeclarum** [comment]
It turns out there are several bugs around async memory databases. I have fixed the most egregious which will make your sample work. Keep an eye out for 1.6-beta.

**Comment by roboticsware** [comment]
When creating new encrypted database, same error in  sqlite-net-sqlcipher 1.6.292
