### ISSUE TITLE
Calling SQLiteConnectionString(string, bool) throws a MethodNotFound exception

### ISSUE THREAD

**Issue by charlenni** [praeclarum/sqlite-net#780]
If I use version 1.5.231 in a Xamarin.Forms Android part (.Net Standard 2.0 project), than I get a MethodNotFound exception when calling SQLiteConnectionString(string, bool). If I use 1.4.118 all is ok. For the iOS part, 1.5.231 works ok without problems.

**Comment by praeclarum** [comment]
Sorry this was a mistake and will be fixed in 1.6. See also #784
