### ISSUE TITLE
[BREAKING CHANGE] SQLiteConnectionString ctor

### ISSUE THREAD

**Issue by plamen-i** [praeclarum/sqlite-net#784]
A third required argument (object key) was added between versions 1.4.118 and 1.5.231 to SQLiteConnectionString ctor so this breaks libraries which tried to use it.

Btw. I mention that in all other ctors (SQLiteConnection, SQLiteAsyncConnection) it is added as optional (object key = null).

**Comment by charlenni** [comment]
Ah, it was [this](https://github.com/praeclarum/sqlite-net/commit/c360ae602dd3a36d8ffdb60e3101c872a5de872a) commit, which changes the ctors. But why is the SQLiteConnectionString the only, where key not defaults to null?

**Comment by praeclarum** [comment]
Yes, this was a mistake. Sorry for the trouble. I'll work on it this week.

**Comment by chixlol** [comment]
@praeclarum Do you already know the date, when this bugfix will be released?

**Comment by praeclarum** [comment]
I have a fix in place and will release a beta today. If it looks good, I'll do a full release.

**Comment by praeclarum** [comment]
I can confirm that it's back in 1.6:

https://www.fuget.org/packages/sqlite-net-pcl/1.6.249-beta/lib/netstandard1.1/diff/1.4.118/

**Comment by pauldendulk** [comment]
@praeclarum Any idea when 1.6 will be released? Currently users of my library experience a runtime error when upgrading the packages to the latest version, which is something do most of the time.
