### ISSUE TITLE
InsertOrReplaceAsync  not working as intended

### ISSUE THREAD

**Issue by dannythomas13** [praeclarum/sqlite-net#785]
I have a base class with a property ID of type string that I have marked as PrimaryKey but when I use InsertOrReplaceAsync and add a record having the same ID I have found that it adds a second row even though the ID values are the same, is this because I am using a string for ID or because the object being added uses inheritance and the ID is in the base class?

**Comment by praeclarum** [comment]
Hello, this works for me on version 1.6:

```csharp
    class Person {
        [PrimaryKey]
        public string Name { get; set; }
        public int Age { get; set; }
    }

    class Program
    {
        static void Main(string[] args)
        {
            var path = Path.GetTempFileName();
            var db = new SQLiteConnection(path);
            db.CreateTable<Person> ();
            db.InsertOrReplace (new Person { Name = "Frank", Age = 38 });
            Console.WriteLine (db.Table<Person> ().Count ());
            db.InsertOrReplace (new Person { Name = "Frank", Age = 39 });
            Console.WriteLine (db.Table<Person> ().Count ());
        }
    }
```

Perhaps updating will fix it?
