### ISSUE TITLE
GetAsync does not work with in-memory database

### ISSUE THREAD

**Issue by mobilemotion** [praeclarum/sqlite-net#787]
In version 1.5.231, the `GetAsync` method throws a `SQLiteException: no such table`

To reproduce, create a simple model class:

    public class MyTable
    {
        [PrimaryKey, AutoIncrement]
        public int Id { get; set; }

        public string Column1 { get; set; }
    }

...and insert a line into the DB, then try to read it:

    var conn = new SQLiteAsyncConnection(":memory:", true);
    await conn.CreateTableAsync<MyTable>();
    await conn.InsertAsync(new MyTable { Id = 1, Column1 = "a" });
    var x = await conn.GetAsync<MyTable>(1);

The last line fails (`SQLiteException: no such table: MyTable`), but works when passing a DB path on disk instead of ":memory:". Happens for me both in a .NET 4.6 console application and in a .NET Core 2.1 console application.

Am I using everything correctly? Can somebody confirm this behavior?

**Comment by stevenengland** [comment]
Same here for me when using FindAsync and in memory db.
Fails:
`var customer = await this.database.FindAsync<Customer>(x => x.Name == name).ConfigureAwait(false);`
Succeeds:
`var customer= await this.database.Table<Customer>().Where(x => x.Name == name).FirstOrDefaultAsync().ConfigureAwait(false);`

**Comment by mobilemotion** [comment]
FYI: Downgrading to v1.4.118 resolved the problem. However, only a temporary solution obviously...

**Comment by praeclarum** [comment]
Hi all, sorry for the trouble. I have fixed this for 1.6 (beta out now) but there are some additional bugs I've discovered that haven't been addressed. That said, those same bugs were in 1.4 so I'm marking this closed.

**Comment by poumason** [comment]
I already use the 1.6.292 version, but the issue exist exist.
