### ISSUE TITLE
Consider update to SQLitePCL.raw 1.1.13

### ISSUE THREAD

**Issue by ericsink** [praeclarum/sqlite-net#794]
Hey Frank,

I just pushed SQLitePCL.raw 1.1.13 to nuget.  In 1.1.12, some of the bundled sqlcipher builds were broken.  The 1.1.13 release fixes that, and contains no other significant changes.

Since you appear to be finalizing a release, I'm letting you know in case you want to update your reference, but it doesn't seem critical that you do so.

**Comment by praeclarum** [comment]
Perfect. Thanks for letting me know.
