### ISSUE TITLE
SQLite.SQLiteException: file is not a database

### ISSUE THREAD

**Issue by wangminsho** [praeclarum/sqlite-net#802]
I am trying to create an encrypted database using SQLiteAsyncConnection in a Xamarin project. I am using sqlite-net-sqlcipher package and updated it to 1.6.258 beta version in PCL project. I also updated the same for Android app project as well. This is the only package I am using for database encryption. Am I supposed to use any other packages along with this?
I am using following lines of code to encrypt the database.
`           SQLitePCL.Batteries_V2.Init();
            m_databaseName = DependencyService.Get<SqlHelper>().GetDBFileName();
            m_database = new SQLiteAsyncConnection(m_databaseName);
            string password = "$1234#";
            m_database.QueryAsync<int>("PRAGMA key='?'", password);`

When i run this the first time, a DB file is created but it is not encrypted. I am able to open the database and view its contents. Second time when I run the App i get "SQLite.SQLiteException: file is not a database" exception.
As a test case, when i used SQLiteConnection instead of SQLiteAsyncConnection, database is encrypted correctly. Please let me know what is going wrong and if I am following the steps correctly. Thanks.

**Comment by vasani-arpit** [comment]
@wangminsho How did you resolved this issue ?

**Comment by quangvinhnguyen** [comment]
@wangminsho How did you resolved this issue ?
