### ISSUE TITLE
sqlite-net-sqlcipher with SQLiteNetExtensions

### ISSUE THREAD

**Issue by softerj** [praeclarum/sqlite-net#807]
Hi there. My current project is making use of sqlite-net-pcl v1.5.231 and SQLiteNetExtensions v2.1.0 by TwinCoders. I would like to make the switch to use sqlite-net-cipher. I created a new project for testing a basic example and was able to get sqlite-net-cipher v1.6.258-beta to encrypt the database fine. When I add SQLiteNetExtensions to the project I get the following error when trying to create the db connection:

![image](https://user-images.githubusercontent.com/7099117/52580980-6317bb00-2dde-11e9-831f-491f904ffb20.png)

What can I do to make the extensions library compatible with sqlite-net-cipher?

**Comment by ericsink** [comment]
Looks like SQLiteNetExtensions has a dependency on sqlite-net-pcl, so you're bringing in SQLitePCLRaw.bundle_green as well as SQLitePCLRaw.bundle_sqlcipher, which is causing you problems.

You can probably fix this with something like:

        <PackageReference Include="SQLitePCLRaw.bundle_green" ExcludeAssets="All"/>

**Comment by softerj** [comment]
Thank you Eric. The following line did the trick:

`<PackageReference Include="SQLitePCLRaw.bundle_green" ExcludeAssets="All" Version="1.1.13"/>`

I knew it was something along the lines of that but I'm still a novice to all of this. Thanks for you help.
