### ISSUE TITLE
ExecuteScalar throws exception when table is empty

### ISSUE THREAD

**Issue by suihanhbr** [praeclarum/sqlite-net#811]
I execute code like ` conn.FindInt($"select max(id) from {tableName};") ;`  and the FindInt() likes that

```
		public override int FindInt(string query) {
			try {
				var result = DataBase.ExecuteScalar<int>(query);
				return result;

			} catch (Exception e) {
				ErrorReporter.Report(e);
			}
		 return 0;
		}

```

If the table is empty , it will throws NullReferenceException. And app maybe crash at Android 8.0 or Android 9.0.

**Comment by kinderry** [comment]
Yes,this is a bug when you  use ExecuteScalar with a colunm not in the table.
