### ISSUE TITLE
Column from private property

### ISSUE THREAD

**Issue by EmmanuelJego** [praeclarum/sqlite-net#817]
Hello,

I would like to know if it's possible to create a table with (some) columns matching to private properties in my models. From what I see, it's currently not possible (when I retrieve data from my database, the properties are null). 

I've tried to precise the Column attribute (`[Column("MyColumn"]) private string MyString { get; set; }`), to see if it has the same behavior as NewtonSoft Json library (which takes into account private properties if we precise the [JsonProperty] attribute), but it doesn't seems to change anything.

Thanks for your help!
Emmanuel

**Comment by kinderry** [comment]
Columns are created by reflection,we usually only use public properties,if you are sure to use private properties ,you can update this Method in SQLite.cs :
` public TableMapping(Type type, CreateFlags createFlags = CreateFlags.None)`  
change  ` (p.GetMethod.IsPublic && p.SetMethod.IsPublic)`   in line 2515
to    ` ((p.GetMethod.IsPublic && p.SetMethod.IsPublic)||(p.GetMethod.IsPrivate&& p.SetMethod.IsPrivate)) `

**Comment by denravonska** [comment]
We'd also like to be able to serialize private properties, at least when explicitly mapped to a column.

We have a situation were we use enum flags to determine available features for a particular product. This enum has extensions that allows us to set, clear and get flags, hiding the bit operations. The problems we have is that we cannot use `ref` in the extensions to modify the enum as properties, required by SQLiteNet, cannot be passed as `ref`.

As a workaround we have a property field (`_Features`) which wraps a non-property field (`Features`) but that field is required to be public which adds a slight confusion.

**Comment by TomArrow** [comment]
Any way to make it posssible by default to expose the properties to SQLite via the InternalsVisibleTo attribute? 

https://learn.microsoft.com/en-us/dotnet/api/system.runtime.compilerservices.internalsvisibletoattribute?view=net-8.0

That way SQLite could access them without a problem while still restricting elsewhere in the software. Though being able to set an option to allow private setters for write operations would be better still.

**Comment by pavlobielousov** [comment]
I agree that the possibility of marking the required private property with an attribute would be very helpful. Since we already have the [Ignore] attribute, a new attribute may be called [Include] to mark a property that should be included in the table.
