### ISSUE TITLE
SQLiteConnectionString with encryption pragmas doesn't work

### ISSUE THREAD

**Issue by galit1993** [praeclarum/sqlite-net#858]
When trying to set pragmas to control the encryption I get error CS1739:
The best overload for 'SQLiteConnectionString' does not have a parameter named 'preKeyAction'

Code:
`var options = new SQLiteConnectionString(databasePath, true,
                key: password,
                preKeyAction: db => db.Execute("PRAGMA cipher_default_use_hmac = OFF;"),
                postKeyAction: db => db.Execute("PRAGMA kdf_iter = 128000;"));`

I looked at SQLiteConnectionString definition and preKeyAction, postKeyAction doesn't appear there:
![image](https://user-images.githubusercontent.com/50656806/62460219-12c85700-b78a-11e9-854c-8581b23c3a44.png)

Installed package: sqlite-net-sqlcipher -Version 1.5.231

**Comment by NipunKalra** [comment]
@galit1993 that ctor is in pre-release. You can find the ctor here (https://github.com/praeclarum/sqlite-net/blob/master/src/SQLite.cs#L2164). Install the latest beta version 1.6.258-beta from nuget

**Comment by galit1993** [comment]
Thank you! :) 👍
