### ISSUE TITLE
TimeSpans are saved as strings by default

### ISSUE THREAD

**Issue by tipa** [praeclarum/sqlite-net#877]
Since the latest update to v1.6.292, TimeSpans are saved as strings by default, while DateTimes are saved as ticks. I create the DB connection as follows:
`var db = new SQLiteConnection(dbPath);`

![image](https://user-images.githubusercontent.com/2863198/65420057-7bce6180-de00-11e9-979c-a71677c349b4.png)
This commit introduced that change in behavior: https://github.com/praeclarum/sqlite-net/commit/cf41ec30bc38e83345cbc6a065f201a660192fb9

I think the TimeSpans should default to ticks as well.

Edit: Even when specifying `storeTimeSpanAsTicks: true` in the connection string, I cant force them to be saved/read as ticks:
`var db = new SQLiteConnection(new SQLiteConnectionString(dbPath, SQLiteOpenFlags.Create | SQLiteOpenFlags.ReadWrite | SQLiteOpenFlags.FullMutex, true, storeTimeSpanAsTicks: true));`

**Comment by gtbX** [comment]
Hope to resolve this with https://github.com/praeclarum/sqlite-net/pull/878

**Comment by tipa** [comment]
@praeclarum any chance to merge the PR from @gtbX? :)

**Comment by Zofware** [comment]
Yes please! Pretty please!

**Comment by tipa** [comment]
This can be used as a workaround in the meantime:
`db .GetType().GetProperty("StoreTimeSpanAsTicks").SetValue(db , true, null);`

**Comment by Zofware** [comment]
@tipa Oh man thanks for that! With AppCenter 3 out now I wasn't sure how to move forward. That's great!

**Comment by Zofware** [comment]
@tipa, do you know how to make this hack work with `SQLiteAsyncConnection`? I tried calling `SQLiteAsyncConnection.GetConnection`, then locked the returned synchronous connection, then tried your hack but it throws an exception because the `StoreTimeSpanAsTicks` property isn't writable.

**Comment by tipa** [comment]
I don't use the async version, so no idea, sorry

**Comment by Zofware** [comment]
@praeclarum, if we tossed some coin into your Patreon bucket would you consider merging #878 and pushing out a new release? Thanks.

**Comment by MoeHamdan** [comment]
@Zofware for async connections you can do something like the below
`            var con = new SQLiteAsyncConnection(databasePath);
            var innerCon = con.GetConnection();
            typeof(SQLiteConnection).GetProperty("StoreTimeSpanAsTicks").SetValue(innerCon, true, null);`

**Comment by Zofware** [comment]
Thanks @MoeHamdan. I'll give that a try. I've been using a locally built copy of SQLite-Net that has the fix applied but it would be nice to go back to using the version from nuget.

**Comment by tipa** [comment]
Appears to be fixed now with the latest version - thanks for merging @gtbX pull request!
