### ISSUE TITLE
sqlite-net-sqlcipher : How it works?

### ISSUE THREAD

**Issue by Zujaj** [praeclarum/sqlite-net#903]

**Comment by simonbuehler** [comment]
``` 
_connection = new SQLiteConnection(Global.AppdataPath + "cipher.db",true, "secretkey");
_connection.CreateTable<MyClass>();
```

**Comment by Zujaj** [comment]
> ```
> _connection = new SQLiteConnection(Global.AppdataPath + "cipher.db",true, "secretkey");
> _connection.CreateTable<MyClass>();
> ```

What is Global?

**Comment by simonbuehler** [comment]
ok i am still on version 1.5x of sqlite-net-sqlcipher, things got refactored but just follow the example sin the tests: https://github.com/iodes/sqlite-net/blob/021fd74db56c1f5d2f7b25706190c8fdeebdf99d/tests/SQLCipherTest.cs#L36
