### ISSUE TITLE
How can I use sqlite-net to create a single table, single column database of just int numbers?

### ISSUE THREAD

**Issue by nicktheone** [praeclarum/sqlite-net#926]
I have a really long list of numbers in a plain text file I want to migrate to a SQL database. Since sqlite-net only seems to accept an object when creating a table or inserting a value how can I use it in order to achieve a single table (numbers), single column (number) database of just int numbers?

**Comment by RSF-Deus** [comment]
Not sure I follow your intentions, if you want to have a table with just integers, you have to create an object with just integer as properties inside, and fill all those properties before inserting the object with a simple insert command

**Comment by nicktheone** [comment]
Thanks. That’s what I thought I had to do.
