### ISSUE TITLE
Question: Updating 1.6.292 to 1.7.335 version

### ISSUE THREAD

**Issue by Orgbrat** [praeclarum/sqlite-net#954]
Now that we finally have a  new stable version, is the update of version 1.6.292 to 1.7.335 properly and fully done with the Nuget package manager update. Does all needed dependencies get updated correctly as needed within Visual Studio 2019 and a Xamarin Forms solution containing Android, iOS and UWP?  Or is there something special that needs to be done?

**Comment by ederbond** [comment]
I've updated the nuget packages I everything just worked

**Comment by Orgbrat** [comment]
Well I was very concerned about this update because the latest Microsoft.AppCenter libraries needed this new update to work correctly. But I can say that this update  went very smoothly and I was very happy.  Thanks praeclarum...
