### ISSUE TITLE
savePoint is not valid

### ISSUE THREAD

**Issue by shengxq** [praeclarum/sqlite-net#963]
应该是多线程操作时引起的异常,出现下面的错误后,关闭软件会丢失异常之后的所有数据

It should be an exception caused by multithreading operation. After the following error occurs, closing the software will lose all data after the exception

请问应该怎么解决

How to solve it
```
savePoint is not valid, and should be the result of a call to SaveTransactionPoint.
参数名: savePoint  
在 SQLite.SQLiteConnection.DoSavePointExecute(String savepoint, String cmd)
   在 SQLite.SQLiteConnection.Release(String savepoint)
   在 SQLite.SQLiteConnection.RunInTransaction(Action action)
   在 SQLite.SQLiteConnection.UpdateAll(IEnumerable objects, Boolean runInTransaction)
   在 Cls_Standard.Cls_账单.计算账单() 位置 C:\\Users\\ShengXQ\\Desktop\\ydcxt5\\ydcxt5\\Cls_Standard\\业务逻辑\\Cls_账单.cs:行号 2456
   在 Cls_Standard.Cls_账单.结账(B_员工 b_当前员工, Int64 I_班次编号, Decimal 收现金, String C_整单备注, Boolean 强制自动打印结账单) 位置 C:\\Users\\ShengXQ\\Desktop\\ydcxt5\\ydcxt5\\Cls_Standard\\业务逻辑\\Cls_账单.cs:行号 1703
   在 Cls_Standard.BASESYD.ProRequest(String cmd, JObject jo_in, JObject& jo_out, String ip) 位置 C:\\Users\\ShengXQ\\Desktop\\ydcxt5\\ydcxt5\\Cls_Standard\\BASESYD.cs:行号 2371
   在 Cls_Standard.BASESYD.Api(JObject jo_in, String ip) 位置 C:\\Users\\ShengXQ\\Desktop\\ydcxt5\\ydcxt5\\Cls_Standard\\BASESYD.cs:行号 319
```

**Comment by shengxq** [comment]
@zaclic 
This problem has not been solved，If you have a good idea, please share it with me. Thank you！

**Comment by shengxq** [comment]
@praeclarum 
This problem has not been solved，If you have a good idea, please share it with me. Thank you！

**Comment by RichMcLaren** [comment]
@shengxq hey,

I haven't tested it with UpdateAll (only with InsertAll), but I believe the solution is kind of the same.

Try do it this way:
`await this.connection.RunInTransactionAsync(transact => transact.UpdateAll(entities, runInTransaction: false));`

**Comment by shengxq** [comment]
出现这样的问题，一般都是由于并发引起的
进过这一段验证，我认为最好使用静态单实例模式，并且结合lock
保证数据库操作不会并发，就不会出现这样的错误

static SQLiteConnection db；

lock(db){
        // db.Tabel<tabelname>.Where()
        //db.insert()
}


@praeclarum 
能不能在sqlite.net 内部实现单实例,防止并发,这样就更加好了
