### ISSUE TITLE
[Question] Notify/Event that Table or Database Changed? 

### ISSUE THREAD

**Issue by LeoJHarris** [praeclarum/sqlite-net#969]
Hi there, quick question...

In my application I have an app that has a SQLite database using this plugin, my question is whether it is possible to be notified that a table or database has changed? i.e. a new item was added or updated in the database or a particular table table.

Is this possible on the plugin itself?

**Comment by ske66** [comment]
Do you mean the actual columns of the database have changed or a new row has been added/changed?

**Comment by LeoJHarris** [comment]
@ske66 I mean new rows added. Ive actually implemented an event handler for this now but curious if there is a way that this library can provide that functionality out of the box.
