### ISSUE TITLE
Begginer Level Docs

### ISSUE THREAD

**Issue by mytahir** [praeclarum/sqlite-net#997]
Hello Devs, The wiki of this Library really confuses me as it's my first time to use Sqlite-net-pcl, any Docs or Tutorial link would be appreciated, I want use it in my xamarin forms Register and Login Pages. I am begginer in the field. Thank you

**Comment by ske66** [comment]
Hi Mytahir, I wrote the Synchronous connection docs. What is it you're needing help understanding

**Comment by mytahir** [comment]
I took long time time trying to connect the database with Registration Form and Login Form, I also want be good in CRUD Operations. Thank you very much for your Reply!

**Comment by ske66** [comment]
I have updated the Get Started documentation. I recommend having a good read of that as it should be a bit easier to follow. After that, move onto the Synchronous Connection documentation as it explains all 4 basic CRUD operations in both SQL and LINQ format.

**Comment by mytahir** [comment]
Yess! I see, thank you very much. But I see in the Wiki you recommend using AsynchronousAPI on Xamarin.Forms. should I just use SynchronousAPI? Thank You for your Contributions

**Comment by ske66** [comment]
The Async API is faster and more efficient than the synchronous API, but if you are just starting out with this library I would recommend sticking to the Synchronous API for the time being, then when you have a better grasp of how the library holds together, move onto Async calls. Don't let that stop you from giving it a go!

**Comment by mytahir** [comment]
Ok, thank you
